import { afterAll, afterEach, describe, expect, it } from "vitest";
import { prisma } from "@ai-cognitive/db";
import { dispatchPendingIngestion } from "../src/index.js";

const workspaceIds: string[] = [];
class ControlledQueue { readonly ids = new Set<string>(); calls: string[] = []; fail = false; async add(_name: string, payload: { ingestionRunId: string }, options: { jobId?: string }) { this.calls.push(payload.ingestionRunId); if (this.fail) throw new Error("REDIS_UNAVAILABLE"); this.ids.add(options.jobId!); return { id: options.jobId }; } }
async function event(status: "PENDING" | "PROCESSING" = "PENDING", expired = false) { const suffix = crypto.randomUUID(); const user = await prisma.user.create({ data: { email: `${suffix}@test` } }); const workspace = await prisma.workspace.create({ data: { name: suffix } }); workspaceIds.push(workspace.id); await prisma.workspaceMember.create({ data: { workspaceId: workspace.id, userId: user.id, role: "OWNER" } }); const source = await prisma.source.create({ data: { workspaceId: workspace.id, kind: "FILE", displayName: "x" } }); const blob = await prisma.sourceBlob.create({ data: { workspaceId: workspace.id, sha256: suffix, sizeBytes: 1, mediaType: "text/plain", storageKey: `workspaces/${workspace.id}/x` } }); const document = await prisma.sourceDocument.create({ data: { workspaceId: workspace.id, sourceId: source.id, sourceBlobId: blob.id, version: 1, sha256: suffix, sizeBytes: 1, mediaType: "text/plain", storageKey: blob.storageKey } }); const job = await prisma.job.create({ data: { workspaceId: workspace.id, userId: user.id, type: "source.ingest", payload: { sourceDocumentId: document.id }, idempotencyKey: `ingest:${suffix}` } }); const run = await prisma.ingestionRun.create({ data: { workspaceId: workspace.id, sourceDocumentId: document.id, jobId: job.id, parserVersion: "test", normalizationVersion: "test" } }); return prisma.outboxEvent.create({ data: { topic: "source.ingestion.requested", aggregateId: run.id, payload: { ingestionRunId: run.id }, status, leaseUntil: status === "PROCESSING" ? new Date(Date.now() + (expired ? -60_000 : 60_000)) : null } }); }
afterEach(async () => { for (const workspaceId of workspaceIds.splice(0)) { await prisma.outboxEvent.deleteMany({ where: { aggregateId: { in: (await prisma.ingestionRun.findMany({ where: { workspaceId }, select: { id: true } })).map((x) => x.id) } } }); await prisma.ingestionRun.deleteMany({ where: { workspaceId } }); await prisma.job.deleteMany({ where: { workspaceId } }); await prisma.sourceDocument.deleteMany({ where: { workspaceId } }); await prisma.source.deleteMany({ where: { workspaceId } }); await prisma.sourceBlob.deleteMany({ where: { workspaceId } }); await prisma.workspaceMember.deleteMany({ where: { workspaceId } }); await prisma.workspace.delete({ where: { id: workspaceId } }); } }); afterAll(() => prisma.$disconnect());

describe("transactional ingestion outbox", () => {
  it("claims competing events once while allowing independent rows to progress", async () => { const a = await event(), b = await event(); const q = new ControlledQueue(), aggregateIds = [a.aggregateId, b.aggregateId]; await Promise.all([dispatchPendingIngestion(q, { batchSize: 2, aggregateIds }), dispatchPendingIngestion(q, { batchSize: 2, aggregateIds })]); expect(q.ids).toEqual(new Set([(a.payload as { ingestionRunId: string }).ingestionRunId, (b.payload as { ingestionRunId: string }).ingestionRunId])); expect(q.calls).toHaveLength(2); });
  it("does not steal an active lease but reclaims an expired lease", async () => { const active = await event("PROCESSING"), stale = await event("PROCESSING", true); const q = new ControlledQueue(); await dispatchPendingIngestion(q, { aggregateIds: [active.aggregateId, stale.aggregateId] }); expect(q.ids.has((active.payload as { ingestionRunId: string }).ingestionRunId)).toBe(false); expect(q.ids.has((stale.payload as { ingestionRunId: string }).ingestionRunId)).toBe(true); });
  it("retains failures, increments attempts, and eventually fails", async () => { const e = await event(); const q = new ControlledQueue(); q.fail = true; await dispatchPendingIngestion(q, { maxAttempts: 2, aggregateIds: [e.aggregateId] }); await dispatchPendingIngestion(q, { maxAttempts: 2, aggregateIds: [e.aggregateId] }); const current = await prisma.outboxEvent.findUniqueOrThrow({ where: { id: e.id } }); expect(current).toMatchObject({ status: "FAILED", attemptCount: 2 }); expect(current.lastError).toContain("REDIS_UNAVAILABLE"); });
  it("recovers the enqueue/finalize crash window with one deterministic queue job and Job authority", async () => { const e = await event(); const q = new ControlledQueue(); await dispatchPendingIngestion(q, { aggregateIds: [e.aggregateId], beforeFinalize: () => { throw new Error("FINALIZE_FAILURE"); } }); await dispatchPendingIngestion(q, { aggregateIds: [e.aggregateId] }); const current = await prisma.outboxEvent.findUniqueOrThrow({ where: { id: e.id } }); const run = await prisma.ingestionRun.findUniqueOrThrow({ where: { id: (e.payload as { ingestionRunId: string }).ingestionRunId }, include: { job: true } }); expect(q.ids).toEqual(new Set([run.id])); expect(q.calls).toEqual([run.id, run.id]); expect(current.status).toBe("DISPATCHED"); expect(run.job.queueJobId).toBe(run.id); });
});
