import { NextResponse } from "next/server";
import { z } from "zod";
import { createPodcastProject, configureStyle, createEpisode, requestPodcastGeneration } from "@ai-cognitive/podcast-generation";
import { createShortVideoProject, configureShortVideoStyle, requestShortVideoGeneration } from "@ai-cognitive/short-video-generation";
import { resolveWebIdentity } from "@/lib/identity";

const podcast = z.object({ kind:z.literal("podcast"), title:z.string().trim().min(1).max(160), sourceDocumentIds:z.array(z.string().min(1)).min(1).max(8), duration:z.number().int().min(1).max(120).default(10), tone:z.string().trim().min(1).max(160).default("clear, curious, grounded") });
const video = z.object({ kind:z.literal("video"), title:z.string().trim().min(1).max(160), sourceDocumentIds:z.array(z.string().min(1)).min(1).max(8), duration:z.number().int().min(15).max(180).default(60), tone:z.string().trim().min(1).max(160).default("clear, curious, grounded") });
const bodySchema=z.discriminatedUnion("kind",[podcast,video]);
const provider = (kind: "podcast" | "video") => kind === "podcast"
  ? { provider: process.env.PODCAST_GENERATION_PROVIDER?.trim() ?? "", model: process.env.PODCAST_GENERATION_MODEL?.trim() ?? "", modelVersion: process.env.PODCAST_GENERATION_MODEL_VERSION?.trim() }
  : { provider: process.env.SHORT_VIDEO_GENERATION_PROVIDER?.trim() ?? "", model: process.env.SHORT_VIDEO_GENERATION_MODEL?.trim() ?? "", modelVersion: process.env.SHORT_VIDEO_GENERATION_MODEL_VERSION?.trim() };
export async function POST(request:Request){try{const input=bodySchema.parse(await request.json());const context=await resolveWebIdentity();const identity=provider(input.kind);if(!identity.provider||!identity.model)throw new Error("GENERATION_PROVIDER_NOT_CONFIGURED");if(input.kind==="podcast"){const project=await createPodcastProject(context,{name:input.title,sourceDocumentIds:input.sourceDocumentIds});await configureStyle(context,project.id,{targetDurationMinutes:input.duration,tone:input.tone});const episode=await createEpisode(context,{podcastProjectId:project.id,title:input.title,targetDurationMinutes:input.duration});await requestPodcastGeneration(context,{episodeId:episode.id,pipelineVersion:"phase6-web-v1",promptVersion:"phase6-web-v1",...identity});return NextResponse.json({id:episode.id,href:`/studio/podcasts/${episode.id}`});}const project=await createShortVideoProject(context,{name:input.title,sourceDocumentIds:input.sourceDocumentIds});await configureShortVideoStyle(context,project.id,{targetDurationSeconds:input.duration,tone:input.tone});await requestShortVideoGeneration(context,{shortVideoProjectId:project.id,pipelineVersion:"phase6-web-v1",promptVersion:"phase6-web-v1",retrievalVersion:"phase6-web-v1",scenePlannerVersion:"phase6-web-v1",captionVersion:"phase6-web-v1",audioVersion:"phase6-web-v1",renderVersion:"phase6-web-v1",...identity});return NextResponse.json({id:project.id,href:`/studio/videos/${project.id}`});}catch(error){const code=error instanceof Error?error.message:"GENERATION_FAILED";return NextResponse.json({error:code},{status:code.includes("ACCESS_DENIED")?403:400});}}
