import { createCipheriv, createDecipheriv, randomBytes } from "node:crypto";
import { ProviderGatewayError } from "../errors.js";

export type CredentialAad = { workspaceId: string; connectionId: string; credentialVersionId: string; providerKey: string };
export type EncryptedCredential = { ciphertext: string; iv: string; authTag: string; keyVersion: string };
export interface CredentialCipher { encrypt(plaintext: string, aad: CredentialAad): EncryptedCredential; decrypt(value: EncryptedCredential, aad: CredentialAad): string; }
export type EmbeddingResultAad = { workspaceId: string; invocationId: string; attemptId: string; snapshotId: string; providerKey: string; modelId: string };
export interface EmbeddingResultCipher { encryptEmbeddingResult(plaintext: string, aad: EmbeddingResultAad): EncryptedCredential; decryptEmbeddingResult(value: EncryptedCredential, aad: EmbeddingResultAad): string; }
function aadBytes(aad: CredentialAad): Buffer { return Buffer.from(JSON.stringify([aad.workspaceId, aad.connectionId, aad.credentialVersionId, aad.providerKey])); }
function embeddingResultAadBytes(aad: EmbeddingResultAad): Buffer { return Buffer.from(JSON.stringify(["provider-embedding-result-v1", aad.workspaceId, aad.invocationId, aad.attemptId, aad.snapshotId, aad.providerKey, aad.modelId])); }
export class VersionedAesGcmCipher implements CredentialCipher {
  constructor(private readonly activeVersion: string, private readonly keys: ReadonlyMap<string, Buffer>) { if (!keys.has(activeVersion)) throw new ProviderGatewayError("INTERNAL_PROVIDER_ERROR", "Active credential key is unavailable"); for (const key of keys.values()) if (key.length !== 32) throw new ProviderGatewayError("INTERNAL_PROVIDER_ERROR", "Credential encryption keys must be 256-bit"); }
  encrypt(plaintext: string, aad: CredentialAad): EncryptedCredential { const key = this.keys.get(this.activeVersion); if (!key) throw new ProviderGatewayError("INTERNAL_PROVIDER_ERROR"); const iv = randomBytes(12); const cipher = createCipheriv("aes-256-gcm", key, iv); cipher.setAAD(aadBytes(aad)); return { ciphertext: Buffer.concat([cipher.update(plaintext, "utf8"), cipher.final()]).toString("base64"), iv: iv.toString("base64"), authTag: cipher.getAuthTag().toString("base64"), keyVersion: this.activeVersion }; }
  decrypt(value: EncryptedCredential, aad: CredentialAad): string { const key = this.keys.get(value.keyVersion); if (!key) throw new ProviderGatewayError("INTERNAL_PROVIDER_ERROR", "Unknown credential key version"); try { const decipher = createDecipheriv("aes-256-gcm", key, Buffer.from(value.iv, "base64")); decipher.setAAD(aadBytes(aad)); decipher.setAuthTag(Buffer.from(value.authTag, "base64")); return Buffer.concat([decipher.update(Buffer.from(value.ciphertext, "base64")), decipher.final()]).toString("utf8"); } catch { throw new ProviderGatewayError("AUTHORIZATION_FAILED", "Credential integrity validation failed"); } }
  encryptEmbeddingResult(plaintext: string, aad: EmbeddingResultAad): EncryptedCredential { return this.encryptWithAad(plaintext, embeddingResultAadBytes(aad)); }
  decryptEmbeddingResult(value: EncryptedCredential, aad: EmbeddingResultAad): string { try { return this.decryptWithAad(value, embeddingResultAadBytes(aad)); } catch { throw new ProviderGatewayError("INTERNAL_PROVIDER_ERROR", "Embedding result integrity validation failed"); } }
  private encryptWithAad(plaintext: string, aad: Buffer): EncryptedCredential { const key = this.keys.get(this.activeVersion); if (!key) throw new ProviderGatewayError("INTERNAL_PROVIDER_ERROR"); const iv = randomBytes(12); const cipher = createCipheriv("aes-256-gcm", key, iv); cipher.setAAD(aad); return { ciphertext: Buffer.concat([cipher.update(plaintext, "utf8"), cipher.final()]).toString("base64"), iv: iv.toString("base64"), authTag: cipher.getAuthTag().toString("base64"), keyVersion: this.activeVersion }; }
  private decryptWithAad(value: EncryptedCredential, aad: Buffer): string { const key = this.keys.get(value.keyVersion); if (!key) throw new ProviderGatewayError("INTERNAL_PROVIDER_ERROR", "Unknown embedding result key version"); const decipher = createDecipheriv("aes-256-gcm", key, Buffer.from(value.iv, "base64")); decipher.setAAD(aad); decipher.setAuthTag(Buffer.from(value.authTag, "base64")); return Buffer.concat([decipher.update(Buffer.from(value.ciphertext, "base64")), decipher.final()]).toString("utf8"); }
}
export function parseKeyring(input: string | undefined): VersionedAesGcmCipher | undefined { if (!input) return undefined; let value: unknown; try { value = JSON.parse(input); } catch { throw new ProviderGatewayError("INTERNAL_PROVIDER_ERROR", "Invalid provider gateway keyring"); } const record = value as { activeVersion?: unknown; keys?: unknown }; if (typeof record.activeVersion !== "string" || !record.keys || typeof record.keys !== "object") throw new ProviderGatewayError("INTERNAL_PROVIDER_ERROR", "Invalid provider gateway keyring"); const keys = new Map(Object.entries(record.keys as Record<string, unknown>).map(([version, encoded]) => { if (typeof encoded !== "string") throw new ProviderGatewayError("INTERNAL_PROVIDER_ERROR", "Invalid provider gateway key"); return [version, Buffer.from(encoded, "base64")]; })); return new VersionedAesGcmCipher(record.activeVersion, keys); }
