-- Additive Phase 2 lineage hardening. Existing Phase 2 artifacts are versioned;
-- this migration is intended to run before materialization in every environment.
ALTER TABLE "SourceBlock" ADD CONSTRAINT "SourceBlock_id_extractionId_key" UNIQUE ("id", "extractionId");
ALTER TABLE "DocumentStructureNode" ADD CONSTRAINT "DocumentStructureNode_id_extractionId_key" UNIQUE ("id", "extractionId");
ALTER TABLE "DocumentStructureNode" DROP CONSTRAINT "DocumentStructureNode_parentId_fkey";
ALTER TABLE "DocumentStructureNode" ADD CONSTRAINT "DocumentStructureNode_parent_lineage_fkey" FOREIGN KEY ("parentId", "extractionId") REFERENCES "DocumentStructureNode"("id", "extractionId") ON DELETE CASCADE;
ALTER TABLE "ChunkSet" ADD CONSTRAINT "ChunkSet_id_workspaceId_extractionId_key" UNIQUE ("id", "workspaceId", "extractionId");
ALTER TABLE "DocumentChunk" ADD COLUMN "extractionId" TEXT NOT NULL;
ALTER TABLE "DocumentChunk" ADD CONSTRAINT "DocumentChunk_id_extractionId_key" UNIQUE ("id", "extractionId");
ALTER TABLE "DocumentChunk" ADD CONSTRAINT "DocumentChunk_id_workspaceId_chunkSetId_key" UNIQUE ("id", "workspaceId", "chunkSetId");
ALTER TABLE "DocumentChunk" DROP CONSTRAINT "DocumentChunk_chunkSetId_workspaceId_fkey";
ALTER TABLE "DocumentChunk" ADD CONSTRAINT "DocumentChunk_chunkset_lineage_fkey" FOREIGN KEY ("chunkSetId", "workspaceId", "extractionId") REFERENCES "ChunkSet"("id", "workspaceId", "extractionId") ON DELETE CASCADE;
ALTER TABLE "DocumentChunk" DROP CONSTRAINT "DocumentChunk_structureNodeId_fkey";
ALTER TABLE "DocumentChunk" ADD CONSTRAINT "DocumentChunk_structure_lineage_fkey" FOREIGN KEY ("structureNodeId", "extractionId") REFERENCES "DocumentStructureNode"("id", "extractionId") ON DELETE RESTRICT;
ALTER TABLE "ChunkSourceSpan" ADD COLUMN "extractionId" TEXT NOT NULL;
ALTER TABLE "ChunkSourceSpan" DROP CONSTRAINT "ChunkSourceSpan_chunkId_fkey";
ALTER TABLE "ChunkSourceSpan" ADD CONSTRAINT "ChunkSourceSpan_chunk_lineage_fkey" FOREIGN KEY ("chunkId", "extractionId") REFERENCES "DocumentChunk"("id", "extractionId") ON DELETE CASCADE;
ALTER TABLE "ChunkSourceSpan" DROP CONSTRAINT "ChunkSourceSpan_sourceBlockId_fkey";
ALTER TABLE "ChunkSourceSpan" ADD CONSTRAINT "ChunkSourceSpan_block_lineage_fkey" FOREIGN KEY ("sourceBlockId", "extractionId") REFERENCES "SourceBlock"("id", "extractionId") ON DELETE RESTRICT;
ALTER TABLE "BookAnalysisRun" ADD CONSTRAINT "BookAnalysisRun_id_workspaceId_chunkSetId_key" UNIQUE ("id", "workspaceId", "chunkSetId");
ALTER TABLE "BookAnalysisRun" DROP CONSTRAINT "BookAnalysisRun_chunkSetId_workspaceId_fkey";
ALTER TABLE "BookAnalysisRun" ADD CONSTRAINT "BookAnalysisRun_chunkset_lineage_fkey" FOREIGN KEY ("chunkSetId", "workspaceId", "extractionId") REFERENCES "ChunkSet"("id", "workspaceId", "extractionId") ON DELETE RESTRICT;
ALTER TABLE "AnalysisArtifact" ADD COLUMN "workspaceId" TEXT NOT NULL, ADD COLUMN "chunkSetId" TEXT NOT NULL;
ALTER TABLE "AnalysisArtifact" ADD CONSTRAINT "AnalysisArtifact_id_analysisRunId_key" UNIQUE ("id", "analysisRunId");
ALTER TABLE "AnalysisArtifact" DROP CONSTRAINT "AnalysisArtifact_analysisRunId_fkey";
ALTER TABLE "AnalysisArtifact" ADD CONSTRAINT "AnalysisArtifact_run_lineage_fkey" FOREIGN KEY ("analysisRunId", "workspaceId", "chunkSetId") REFERENCES "BookAnalysisRun"("id", "workspaceId", "chunkSetId") ON DELETE CASCADE;
ALTER TABLE "AnalysisArtifact" DROP CONSTRAINT "AnalysisArtifact_parentId_fkey";
ALTER TABLE "AnalysisArtifact" ADD CONSTRAINT "AnalysisArtifact_parent_lineage_fkey" FOREIGN KEY ("parentId", "analysisRunId") REFERENCES "AnalysisArtifact"("id", "analysisRunId") ON DELETE CASCADE;
ALTER TABLE "AnalysisArtifact" DROP CONSTRAINT "AnalysisArtifact_chunkId_fkey";
ALTER TABLE "AnalysisArtifact" ADD CONSTRAINT "AnalysisArtifact_chunk_lineage_fkey" FOREIGN KEY ("chunkId", "workspaceId", "chunkSetId") REFERENCES "DocumentChunk"("id", "workspaceId", "chunkSetId") ON DELETE RESTRICT;
