import { prisma } from "@ai-cognitive/db";

export const PODCAST_GENERATION_OWNERSHIP_LOST = "PODCAST_GENERATION_OWNERSHIP_LOST";
type OwnedTx = Parameters<Parameters<typeof prisma.$transaction>[0]>[0];
export async function assertOwnedPodcastRunInTransaction(tx: OwnedTx, runId: string, token: string, expectedStage?: string): Promise<void> { const rows = await tx.$queryRaw<Array<{ id: string }>>`SELECT "id" FROM "PodcastGenerationRun" WHERE "id" = ${runId} AND "executionClaimToken" = ${token} AND "executionLeaseUntil" > NOW() AND "status" = 'RUNNING'::"PodcastGenerationStatus" AND (${expectedStage ?? null}::text IS NULL OR "stage" = CAST(${expectedStage ?? ""} AS "PodcastGenerationStage")) FOR UPDATE`; if (rows.length !== 1) throw new Error(PODCAST_GENERATION_OWNERSHIP_LOST); }
export async function withOwnedPodcastTransaction<T>(runId: string, token: string, work: (tx: OwnedTx) => Promise<T>): Promise<T> { return prisma.$transaction(async (tx) => { await assertOwnedPodcastRunInTransaction(tx, runId, token); return work(tx); }); }
export async function claimPodcastGenerationRun(runId: string, token: string): Promise<boolean> { return prisma.$transaction(async (tx) => { const rows = await tx.$queryRaw<Array<{ jobId: string; episodeId: string }>>`UPDATE "PodcastGenerationRun" SET "status" = 'RUNNING'::"PodcastGenerationStatus", "stage" = CASE WHEN "stage" = 'QUEUED'::"PodcastGenerationStage" THEN 'EPISODE_PLANNING'::"PodcastGenerationStage" ELSE "stage" END, "startedAt" = COALESCE("startedAt", NOW()), "completedAt" = NULL, "errorCode" = NULL, "executionClaimToken" = ${token}, "executionClaimedAt" = NOW(), "executionLeaseUntil" = NOW() + INTERVAL '2 minutes' WHERE "id" = ${runId} AND "status" <> 'SUCCEEDED'::"PodcastGenerationStatus" AND ("executionClaimToken" IS NULL OR "executionLeaseUntil" < NOW()) RETURNING "jobId", "episodeId"`; if (rows.length !== 1) return false; await tx.$executeRaw`UPDATE "Job" SET "status" = 'RUNNING'::"JobStatus", "startedAt" = COALESCE("startedAt", NOW()), "completedAt" = NULL, "error" = NULL, "attemptCount" = "attemptCount" + 1 WHERE "id" = ${rows[0]!.jobId}`; await tx.$executeRaw`UPDATE "PodcastEpisode" SET "status" = 'GENERATING'::"PodcastEpisodeStatus" WHERE "id" = ${rows[0]!.episodeId}`; return true; }); }
export async function renewPodcastGenerationLease(runId: string, token: string, leaseMs = 120_000): Promise<void> { const changed = await prisma.$executeRaw`UPDATE "PodcastGenerationRun" SET "executionLeaseUntil" = NOW() + (${leaseMs} * INTERVAL '1 millisecond') WHERE "id" = ${runId} AND "executionClaimToken" = ${token} AND "executionLeaseUntil" > NOW() AND "status" = 'RUNNING'::"PodcastGenerationStatus"`; if (changed !== 1) throw new Error(PODCAST_GENERATION_OWNERSHIP_LOST); }
export async function advancePodcastStage(runId: string, token: string, expected: string, next: string): Promise<void> { const changed = await prisma.$executeRaw`UPDATE "PodcastGenerationRun" SET "stage" = CAST(${next} AS "PodcastGenerationStage") WHERE "id" = ${runId} AND "executionClaimToken" = ${token} AND "executionLeaseUntil" > NOW() AND "status" = 'RUNNING'::"PodcastGenerationStatus" AND "stage" = CAST(${expected} AS "PodcastGenerationStage")`; if (changed !== 1) throw new Error(PODCAST_GENERATION_OWNERSHIP_LOST); }
export async function failOwnedPodcastGeneration(runId: string, jobId: string, episodeId: string, token: string, errorCode: string): Promise<boolean> { return prisma.$transaction(async (tx) => { const changed = await tx.$executeRaw`UPDATE "PodcastGenerationRun" SET "status" = 'FAILED'::"PodcastGenerationStatus", "errorCode" = ${errorCode}, "completedAt" = NOW(), "executionClaimToken" = NULL, "executionClaimedAt" = NULL, "executionLeaseUntil" = NULL WHERE "id" = ${runId} AND "executionClaimToken" = ${token} AND "executionLeaseUntil" > NOW() AND "status" = 'RUNNING'::"PodcastGenerationStatus"`; if (changed !== 1) return false; await tx.$executeRaw`UPDATE "Job" SET "status" = 'FAILED'::"JobStatus", "error" = ${JSON.stringify({ code: errorCode })}::jsonb, "completedAt" = NOW() WHERE "id" = ${jobId}`; await tx.$executeRaw`UPDATE "PodcastEpisode" SET "status" = CASE WHEN EXISTS (SELECT 1 FROM "CurrentPodcastScript" WHERE "episodeId" = ${episodeId}) THEN 'READY'::"PodcastEpisodeStatus" ELSE 'FAILED'::"PodcastEpisodeStatus" END WHERE "id" = ${episodeId}`; return true; }); }
