export const BETA_CONSENT_VERSION = "phase17-beta-consent-v1";
export const METRICS_VERSION = "phase17-metrics-v1";
export const EVENT_TAXONOMY_VERSION = "phase17-events-v1";
export const CLIENT_EVENT_NAMES = ["STUDIO_SESSION_STARTED", "PODCAST_PLAYBACK_STARTED", "PODCAST_PLAYBACK_25", "PODCAST_PLAYBACK_50", "PODCAST_PLAYBACK_75", "PODCAST_PLAYBACK_90", "PODCAST_PLAYBACK_ENDED", "ONBOARDING_CHECKLIST_VIEWED", "ONBOARDING_CHECKLIST_DISMISSED"] as const;
export type ClientEventName = (typeof CLIENT_EVENT_NAMES)[number];
export const MAX_EVENT_PROPERTIES_BYTES = 2048;
export const GENERIC_INVITE_ERROR = "BETA_INVITATION_INVALID";
