import { ProviderGatewayError } from "../errors.js";
import { stableHash } from "../routing/snapshot.js";
import type { EmbeddingInput, ModelCapability } from "../types.js";
const limits = { inputs: 96, text: 200_000, total: 1_000_000 };
export function canonicalEmbeddingInputHash(input: EmbeddingInput): string { return stableHash({ texts: input.texts, purpose: input.purpose }); }
export function validateEmbeddingInput(input: EmbeddingInput, capability?: ModelCapability): void { if (!input || !Array.isArray(input.texts) || !["DOCUMENT", "QUERY", "SEMANTIC_SIMILARITY", "CLASSIFICATION", "CLUSTERING"].includes(input.purpose) || input.texts.length < 1 || input.texts.length > (capability?.maxEmbeddingInputs ?? limits.inputs)) throw invalid(); let total = 0; for (const text of input.texts) { if (typeof text !== "string" || !text.trim() || text.length > limits.text) throw invalid(); total += text.length; } if (total > limits.total || (capability?.embeddingPurposes && !capability.embeddingPurposes.includes(input.purpose))) throw new ProviderGatewayError("CAPABILITY_MISMATCH"); }
export function embeddingDimensions(capability: ModelCapability, configuration: Readonly<Record<string, unknown>>): number { const configured = configuration.embeddingDimensions; const raw = configured === undefined ? capability.embeddingDimensions : configured; if (!Number.isSafeInteger(raw)) throw new ProviderGatewayError("CAPABILITY_MISMATCH"); const value = raw as number; if ((capability.embeddingDimensionOptions && !capability.embeddingDimensionOptions.includes(value)) || (capability.minEmbeddingDimensions !== undefined && value < capability.minEmbeddingDimensions) || (capability.maxEmbeddingDimensions !== undefined && value > capability.maxEmbeddingDimensions) || (configured !== undefined && !capability.configurableEmbeddingDimensions && configured !== capability.embeddingDimensions)) throw new ProviderGatewayError("CAPABILITY_MISMATCH"); return value; }
export function validateVectors(vectors: unknown, expectedCount: number, dimensions: number): readonly number[][] { if (!Array.isArray(vectors) || vectors.length !== expectedCount) throw invalid(); return vectors.map(vector => { if (!Array.isArray(vector) || vector.length !== dimensions || vector.some(value => typeof value !== "number" || !Number.isFinite(value)) || !vector.some(value => value !== 0)) throw invalid(); return vector as number[]; }); }
function invalid(): ProviderGatewayError { return new ProviderGatewayError("INVALID_PROVIDER_RESPONSE", "Invalid embedding input or provider response"); }
