import { randomUUID } from "node:crypto";
import { afterEach, describe, expect, it } from "vitest";
import { prisma } from "@ai-cognitive/db";
import { ProviderGatewayRepository, parseKeyring, type GatewayRequest } from "@ai-cognitive/provider-gateway";
import { materializeChunkSet, processBookAnalysisRun, requestBookAnalysisForUser } from "@ai-cognitive/book-intelligence";
import { createBookProductionGatewayRuntime } from "../src/provider-gateway-runtime.js";

const keyring = JSON.stringify({ activeVersion: "v1", keys: { v1: Buffer.alloc(32, 7).toString("base64") } });
const manifest = JSON.stringify({ providers: [{ providerKey: "fixture", displayName: "Fixture", protocol: "TEST", adapterVersion: "test", models: [{ modelId: "fixture-model", families: ["TEXT_GENERATION", "EMBEDDING"], confidence: "VERIFIED", structuredOutput: "STRICT_JSON_SCHEMA", embeddingDimensions: 3, maxEmbeddingInputs: 10, embeddingPurposes: ["DOCUMENT"] }] }] });
const source = { REDIS_URL: "redis://127.0.0.1:6379", NODE_ENV: "test", PROVIDER_GATEWAY_KEYRING: keyring, PROVIDER_GATEWAY_MODEL_MANIFEST: manifest };
const textSchema = { type: "object", additionalProperties: false, required: ["summary"], properties: { summary: { type: "string" } } };
const owned: Array<{ workspaceId: string; userId: string }> = [];
const controls = { circuit: { admit: async () => undefined, recordSuccess: async () => undefined, recordRetryableFailure: async () => undefined }, rate: { admit: async () => undefined }, concurrency: { acquire: async (key: string) => ({ key, token: "test" }), release: async () => true }, validateEndpoint: async () => undefined };
function runtime(calls: { text: number; embedding: number }) {
  return createBookProductionGatewayRuntime(source, {
    ...controls,
    adapterResolver: input => ({ execute: async ({ request }) => {
      if (input.family === "EMBEDDING") {
        calls.embedding++;
        return { response: { vectors: request.embedding!.texts.map(() => [1, 0, 0]), dimensions: 3 } };
      }
      calls.text++;
      return { response: { type: "STRUCTURED", structured: { summary: "durable summary", memory: [{ type: "SUMMARY", content: "durable memory" }] } }, usage: { inputTokens: 1, outputTokens: 1 } };
    } }),
  });
}
async function fixture() { const user = await prisma.user.create({ data: { email: `${randomUUID()}@phase8c.test` } }), ws = await prisma.workspace.create({ data: { name: randomUUID() } }); owned.push({ workspaceId: ws.id, userId: user.id }); await prisma.workspaceMember.create({ data: { workspaceId: ws.id, userId: user.id, role: "OWNER" } }); return { workspaceId: ws.id, userId: user.id }; }
async function routes(f: { workspaceId: string; userId: string }, slots = ["BOOK_CHUNK_ANALYSIS", "BOOK_REDUCTION_ANALYSIS", "BOOK_SYNTHESIS", "EMBEDDING"]) { const store = new ProviderGatewayRepository(prisma, parseKeyring(keyring)!); const connection = await store.createConnection(f, { providerKey: "fixture", protocol: "TEST", displayName: "fixture" }); await store.rotateCredential(f, connection.id, "fixture-secret"); for (const routeSlot of slots) await store.setRoute(f, { routeSlot, connectionId: connection.id, modelId: "fixture-model", configuration: routeSlot === "EMBEDDING" ? { embeddingDimensions: 3 } : {} }); return { store, connection }; }
function request(workspaceId: string, routeSlot: GatewayRequest["routeSlot"], id: string, embedding = false): GatewayRequest { return { workspaceId, routeSlot, correlationId: id, idempotencyKey: id, inputHash: "a".repeat(64), capability: embedding ? { family: "EMBEDDING" } : { family: "TEXT_GENERATION", structuredOutput: "STRICT_JSON_SCHEMA" }, ...(embedding ? { embedding: { texts: ["one"], purpose: "DOCUMENT" } } : { text: { system: "test", messages: [{ role: "user", content: "one" }], structuredOutput: { mode: "STRICT_JSON_SCHEMA", schemaName: "response", schema: textSchema } } }) }; }
async function bookLineage(f: { workspaceId: string; userId: string }) { const sourceRow = await prisma.source.create({ data: { workspaceId: f.workspaceId, kind: "FILE", displayName: "book.md" } }), blob = await prisma.sourceBlob.create({ data: { workspaceId: f.workspaceId, sha256: randomUUID(), sizeBytes: 1, mediaType: "text/markdown", storageKey: `phase8c/${randomUUID()}` } }), document = await prisma.sourceDocument.create({ data: { workspaceId: f.workspaceId, sourceId: sourceRow.id, sourceBlobId: blob.id, version: 1, sha256: randomUUID(), sizeBytes: 1, mediaType: "text/markdown", storageKey: blob.storageKey } }), job = await prisma.job.create({ data: { workspaceId: f.workspaceId, userId: f.userId, type: "source.ingest", payload: {}, idempotencyKey: `ingest:${randomUUID()}` } }), ingestion = await prisma.ingestionRun.create({ data: { workspaceId: f.workspaceId, sourceDocumentId: document.id, jobId: job.id, parserVersion: "test", normalizationVersion: "test" } }), extraction = await prisma.documentExtraction.create({ data: { workspaceId: f.workspaceId, sourceDocumentId: document.id, ingestionRunId: ingestion.id, status: "SUCCEEDED", parserName: "test", parserVersion: "test", normalizationVersion: "test" } }); for (const [ordinal, text] of ["# Chapter", "## Section", "First sufficiently long durable paragraph for the first chunk.", "Second sufficiently long durable paragraph for the second chunk."].entries()) await prisma.sourceBlock.create({ data: { extractionId: extraction.id, ordinal, kind: ordinal < 2 ? "HEADING" : "PARAGRAPH", text, contentHash: randomUUID(), metadata: ordinal < 2 ? { level: ordinal + 1 } : {} } }); await prisma.currentDocumentExtraction.create({ data: { workspaceId: f.workspaceId, sourceDocumentId: document.id, extractionId: extraction.id } }); await materializeChunkSet({ workspaceId: f.workspaceId, sourceDocumentId: document.id, configuration: { targetSize: 40, hardMax: 80 } }); return document; }
afterEach(async () => { for (const f of owned.splice(0)) { await prisma.currentBookIntelligence.deleteMany({ where: { workspaceId: f.workspaceId } }); await prisma.providerTextResult.deleteMany({ where: { workspaceId: f.workspaceId } }); await prisma.providerEmbeddingResult.deleteMany({ where: { workspaceId: f.workspaceId } }); await prisma.providerUsageEvent.deleteMany({ where: { workspaceId: f.workspaceId } }); await prisma.providerInvocationAttempt.deleteMany({ where: { workspaceId: f.workspaceId } }); await prisma.providerInvocation.deleteMany({ where: { workspaceId: f.workspaceId } }); await prisma.providerExecutionSnapshot.deleteMany({ where: { workspaceId: f.workspaceId } }); await prisma.providerRouteBinding.deleteMany({ where: { workspaceId: f.workspaceId } }); await prisma.providerCredentialVersion.deleteMany({ where: { workspaceId: f.workspaceId } }); await prisma.providerConnection.deleteMany({ where: { workspaceId: f.workspaceId } }); await prisma.bookAnalysisRun.deleteMany({ where: { workspaceId: f.workspaceId } }); await prisma.chunkSet.deleteMany({ where: { workspaceId: f.workspaceId } }); await prisma.currentDocumentExtraction.deleteMany({ where: { workspaceId: f.workspaceId } }); await prisma.documentExtraction.deleteMany({ where: { workspaceId: f.workspaceId } }); await prisma.ingestionRun.deleteMany({ where: { workspaceId: f.workspaceId } }); await prisma.job.deleteMany({ where: { workspaceId: f.workspaceId } }); await prisma.sourceDocument.deleteMany({ where: { workspaceId: f.workspaceId } }); await prisma.source.deleteMany({ where: { workspaceId: f.workspaceId } }); await prisma.sourceBlob.deleteMany({ where: { workspaceId: f.workspaceId } }); await prisma.workspaceMember.deleteMany({ where: { workspaceId: f.workspaceId } }); await prisma.workspace.delete({ where: { id: f.workspaceId } }); await prisma.user.delete({ where: { id: f.userId } }); } });

describe("Phase 8C Checkpoint 3B production gateway composition", () => {
  it("P01 valid production startup", () => expect(runtime({ text: 0, embedding: 0 })).toMatchObject({ gateway: expect.any(Object), repository: expect.any(Object) }));
  it("P02 missing keyring fails closed", () => expect(() => createBookProductionGatewayRuntime({ ...source, PROVIDER_GATEWAY_KEYRING: undefined })).toThrow("PROVIDER_GATEWAY_KEYRING_MISSING"));
  it("P03 malformed manifest fails closed", () => expect(() => createBookProductionGatewayRuntime({ ...source, PROVIDER_GATEWAY_MODEL_MANIFEST: "{" })).toThrow("PROVIDER_GATEWAY_MODEL_MANIFEST_INVALID"));
  it("P04 missing BOOK_CHUNK_ANALYSIS route", async () => { const f = await fixture(), calls = { text: 0, embedding: 0 }; await expect(runtime(calls).gateway.execute(request(f.workspaceId, "BOOK_CHUNK_ANALYSIS", "p04"), { userId: f.userId })).rejects.toMatchObject({ code: "ROUTE_UNAVAILABLE" }); expect(calls.text).toBe(0); });
  it("P05 missing EMBEDDING route", async () => { const f = await fixture(), calls = { text: 0, embedding: 0 }; await expect(runtime(calls).gateway.execute(request(f.workspaceId, "EMBEDDING", "p05", true), { userId: f.userId })).rejects.toMatchObject({ code: "ROUTE_UNAVAILABLE" }); expect(calls.embedding).toBe(0); });
  it("P06 disabled connection fails closed", async () => { const f = await fixture(), calls = { text: 0, embedding: 0 }, { store, connection } = await routes(f); await store.setConnectionEnabled(f, connection.id, false); await expect(runtime(calls).gateway.execute(request(f.workspaceId, "BOOK_CHUNK_ANALYSIS", "p06"), { userId: f.userId })).rejects.toMatchObject({ code: "CONNECTION_DISABLED" }); expect(calls.text).toBe(0); });
  it("P07 absent membership fails closed", async () => { const f = await fixture(), calls = { text: 0, embedding: 0 }; await routes(f); const other = await prisma.user.create({ data: { email: `${randomUUID()}@phase8c.test` } }); await expect(runtime(calls).gateway.execute(request(f.workspaceId, "BOOK_CHUNK_ANALYSIS", "p07"), { userId: other.id })).rejects.toMatchObject({ code: "AUTHORIZATION_FAILED" }); expect(calls.text).toBe(0); await prisma.user.delete({ where: { id: other.id } }); });
  it("P08 actor-null path is explicitly rejected by the production authorizer", async () => { const f = await fixture(), calls = { text: 0, embedding: 0 }; await routes(f); await expect(runtime(calls).gateway.execute(request(f.workspaceId, "BOOK_CHUNK_ANALYSIS", "p08"))).rejects.toMatchObject({ code: "AUTHORIZATION_FAILED" }); expect(calls.text).toBe(0); });
  it("P09 workspace A uses only A route", async () => { const a = await fixture(), b = await fixture(), calls = { text: 0, embedding: 0 }; await routes(a); await routes(b); await runtime(calls).gateway.execute(request(a.workspaceId, "BOOK_CHUNK_ANALYSIS", "p09"), { userId: a.userId }); expect(await prisma.providerInvocation.count({ where: { workspaceId: a.workspaceId } })).toBe(1); expect(await prisma.providerInvocation.count({ where: { workspaceId: b.workspaceId } })).toBe(0); });
  it("P10 workspace B uses only B route", async () => { const a = await fixture(), b = await fixture(), calls = { text: 0, embedding: 0 }; await routes(a); await routes(b); await runtime(calls).gateway.execute(request(b.workspaceId, "BOOK_CHUNK_ANALYSIS", "p10"), { userId: b.userId }); expect(await prisma.providerInvocation.count({ where: { workspaceId: b.workspaceId } })).toBe(1); expect(await prisma.providerInvocation.count({ where: { workspaceId: a.workspaceId } })).toBe(0); });
  for (const [label, slot, embedding] of [["P11", "BOOK_CHUNK_ANALYSIS", false], ["P12", "BOOK_REDUCTION_ANALYSIS", false], ["P13", "BOOK_REDUCTION_ANALYSIS", false], ["P14", "BOOK_SYNTHESIS", false], ["P15", "EMBEDDING", true]] as const) it(`${label} uses exact route slot ${slot}`, async () => { const f = await fixture(), calls = { text: 0, embedding: 0 }; await routes(f); await runtime(calls).gateway.execute(request(f.workspaceId, slot, label, embedding), { userId: f.userId }); expect((await prisma.providerExecutionSnapshot.findFirstOrThrow({ where: { workspaceId: f.workspaceId } })).routeSlot).toBe(slot); });
  it("P16 durable text result survives retry with one remote call", async () => { const f = await fixture(), calls = { text: 0, embedding: 0 }, r = runtime(calls); await routes(f); await r.gateway.execute(request(f.workspaceId, "BOOK_CHUNK_ANALYSIS", "p16"), { userId: f.userId }); await r.gateway.execute(request(f.workspaceId, "BOOK_CHUNK_ANALYSIS", "p16"), { userId: f.userId }); expect(calls.text).toBe(1); await expect(Promise.all([prisma.providerExecutionSnapshot.count({ where: { workspaceId: f.workspaceId } }), prisma.providerInvocation.count({ where: { workspaceId: f.workspaceId } }), prisma.providerInvocationAttempt.count({ where: { workspaceId: f.workspaceId } }), prisma.providerUsageEvent.count({ where: { workspaceId: f.workspaceId } }), prisma.providerTextResult.count({ where: { workspaceId: f.workspaceId } })])).resolves.toEqual([1, 1, 1, 1, 1]); });
  it("P17 consumed receipt replay reports textConsumed and performs no remote call", async () => { const f = await fixture(), calls = { text: 0, embedding: 0 }, r = runtime(calls); await routes(f); const first = await r.gateway.execute(request(f.workspaceId, "BOOK_CHUNK_ANALYSIS", "p17"), { userId: f.userId }); if (first.status !== "SUCCEEDED" || !first.invocationId) throw new Error("fixture"); await r.repository.consumeTextResult({ workspaceId: f.workspaceId, invocationId: first.invocationId, snapshotId: first.snapshot.id, consumerKind: "TEST", consumerKey: "p17", consumerFingerprint: "b".repeat(64) }, async () => undefined); await expect(r.gateway.execute(request(f.workspaceId, "BOOK_CHUNK_ANALYSIS", "p17"), { userId: f.userId })).resolves.toMatchObject({ status: "ALREADY_PROCESSED", textConsumed: true }); expect(calls.text).toBe(1); });
  it("P18 consumed missing destination cannot recreate or recall", async () => { const f = await fixture(), calls = { text: 0, embedding: 0 }, r = runtime(calls); await routes(f); const first = await r.gateway.execute(request(f.workspaceId, "BOOK_CHUNK_ANALYSIS", "p18"), { userId: f.userId }); if (first.status !== "SUCCEEDED" || !first.invocationId) throw new Error("fixture"); await r.repository.consumeTextResult({ workspaceId: f.workspaceId, invocationId: first.invocationId, snapshotId: first.snapshot.id, consumerKind: "TEST", consumerKey: "p18", consumerFingerprint: "c".repeat(64) }, async () => undefined); await r.gateway.execute(request(f.workspaceId, "BOOK_CHUNK_ANALYSIS", "p18"), { userId: f.userId }); expect(calls.text).toBe(1); });
  it("P19 durable receipt remains pinned after a route update", async () => { const f = await fixture(), calls = { text: 0, embedding: 0 }, r = runtime(calls), { store, connection } = await routes(f); await r.gateway.execute(request(f.workspaceId, "BOOK_CHUNK_ANALYSIS", "p19"), { userId: f.userId }); await store.setRoute(f, { routeSlot: "BOOK_CHUNK_ANALYSIS", connectionId: connection.id, modelId: "fixture-model" }); await r.gateway.execute(request(f.workspaceId, "BOOK_CHUNK_ANALYSIS", "p19"), { userId: f.userId }); expect(calls.text).toBe(1); });
  it("P20 completes the real production-composed BookAnalysis chain", async () => { const f = await fixture(), document = await bookLineage(f), calls = { text: 0, embedding: 0 }, r = runtime(calls); await routes(f); const requested = await requestBookAnalysisForUser(f, { sourceDocumentId: document.id, pipelineVersion: "p20", promptVersion: "p", provider: "fixture", model: "fixture-model" }); const final = await processBookAnalysisRun(requested.run.id, { analysisProviderForRun: input => r.createAnalysisProvider(input), embeddingGatewayForRun: input => ({ gateway: r.gateway, repository: r.repository, userId: input.userId }) }); expect(final).toMatchObject({ status: "SUCCEEDED", analysisStage: "COMPLETED" }); expect(await prisma.job.findUniqueOrThrow({ where: { id: requested.job.id } })).toMatchObject({ status: "SUCCEEDED" }); expect(await prisma.currentBookIntelligence.findFirst({ where: { workspaceId: f.workspaceId, analysisRunId: requested.run.id } })).toBeTruthy(); expect(calls.text).toBeGreaterThan(0); expect(calls.embedding).toBe(1); });
});
