import { assertBetaOperator, computeClosedBetaMetrics } from "@ai-cognitive/product-analytics";
import { prisma } from "@ai-cognitive/db";
import { resolveWebIdentity } from "@/lib/identity";
import { redirect } from "next/navigation";
import { BetaInviteManager } from "@/components/beta-invite-manager";
export default async function BetaDashboardPage() {
  const identity = await resolveWebIdentity();
  try { await assertBetaOperator(identity.userId); } catch { redirect("/studio"); }
  const [metrics, feedback] = await Promise.all([computeClosedBetaMetrics(new Date()), prisma.betaFeedback.findMany({ orderBy: { createdAt: "desc" }, take: 30, select: { id: true, category: true, dimension: true, rating: true, message: true, createdAt: true, participant: { select: { cohort: true } } } })]);
  return <section><p className="page-eyebrow">CLOSED BETA · INTERNAL</p><h1 className="page-title font-serif">Beta 概览</h1><p className="page-desc">所有百分比均显示实际分母；小样本只作方向性观察，不代表统计结论。</p><div className="cards-grid-3"><article className="card-panel"><h2>激活</h2><p>{metrics.activatedParticipants} / {metrics.enrolledParticipants}</p><small>{metrics.activationRate === null ? "INSUFFICIENT_SAMPLE" : `${Math.round(metrics.activationRate * 100)}%`}</small></article><article className="card-panel"><h2>D1 留存</h2><p>{metrics.d1.retained} / {metrics.d1.eligible}</p></article><article className="card-panel"><h2>D7 留存</h2><p>{metrics.d7.retained} / {metrics.d7.eligible}</p></article><article className="card-panel"><h2>播客完成</h2><p>{metrics.podcast.completedPairs} / {metrics.podcast.startedPairs}</p></article><article className="card-panel"><h2>自然度评分</h2><p>{metrics.podcast.naturalness.median ?? "INSUFFICIENT_SAMPLE"}</p><small>样本 {metrics.podcast.naturalness.sampleCount}</small></article><article className="card-panel"><h2>价值评分</h2><p>{metrics.podcast.value.median ?? "INSUFFICIENT_SAMPLE"}</p><small>样本 {metrics.podcast.value.sampleCount}</small></article><article className="card-panel"><h2>认知保存 / 复习</h2><p>{metrics.cognition.saveUsers} / {metrics.cognition.reviewUsers}</p></article><article className="card-panel"><h2>思考 / Teach Back</h2><p>{metrics.thinking.completedUsers} / {metrics.teachBack.assessedUsers}</p></article></div><BetaInviteManager /><section style={{ marginTop: 32 }}><h2 className="section-title">反馈队列</h2>{feedback.length ? feedback.map((item) => <article className="card-panel" key={item.id}><strong>{item.category} · {item.participant.cohort}</strong><p>{item.message}</p><small>{item.rating ? `${item.rating}/5` : "无评分"} · {item.createdAt.toLocaleString("zh-CN")}</small></article>) : <p>暂无反馈。</p>}</section></section>;
}
