import { describe, expect, it } from "vitest";
import { calculatePhase16Scenarios, estimateProviderCost, p50p95, phase16PricingCatalog, summarizeProviderEfficiency, summarizeRunPerformance } from "../src/index.js";
describe("Phase 16 deterministic cost accounting", () => {
  it("prices cached and uncached text independently using bigint", () => { const full = estimateProviderCost(phase16PricingCatalog, { providerKey: "benchmark", modelId: "text-v1", capability: "TEXT_GENERATION", inputTokens: 1_000_000, cachedInputTokens: 0, outputTokens: 1_000_000 }); const cached = estimateProviderCost(phase16PricingCatalog, { providerKey: "benchmark", modelId: "text-v1", capability: "TEXT_GENERATION", inputTokens: 1_000_000, cachedInputTokens: 500_000, outputTokens: 1_000_000 }); expect(full.estimatedCostMicros).toBe(3_000_000n); expect(cached.estimatedCostMicros).toBe(2_625_000n); });
  it("never converts unknown, missing, invalid, or huge usage to zero", () => { expect(estimateProviderCost(phase16PricingCatalog, { providerKey: "none", modelId: "none", capability: "TEXT_GENERATION", inputTokens: 1 }).quality).toBe("UNPRICED"); expect(estimateProviderCost(phase16PricingCatalog, { providerKey: "benchmark", modelId: "text-v1", capability: "TEXT_GENERATION" }).quality).toBe("MISSING_USAGE"); expect(estimateProviderCost(phase16PricingCatalog, { providerKey: "benchmark", modelId: "text-v1", capability: "TEXT_GENERATION", inputTokens: 2, cachedInputTokens: 3 }).quality).toBe("INVALID_METERING"); });
  it("prices embedding and speech only at their declared unit, including deterministic local character estimates", () => { expect(estimateProviderCost(phase16PricingCatalog, { providerKey: "benchmark", modelId: "embedding-v1", capability: "EMBEDDING", embeddingInputTokens: 1_000_000 }).estimatedCostMicros).toBe(200_000n); expect(estimateProviderCost(phase16PricingCatalog, { providerKey: "benchmark", modelId: "speech-v1", capability: "SPEECH", speechInputCharacters: 1_000_000, usageQuality: "LOCAL_DETERMINISTIC_ESTIMATE" })).toMatchObject({ estimatedCostMicros: 1_500_000n, quality: "LOCAL_DETERMINISTIC_ESTIMATE" }); expect(estimateProviderCost(phase16PricingCatalog, { providerKey: "benchmark", modelId: "speech-v1", capability: "SPEECH", audioDurationMs: 1_000 }).quality).toBe("UNPRICED"); });
  it("does not lose precision for bigint intermediate calculations", () => { const result = estimateProviderCost({ version: "large", entries: [{ providerKey: "p", modelId: "m", capability: "TEXT_GENERATION", unit: "TOKENS", inputMicrosPerMillion: 9_999_999_999n }] }, { providerKey: "p", modelId: "m", capability: "TEXT_GENERATION", inputTokens: Number.MAX_SAFE_INTEGER }); expect(result.estimatedCostMicros).not.toBeNull(); expect((result.estimatedCostMicros ?? 0n) > BigInt(Number.MAX_SAFE_INTEGER)).toBe(true); });
  it("uses documented nearest-rank P50/P95", () => { expect(p50p95([])).toEqual({ p50: null, p95: null }); expect(p50p95([1])).toEqual({ p50: 1, p95: 1 }); expect(p50p95([1, 2, 3, 100])).toEqual({ p50: 2, p95: 100 }); });
  it("derives run timing only from authoritative durable timestamps", () => { const at = (seconds: number) => new Date(seconds * 1_000); expect(summarizeRunPerformance("a", [{ id: "one", workspaceId: "a", createdAt: at(0), dispatchedAt: at(1), startedAt: at(2), completedAt: at(8), providerLatencyMs: 4, retryCount: 1 }, { id: "open", workspaceId: "a", createdAt: at(10) }, { id: "other", workspaceId: "b", createdAt: at(0), startedAt: at(99) }])).toMatchObject({ runCount: 2, completedRunCount: 1, incompleteRunCount: 1, queueWait: { p50: 2_000, p95: 2_000 }, execution: { p50: 6_000, p95: 6_000 }, endToEnd: { p50: 8_000, p95: 8_000 }, outboxDispatch: { p50: 1_000, p95: 1_000 }, retryCount: 1 }); });
  it("requires workspace and bounded time range for tenant-safe summaries", () => { const event = { workspaceId: "a", correlationId: "r", routeSlot: "PODCAST_GENERATION", invocationId: "i", attemptNumber: 1, status: "SUCCEEDED" as const, providerKey: "benchmark", modelId: "text-v1", capability: "TEXT_GENERATION", inputTokens: 100, outputTokens: 10, createdAt: new Date("2026-01-01") }; expect(summarizeProviderEfficiency(phase16PricingCatalog, [event, { ...event, workspaceId: "b", invocationId: "secret" }], { workspaceId: "a", from: new Date("2025-12-31"), to: new Date("2026-01-02") }).invocationCount).toBe(1); });
  it("counts retried invocations once and derives duplicates from durable logical operation identities", () => { const base = { workspaceId: "a", correlationId: "r", routeSlot: "BENCHMARK", status: "SUCCEEDED" as const, providerKey: "benchmark", modelId: "text-v1", capability: "TEXT_GENERATION", inputTokens: 10, createdAt: new Date("2026-01-01") }; const oneRetried = summarizeProviderEfficiency(phase16PricingCatalog, [1, 2, 3].map(attemptNumber => ({ ...base, invocationId: "one", attemptNumber, logicalOperationId: `one:${attemptNumber}` })), { workspaceId: "a", from: new Date("2025-12-31"), to: new Date("2026-01-02") }); expect(oneRetried.retryRate).toBe(1); const halfRetried = summarizeProviderEfficiency(phase16PricingCatalog, [{ ...base, invocationId: "one", attemptNumber: 1 }, { ...base, invocationId: "one", attemptNumber: 2 }, { ...base, invocationId: "two", attemptNumber: 1 }], { workspaceId: "a", from: new Date("2025-12-31"), to: new Date("2026-01-02") }); expect(halfRetried.retryRate).toBe(.5); const replay = summarizeProviderEfficiency(phase16PricingCatalog, [{ ...base, invocationId: "one", attemptNumber: 1, logicalOperationId: "receipt-1" }, { ...base, invocationId: "one", attemptNumber: 1, logicalOperationId: "receipt-1" }, { ...base, invocationId: "redraft", attemptNumber: 2, logicalOperationId: "quality-redraft", intentionalQualityRedraft: true }], { workspaceId: "a", from: new Date("2025-12-31"), to: new Date("2026-01-02") }); expect(replay).toMatchObject({ duplicatePaidOperationCount: 1, duplicatePaidOperationRate: .5 }); });
  it("derives every synthetic scenario estimate from the shared calculator", () => { const scenarios = calculatePhase16Scenarios(); expect(scenarios.map(scenario => scenario.scenario)).toEqual(["BOOK_SMALL", "BOOK_MEDIUM", "BOOK_LARGE", "PODCAST_15_MIN", "PODCAST_30_MIN", "PODCAST_60_MIN"]); for (const scenario of scenarios) expect(estimateProviderCost(phase16PricingCatalog, scenario).estimatedCostMicros).toBe(scenario.estimatedCostMicros); });
});
