import { ProviderGatewayError } from "../errors.js";
import { embeddingDimensions, validateVectors } from "../embedding/validation.js";
import type { EmbeddingPurpose, ProviderAdapter } from "../types.js";
import type { ProviderHttpTransport } from "./http-transport.js";
import { approvedProfile, authHeaders } from "./provider-profiles.js";
import { failureForStatus, header, number, parseJson } from "./shared.js";

type Wire = Parameters<ProviderAdapter["execute"]>[0];
function base(input: Wire, protocol: string) { const profile = approvedProfile(input.snapshot.providerKey, "EMBEDDING", input.snapshot.endpoint, input.snapshot.configuration); if (!profile || profile.protocol !== protocol || !input.request.embedding) throw new ProviderGatewayError("NETWORK_POLICY_REJECTED"); return { profile, embedding: input.request.embedding, dimensions: embeddingDimensions(input.snapshot.capability, input.snapshot.configuration) }; }
function result(input: Wire, vectors: unknown, model: unknown, usage: unknown, requestId: string | undefined, dimensions: number) { const valid = validateVectors(vectors, input.request.embedding!.texts.length, dimensions); return { response: { vectors: valid, dimensions, providerModel: typeof model === "string" ? model : undefined }, usage: usage && typeof usage === "object" ? { embeddingInputTokens: number((usage as Record<string, unknown>).prompt_tokens) ?? number((usage as Record<string, unknown>).input_tokens) ?? number((usage as Record<string, unknown>).billed_units) ?? number((usage as Record<string, unknown>).totalTokenCount) } : undefined, remoteRequestId: requestId }; }
function openAiVectors(json: Record<string, unknown>, count: number): unknown { const values = new Array<unknown>(count); const data = json.data; if (!Array.isArray(data)) throw new ProviderGatewayError("INVALID_PROVIDER_RESPONSE"); for (const item of data) { if (!item || typeof item !== "object") throw new ProviderGatewayError("INVALID_PROVIDER_RESPONSE"); const record = item as Record<string, unknown>; if (!Number.isSafeInteger(record.index) || (record.index as number) < 0 || (record.index as number) >= count || values[record.index as number] !== undefined) throw new ProviderGatewayError("INVALID_PROVIDER_RESPONSE"); values[record.index as number] = record.embedding; } if (values.some(value => value === undefined)) throw new ProviderGatewayError("INVALID_PROVIDER_RESPONSE"); return values; }
export class OpenAIEmbeddingAdapter implements ProviderAdapter { constructor(private readonly transport: ProviderHttpTransport) {} async execute(input: Wire) { const { profile, embedding, dimensions } = base(input, "OPENAI_EMBEDDINGS"); const remote = await this.transport.execute({ url: profile.endpoint, method: "POST", headers: { "content-type": "application/json", ...authHeaders(profile.authScheme, input.credential) }, body: JSON.stringify({ model: input.snapshot.modelId, input: embedding.texts, encoding_format: "float", ...(input.snapshot.capability.configurableEmbeddingDimensions ? { dimensions } : {}) }), signal: input.signal }); failureForStatus(remote); const json = parseJson(remote); return result(input, openAiVectors(json, embedding.texts.length), json.model, json.usage, header(remote.headers, "x-request-id"), dimensions); } }
export class QwenEmbeddingAdapter implements ProviderAdapter { constructor(private readonly transport: ProviderHttpTransport) {} async execute(input: Wire) { const { profile, embedding, dimensions } = base(input, "OPENAI_COMPATIBLE"); const remote = await this.transport.execute({ url: profile.endpoint, method: "POST", headers: { "content-type": "application/json", ...authHeaders(profile.authScheme, input.credential) }, body: JSON.stringify({ model: input.snapshot.modelId, input: embedding.texts, encoding_format: "float", ...(input.snapshot.capability.configurableEmbeddingDimensions ? { dimensions } : {}) }), signal: input.signal }); failureForStatus(remote); const json = parseJson(remote); return result(input, openAiVectors(json, embedding.texts.length), json.model, json.usage, header(remote.headers, "x-request-id"), dimensions); } }
const geminiTask: Record<EmbeddingPurpose, string> = { DOCUMENT: "RETRIEVAL_DOCUMENT", QUERY: "RETRIEVAL_QUERY", SEMANTIC_SIMILARITY: "SEMANTIC_SIMILARITY", CLASSIFICATION: "CLASSIFICATION", CLUSTERING: "CLUSTERING" };
export class GeminiEmbeddingAdapter implements ProviderAdapter { constructor(private readonly transport: ProviderHttpTransport) {} async execute(input: Wire) { const { profile, embedding, dimensions } = base(input, "GEMINI_EMBEDDINGS"); const model = encodeURIComponent(input.snapshot.modelId); const config = { taskType: geminiTask[embedding.purpose], autoTruncate: false, ...(input.snapshot.capability.configurableEmbeddingDimensions ? { outputDimensionality: dimensions } : {}) }; const body = { requests: embedding.texts.map(text => ({ model: `models/${input.snapshot.modelId}`, content: { parts: [{ text }] }, ...config })) }; const remote = await this.transport.execute({ url: `${profile.endpoint}/models/${model}:batchEmbedContents`, method: "POST", headers: { "content-type": "application/json", ...authHeaders(profile.authScheme, input.credential) }, body: JSON.stringify(body), signal: input.signal }); failureForStatus(remote); const json = parseJson(remote); const embeddings = Array.isArray(json.embeddings) ? json.embeddings.map(item => item && typeof item === "object" ? (item as Record<string, unknown>).values : undefined) : undefined; return result(input, embeddings, input.snapshot.modelId, json.usageMetadata, header(remote.headers, "x-request-id"), dimensions); } }
const cohereType: Partial<Record<EmbeddingPurpose, string>> = { DOCUMENT: "search_document", QUERY: "search_query", CLASSIFICATION: "classification", CLUSTERING: "clustering" };
export class CohereEmbeddingAdapter implements ProviderAdapter { constructor(private readonly transport: ProviderHttpTransport) {} async execute(input: Wire) { const { profile, embedding, dimensions } = base(input, "COHERE_EMBEDDINGS_V2"); const inputType = cohereType[embedding.purpose]; if (!inputType) throw new ProviderGatewayError("CAPABILITY_MISMATCH"); const remote = await this.transport.execute({ url: profile.endpoint, method: "POST", headers: { "content-type": "application/json", ...authHeaders(profile.authScheme, input.credential) }, body: JSON.stringify({ model: input.snapshot.modelId, texts: embedding.texts, input_type: inputType, embedding_types: ["float"], truncate: "NONE", ...(input.snapshot.capability.configurableEmbeddingDimensions ? { output_dimension: dimensions } : {}) }), signal: input.signal }); failureForStatus(remote); const json = parseJson(remote); const embeddings = json.embeddings as Record<string, unknown> | undefined; return result(input, embeddings?.float, json.model, json.meta && typeof json.meta === "object" ? (json.meta as Record<string, unknown>).billed_units : undefined, header(remote.headers, "x-request-id"), dimensions); } }
const voyageType: Partial<Record<EmbeddingPurpose, string>> = { DOCUMENT: "document", QUERY: "query" };
export class VoyageEmbeddingAdapter implements ProviderAdapter { constructor(private readonly transport: ProviderHttpTransport) {} async execute(input: Wire) { const { profile, embedding, dimensions } = base(input, "VOYAGE_EMBEDDINGS"); const inputType = voyageType[embedding.purpose]; if (!inputType && embedding.purpose !== "SEMANTIC_SIMILARITY") throw new ProviderGatewayError("CAPABILITY_MISMATCH"); const remote = await this.transport.execute({ url: profile.endpoint, method: "POST", headers: { "content-type": "application/json", ...authHeaders(profile.authScheme, input.credential) }, body: JSON.stringify({ input: embedding.texts, model: input.snapshot.modelId, ...(inputType ? { input_type: inputType } : {}), truncation: false, output_dtype: "float", ...(input.snapshot.capability.configurableEmbeddingDimensions ? { output_dimension: dimensions } : {}) }), signal: input.signal }); failureForStatus(remote); const json = parseJson(remote); return result(input, openAiVectors(json, embedding.texts.length), json.model, json.usage, header(remote.headers, "x-request-id"), dimensions); } }
