import { ProviderAdapterFailure, ProviderGatewayError, type ProviderErrorCode } from "../errors.js";
import { normalizeTextResponse } from "../text/structured-output.js";
import type { ProviderUsage, TextGenerationInput, TextGenerationResponse } from "../types.js";
import type { ProviderHttpResponse } from "./http-transport.js";

export function header(headers: ProviderHttpResponse["headers"], name: string): string | undefined { return headers instanceof Headers ? headers.get(name) ?? undefined : headers[name] ?? headers[name.toLowerCase()]; }
export function parseJson(response: ProviderHttpResponse): Record<string, unknown> { if (response.status >= 300 && response.status < 400) throw failure("NETWORK_POLICY_REJECTED", response); try { const parsed: unknown = JSON.parse(response.body); if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error(); return parsed as Record<string, unknown>; } catch { throw new ProviderGatewayError("INVALID_PROVIDER_RESPONSE", "Malformed provider response"); } }
export function failureForStatus(response: ProviderHttpResponse): void { if (response.status >= 200 && response.status < 300) return; throw failure(response.status >= 300 && response.status < 400 ? "NETWORK_POLICY_REJECTED" : codeForStatus(response.status, response.body), response); }
function failure(code: ProviderErrorCode, response: ProviderHttpResponse): ProviderAdapterFailure { return new ProviderAdapterFailure(code, { remoteRequestId: header(response.headers, "x-request-id") ?? header(response.headers, "request-id"), retryAfterMs: retryAfter(header(response.headers, "retry-after")), message: code }); }
function codeForStatus(status: number, body: string): ProviderErrorCode { const detail = errorDetail(body); if (status === 401) return "AUTHENTICATION_FAILED"; if (status === 403) return "AUTHORIZATION_FAILED"; if (status === 404) return "MODEL_NOT_FOUND"; if (status === 408 || status === 504) return "TIMEOUT"; if (detail.has("insufficient_quota") || detail.has("RESOURCE_EXHAUSTED_QUOTA")) return "QUOTA_EXCEEDED"; if (status === 429) return "RATE_LIMITED"; if (status >= 500) return "TRANSIENT_UPSTREAM"; if (detail.has("context_length_exceeded") || detail.has("INVALID_ARGUMENT_CONTEXT")) return "CONTEXT_LIMIT_EXCEEDED"; if (detail.has("content_filter") || detail.has("SAFETY")) return "CONTENT_REJECTED"; return "INVALID_PROVIDER_RESPONSE"; }
function errorDetail(body: string): ReadonlySet<string> { try { const parsed = JSON.parse(body) as { error?: { type?: unknown; code?: unknown; status?: unknown } }; const error = parsed.error; return new Set([error?.type, error?.code, error?.status].filter((value): value is string => typeof value === "string")); } catch { return new Set(); } }
function retryAfter(value: string | undefined): number | undefined { if (!value) return undefined; const seconds = Number(value); if (Number.isFinite(seconds)) return Math.max(0, Math.min(86_400_000, Math.round(seconds * 1000))); const date = Date.parse(value); return Number.isFinite(date) ? Math.max(0, Math.min(86_400_000, date - Date.now())) : undefined; }
export function response(text: string, model: string | undefined, reason: TextGenerationResponse["finishReason"], input: TextGenerationInput, usage?: ProviderUsage, remoteRequestId?: string) { return { response: normalizeTextResponse(text, model, reason, input), usage, remoteRequestId }; }
export function finish(value: unknown): TextGenerationResponse["finishReason"] { return value === "stop" || value === "STOP" ? "STOP" : value === "length" || value === "MAX_TOKENS" ? "LENGTH" : value === "content_filter" || value === "SAFETY" ? "CONTENT_FILTER" : "OTHER"; }
export function number(value: unknown): number | undefined { return typeof value === "number" && Number.isFinite(value) && value >= 0 ? value : undefined; }
