import { prisma } from "@ai-cognitive/db";
import { randomUUID } from "node:crypto";
import { Redis } from "ioredis";
import { afterAll, afterEach, describe, expect, it } from "vitest";
import { createProductionProviderGateway, DeterministicFakeProviderAdapter, ProviderExecutionRepository, ProviderGatewayError, ProviderRegistry, RedisCircuitBreaker, RedisConcurrencyLimiter, RedisRateLimiter, createExecutionSnapshot } from "../src/index.js";
import type { ExecutionSnapshot } from "../src/index.js";

const workspaces: string[] = [];
async function workspace() { const id = randomUUID(); workspaces.push(id); return prisma.workspace.create({ data: { id, name: `phase8a-${id}` } }); }
function snapshot(workspaceId: string, id = randomUUID()): ExecutionSnapshot { return createExecutionSnapshot({ workspaceId, routeSlot: "BOOK_CHUNK_ANALYSIS", correlationId: "corr", idempotencyKey: "key", inputHash: "a".repeat(64), capability: { family: "TEXT_GENERATION" } }, { source: "PLATFORM", providerKey: "fixture", protocol: "TEST", modelId: "fixture-1", adapterVersion: "test", capability: { modelId: "fixture-1", families: ["TEXT_GENERATION"], confidence: "VERIFIED" }, configuration: {} }, new Date("2026-08-16T00:00:00.000Z"), id); }
afterEach(async () => { for (const id of workspaces.splice(0)) { await prisma.providerUsageEvent.deleteMany({ where: { workspaceId: id } }); await prisma.providerInvocationAttempt.deleteMany({ where: { workspaceId: id } }); await prisma.providerInvocation.deleteMany({ where: { workspaceId: id } }); await prisma.providerExecutionSnapshot.deleteMany({ where: { workspaceId: id } }); await prisma.workspace.delete({ where: { id } }); } });
afterAll(async () => prisma.$disconnect());

describe("ProviderExecutionRepository (PostgreSQL)", () => {
  it("persists a production gateway happy path and blocks malformed input before any claim or call", async () => { const ws = await workspace(); const registry = new ProviderRegistry(); const capability = { modelId: "fixture-1", families: ["TEXT_GENERATION"] as const, confidence: "VERIFIED" as const }; registry.register({ providerKey: "fixture", displayName: "Fixture", protocol: "TEST", adapterVersion: "test", models: [capability] }); const adapter = new DeterministicFakeProviderAdapter(); const gateway = createProductionProviderGateway(registry, { resolveWorkspaceRoute: async () => undefined }, { resolve: async () => ({ source: "PLATFORM", providerKey: "fixture", protocol: "TEST", modelId: "fixture-1", adapterVersion: "test", capability, configuration: {} }) }, () => adapter, { authorize: async () => undefined, assertRouteUsable: async () => undefined, validateEndpoint: async () => undefined, assertBudget: () => undefined, repository: new ProviderExecutionRepository(), circuit: { admit: async () => undefined, recordSuccess: async () => undefined, recordRetryableFailure: async () => undefined }, rate: { admit: async () => undefined }, concurrency: { acquire: async key => ({ key, token: "lease" }), release: async () => true } }); const valid = { workspaceId: ws.id, routeSlot: "BOOK_CHUNK_ANALYSIS" as const, correlationId: "corr", idempotencyKey: "happy", inputHash: "a".repeat(64), capability: { family: "TEXT_GENERATION" as const } }; await expect(gateway.execute(valid, { userId: "owner" })).resolves.toMatchObject({ status: "SUCCEEDED" }); expect(adapter.calls).toBe(1); expect(await prisma.providerExecutionSnapshot.count({ where: { workspaceId: ws.id } })).toBe(1); expect(await prisma.providerInvocation.count({ where: { workspaceId: ws.id, status: "SUCCEEDED" } })).toBe(1); expect(await prisma.providerInvocationAttempt.count({ where: { workspaceId: ws.id, status: "SUCCEEDED" } })).toBe(1); expect(await prisma.providerUsageEvent.findFirstOrThrow({ where: { workspaceId: ws.id } })).toMatchObject({ inputTokens: 1, cachedInputTokens: 1, outputTokens: 1 }); await expect(gateway.execute({ ...valid, idempotencyKey: "bad", inputHash: "not-a-hash" }, { userId: "owner" })).rejects.toMatchObject({ code: "INVALID_PROVIDER_RESPONSE" }); expect(adapter.calls).toBe(1); });
  it("applies the shared Redis rate limiter through independently connected production gateways", async () => { const ws = await workspace(); const redisA = new Redis(process.env.REDIS_URL ?? "redis://localhost:6379"); const redisB = new Redis(process.env.REDIS_URL ?? "redis://localhost:6379"); try { const registry = new ProviderRegistry(); const capability = { modelId: "fixture-1", families: ["TEXT_GENERATION"] as const, confidence: "VERIFIED" as const }; registry.register({ providerKey: "fixture", displayName: "Fixture", protocol: "TEST", adapterVersion: "test", models: [capability] }); const adapter = new DeterministicFakeProviderAdapter(); const build = (redis: Redis) => createProductionProviderGateway(registry, { resolveWorkspaceRoute: async () => undefined }, { resolve: async () => ({ source: "PLATFORM" as const, providerKey: "fixture", protocol: "TEST" as const, modelId: "fixture-1", adapterVersion: "test", capability, configuration: {} }) }, () => adapter, { authorize: async () => undefined, assertRouteUsable: async () => undefined, validateEndpoint: async () => undefined, assertBudget: () => undefined, repository: new ProviderExecutionRepository(), circuit: new RedisCircuitBreaker(redis), rate: new RedisRateLimiter(redis), concurrency: new RedisConcurrencyLimiter(redis), rateLimit: 1, rateWindowSeconds: 60 }); const request = { workspaceId: ws.id, routeSlot: "BOOK_CHUNK_ANALYSIS" as const, correlationId: "redis", idempotencyKey: "one", inputHash: "a".repeat(64), capability: { family: "TEXT_GENERATION" as const } }; await expect(build(redisA).execute(request, { userId: "owner" })).resolves.toMatchObject({ status: "SUCCEEDED" }); await expect(build(redisB).execute({ ...request, idempotencyKey: "two", inputHash: "b".repeat(64) }, { userId: "owner" })).rejects.toMatchObject({ code: "RATE_LIMITED" }); expect(adapter.calls).toBe(1); expect(await prisma.providerInvocationAttempt.count({ where: { workspaceId: ws.id } })).toBe(1); } finally { const keys = await redisA.keys(`provider-gateway:*:${ws.id}:*`); if (keys.length) await redisA.del(...keys); await Promise.all([redisA.quit(), redisB.quit()]); } });
  it("atomically suppresses concurrent duplicate claims and distinguishes completed execution", async () => { const ws = await workspace(); const a = new ProviderExecutionRepository(); const b = new ProviderExecutionRepository(); const [first, second] = await Promise.all([a.claimExecution(snapshot(ws.id), { idempotencyKey: "same", fingerprint: "f".repeat(64) }), b.claimExecution(snapshot(ws.id), { idempotencyKey: "same", fingerprint: "f".repeat(64) })]); const owner = first.kind === "OWNER" ? first : second; const duplicate = first.kind === "OWNER" ? second : first; expect(owner.kind).toBe("OWNER"); expect(duplicate.kind).toBe("IN_PROGRESS"); expect(await prisma.providerInvocation.count({ where: { workspaceId: ws.id } })).toBe(1); if (owner.kind !== "OWNER") throw new Error("owner missing"); await a.completeInvocation(ws.id, owner.invocationId, owner.claimToken, "SUCCEEDED"); await expect(b.claimExecution(snapshot(ws.id), { idempotencyKey: "same", fingerprint: "f".repeat(64) })).resolves.toMatchObject({ kind: "ALREADY_PROCESSED" }); await expect(b.claimExecution(snapshot(ws.id), { idempotencyKey: "same", fingerprint: "e".repeat(64) })).rejects.toMatchObject({ code: "IDEMPOTENCY_CONFLICT" }); });
  it("rejects a stale owner after a zero-attempt lease is safely reclaimed", async () => { const ws = await workspace(); let clock = new Date("2026-08-16T00:00:00.000Z"); const old = new ProviderExecutionRepository(prisma, undefined, () => clock, "old"); const claimA = await old.claimExecution(snapshot(ws.id), { idempotencyKey: "stale", fingerprint: "a".repeat(64) }); if (claimA.kind !== "OWNER") throw new Error("first claim missing"); clock = new Date(clock.getTime() + 61_000); const current = new ProviderExecutionRepository(prisma, undefined, () => clock, "new"); const claimB = await current.claimExecution(snapshot(ws.id), { idempotencyKey: "stale", fingerprint: "a".repeat(64) }); expect(claimB).toMatchObject({ kind: "OWNER" }); await expect(old.startAttempt(ws.id, claimA.invocationId, claimA.claimToken)).rejects.toBeInstanceOf(ProviderGatewayError); });
  it("returns terminal states and converts a stale running attempt to reconciliation-required", async () => { const ws = await workspace(); let clock = new Date("2026-08-16T00:00:00.000Z"); const repository = new ProviderExecutionRepository(prisma, undefined, () => clock, "worker", 20); const failed = await repository.claimExecution(snapshot(ws.id), { idempotencyKey: "failed", fingerprint: "f".repeat(64) }); if (failed.kind !== "OWNER") throw new Error("claim missing"); await repository.completeInvocation(ws.id, failed.invocationId, failed.claimToken, "FAILED"); await expect(repository.claimExecution(snapshot(ws.id), { idempotencyKey: "failed", fingerprint: "f".repeat(64) })).resolves.toMatchObject({ kind: "TERMINAL_FAILED" }); const active = await repository.claimExecution(snapshot(ws.id), { idempotencyKey: "unknown", fingerprint: "u".repeat(64) }); if (active.kind !== "OWNER") throw new Error("claim missing"); await repository.startAttempt(ws.id, active.invocationId, active.claimToken); clock = new Date(clock.getTime() + 21); await expect(repository.claimExecution(snapshot(ws.id), { idempotencyKey: "unknown", fingerprint: "u".repeat(64) })).resolves.toMatchObject({ kind: "RECONCILIATION_REQUIRED" }); expect(await prisma.providerInvocation.findUniqueOrThrow({ where: { id_workspaceId: { id: active.invocationId, workspaceId: ws.id } } })).toMatchObject({ status: "RECONCILIATION_REQUIRED" }); });
});
