import { prisma } from "@ai-cognitive/db";
import { randomUUID } from "node:crypto";
import { afterAll, afterEach, describe, expect, it } from "vitest";
import { ProviderExecutionRepository, createExecutionSnapshot } from "../src/index.js";

const workspaces: string[] = [];
async function fixture() { const workspaceId = randomUUID(); workspaces.push(workspaceId); await prisma.workspace.create({ data: { id: workspaceId, name: "recovery" } }); const snapshot = createExecutionSnapshot({ workspaceId, routeSlot: "BOOK_CHUNK_ANALYSIS", correlationId: "recovery", idempotencyKey: "recovery", inputHash: "a".repeat(64), capability: { family: "TEXT_GENERATION" } }, { source: "PLATFORM", providerKey: "fixture", protocol: "TEST", modelId: "fixture-1", adapterVersion: "test", capability: { modelId: "fixture-1", families: ["TEXT_GENERATION"], confidence: "VERIFIED" }, configuration: {} }); return { workspaceId, snapshot }; }
afterEach(async () => { for (const id of workspaces.splice(0)) { await prisma.providerUsageEvent.deleteMany({ where: { workspaceId: id } }); await prisma.providerInvocationAttempt.deleteMany({ where: { workspaceId: id } }); await prisma.providerInvocation.deleteMany({ where: { workspaceId: id } }); await prisma.providerExecutionSnapshot.deleteMany({ where: { workspaceId: id } }); await prisma.workspace.delete({ where: { id } }); } }); afterAll(async () => prisma.$disconnect());
describe("gateway recovery matrix (PostgreSQL)", () => { it("returns in-progress for a live owner and reclaims an expired zero-attempt invocation", async () => { const { workspaceId, snapshot } = await fixture(); const owner = new ProviderExecutionRepository(); const active = await owner.claimExecution(snapshot, { idempotencyKey: "active", fingerprint: "a".repeat(64) }); if (active.kind !== "OWNER") throw new Error("owner claim required"); await expect(new ProviderExecutionRepository().claimExecution(snapshot, { idempotencyKey: "active", fingerprint: "a".repeat(64) })).resolves.toMatchObject({ kind: "IN_PROGRESS" }); await prisma.$executeRaw`UPDATE "ProviderInvocation" SET "claimExpiresAt" = CURRENT_TIMESTAMP - INTERVAL '1 millisecond' WHERE "id" = ${active.invocationId} AND "workspaceId" = ${workspaceId}`; await expect(new ProviderExecutionRepository().claimExecution(snapshot, { idempotencyKey: "active", fingerprint: "a".repeat(64) })).resolves.toMatchObject({ kind: "OWNER" }); }); });
