import { prisma } from "@ai-cognitive/db";
import { randomUUID } from "node:crypto";
import { Redis } from "ioredis";
import { afterAll, afterEach, describe, expect, it, vi } from "vitest";
import { ProviderAdapterFailure, ProviderExecutionRepository, ProviderGatewayRepository, ProviderRegistry, RedisCircuitBreaker, RedisConcurrencyLimiter, RedisRateLimiter, createExecutionSnapshot, createProductionProviderGateway, testCipher, type ProviderAdapter } from "../src/index.js";

const workspaceIds: string[] = [];
const redisKey = `v17-${randomUUID()}`;
let redisA: Redis | undefined;
let redisB: Redis | undefined;
const capability = { modelId: "fixture-1", families: ["TEXT_GENERATION"] as const, confidence: "VERIFIED" as const };

function deferred<T = void>() { let resolve!: (value: T) => void; let reject!: (error: unknown) => void; const promise = new Promise<T>((res, rej) => { resolve = res; reject = rej; }); return { promise, resolve, reject }; }
async function workspace(name: string) { const id = randomUUID(); workspaceIds.push(id); return prisma.workspace.create({ data: { id, name } }); }
function request(workspaceId: string, idempotencyKey: string) { return { workspaceId, routeSlot: "BOOK_CHUNK_ANALYSIS" as const, correlationId: idempotencyKey, idempotencyKey, inputHash: "a".repeat(64), capability: { family: "TEXT_GENERATION" as const } }; }
function registry() { const value = new ProviderRegistry(); value.register({ providerKey: "fixture", displayName: "Fixture", protocol: "TEST", adapterVersion: "test", models: [capability] }); return value; }
function route() { return { source: "PLATFORM" as const, providerKey: "fixture", protocol: "TEST" as const, modelId: "fixture-1", adapterVersion: "test", capability, configuration: {} }; }
function gateway(adapter: ProviderAdapter, repository = new ProviderExecutionRepository(), controls: { circuit?: RedisCircuitBreaker; rate?: RedisRateLimiter; concurrency?: RedisConcurrencyLimiter; circuitThreshold?: number; circuitCooldownMs?: number; concurrencyLimit?: number } = {}) {
  return createProductionProviderGateway(registry(), { resolveWorkspaceRoute: async () => undefined }, { resolve: async () => route() }, () => adapter, {
    authorize: async () => undefined, assertRouteUsable: async () => undefined, validateEndpoint: async () => undefined, assertBudget: () => undefined, repository,
    circuit: controls.circuit ?? { admit: async () => undefined, recordSuccess: async () => undefined, recordRetryableFailure: async () => undefined }, rate: controls.rate ?? { admit: async () => undefined }, concurrency: controls.concurrency ?? { acquire: async key => ({ key, token: randomUUID() }), release: async () => true },
    circuitThreshold: controls.circuitThreshold, circuitCooldownMs: controls.circuitCooldownMs, concurrencyLimit: controls.concurrencyLimit, maxAttempts: 1,
  });
}
async function expire(workspaceId: string, invocationId: string) { await prisma.$executeRaw`UPDATE "ProviderInvocation" SET "claimExpiresAt" = CURRENT_TIMESTAMP - INTERVAL '1 millisecond' WHERE "workspaceId" = ${workspaceId} AND "id" = ${invocationId}`; }

afterEach(async () => { vi.restoreAllMocks(); for (const id of workspaceIds.splice(0)) { await prisma.providerUsageEvent.deleteMany({ where: { workspaceId: id } }); await prisma.providerInvocationAttempt.deleteMany({ where: { workspaceId: id } }); await prisma.providerInvocation.deleteMany({ where: { workspaceId: id } }); await prisma.providerExecutionSnapshot.deleteMany({ where: { workspaceId: id } }); await prisma.providerRouteBinding.deleteMany({ where: { workspaceId: id } }); await prisma.providerCredentialVersion.deleteMany({ where: { workspaceId: id } }); await prisma.providerConnection.deleteMany({ where: { workspaceId: id } }); await prisma.providerAuditEvent.deleteMany({ where: { workspaceId: id } }); await prisma.workspaceMember.deleteMany({ where: { workspaceId: id } }); await prisma.workspace.delete({ where: { id } }); } });
afterAll(async () => { if (redisA) { const keys = await redisA.keys(`provider-gateway:*:${redisKey}:*`); if (keys.length) await redisA.del(...keys); } await Promise.all([redisA?.quit(), redisB?.quit(), prisma.$disconnect()]); });

describe("Phase 8A V17 acceptance evidence", () => {
  it("uses two independently constructed gateways for a shared Redis concurrency lease", async () => {
    const ws = await workspace("v17-concurrency"); redisA = new Redis(process.env.REDIS_URL ?? "redis://localhost:6379"); redisB = new Redis(process.env.REDIS_URL ?? "redis://localhost:6379");
    const entered = deferred(); const release = deferred(); let callsA = 0; let callsB = 0;
    const a = gateway({ execute: async () => { callsA++; entered.resolve(); await release.promise; return { response: { from: "a" } }; } }, new ProviderExecutionRepository(), { concurrency: new RedisConcurrencyLimiter(redisA), concurrencyLimit: 1 });
    const b = gateway({ execute: async () => { callsB++; return { response: { from: "b" } }; } }, new ProviderExecutionRepository(), { concurrency: new RedisConcurrencyLimiter(redisB), concurrencyLimit: 1 });
    const running = a.execute(request(ws.id, `${redisKey}:a`), { userId: "owner" }); await entered.promise;
    const attemptsBefore = await prisma.providerInvocationAttempt.count({ where: { workspaceId: ws.id } }); await expect(b.execute(request(ws.id, `${redisKey}:b`), { userId: "owner" })).rejects.toMatchObject({ code: "RATE_LIMITED" }); expect(callsB).toBe(0); expect(await prisma.providerInvocationAttempt.count({ where: { workspaceId: ws.id } })).toBe(attemptsBefore);
    release.resolve(); await expect(running).resolves.toMatchObject({ status: "SUCCEEDED" }); await expect(b.execute(request(ws.id, `${redisKey}:later`), { userId: "owner" })).resolves.toMatchObject({ status: "SUCCEEDED" }); expect(callsA).toBe(1); expect(callsB).toBe(1);
  });

  it("shares OPEN and allows exactly one HALF_OPEN probe through two real gateways", async () => {
    const ws = await workspace("v17-circuit"); redisA = redisA ?? new Redis(process.env.REDIS_URL ?? "redis://localhost:6379"); redisB = redisB ?? new Redis(process.env.REDIS_URL ?? "redis://localhost:6379"); const cooldown = 5_000; const circuitKey = `provider-gateway:circuit:${ws.id}:fixture:fixture-1`; let aCalls = 0; let bCalls = 0; let failA = true; let blockProbe = false; const probeEntered = deferred(); const releaseProbe = deferred();
    const a = gateway({ execute: async () => { aCalls++; if (failA) throw new ProviderAdapterFailure("TRANSIENT_UPSTREAM", { retryable: true }); if (blockProbe) { probeEntered.resolve(); await releaseProbe.promise; } return { response: { ok: true } }; } }, new ProviderExecutionRepository(), { circuit: new RedisCircuitBreaker(redisA), circuitThreshold: 1, circuitCooldownMs: cooldown });
    const b = gateway({ execute: async () => { bCalls++; if (blockProbe) { probeEntered.resolve(); await releaseProbe.promise; } return { response: { ok: true } }; } }, new ProviderExecutionRepository(), { circuit: new RedisCircuitBreaker(redisB), circuitThreshold: 1, circuitCooldownMs: cooldown });
    await expect(a.execute(request(ws.id, `${redisKey}:open`), { userId: "owner" })).rejects.toMatchObject({ code: "TRANSIENT_UPSTREAM" }); const attemptsBefore = await prisma.providerInvocationAttempt.count({ where: { workspaceId: ws.id } }); await expect(b.execute(request(ws.id, `${redisKey}:closed`), { userId: "owner" })).rejects.toMatchObject({ code: "CIRCUIT_OPEN" }); expect(bCalls).toBe(0); expect(await prisma.providerInvocationAttempt.count({ where: { workspaceId: ws.id } })).toBe(attemptsBefore);
    failA = false; blockProbe = true; await redisA.hset(circuitKey, "state", "OPEN", "openedUntil", `${Date.now() - 1}`); const candidateA = a.execute(request(ws.id, `${redisKey}:probe-a`), { userId: "owner" }); const candidateB = b.execute(request(ws.id, `${redisKey}:probe-b`), { userId: "owner" }); const allCandidates = Promise.allSettled([candidateA, candidateB]); await probeEntered.promise; expect(aCalls + bCalls).toBe(2); releaseProbe.resolve(); const probes = await allCandidates; expect(probes.filter(result => result.status === "fulfilled")).toHaveLength(1); blockProbe = false; await expect(b.execute(request(ws.id, `${redisKey}:after-probe`), { userId: "owner" })).resolves.toMatchObject({ status: "SUCCEEDED" });
    failA = true; await expect(a.execute(request(ws.id, `${redisKey}:reopen`), { userId: "owner" })).rejects.toMatchObject({ code: "TRANSIENT_UPSTREAM" }); await redisA.hset(circuitKey, "state", "OPEN", "openedUntil", `${Date.now() - 1}`); await expect(a.execute(request(ws.id, `${redisKey}:failed-probe`), { userId: "owner" })).rejects.toMatchObject({ code: "TRANSIENT_UPSTREAM" }); const bCallsBefore = bCalls; await expect(b.execute(request(ws.id, `${redisKey}:after-failed-probe`), { userId: "owner" })).rejects.toMatchObject({ code: "CIRCUIT_OPEN" }); expect(bCalls).toBe(bCallsBefore);
  });

  it("drains an in-flight failed heartbeat without finalizing success or replaying", async () => {
    const ws = await workspace("v17-heartbeat"); const repository = new ProviderExecutionRepository(prisma, undefined, undefined, "heartbeat", 300); const entered = deferred(); const releaseRenew = deferred(); let renewals = 0; let firstRenewalSucceeded = false; const original = repository.renewClaim.bind(repository);
    vi.spyOn(repository, "renewClaim").mockImplementation(async (...args) => { renewals++; if (renewals === 1) { await original(...args); firstRenewalSucceeded = true; return; } entered.resolve(); await expire(args[0], args[1]); await releaseRenew.promise; return original(...args); }); let calls = 0; const subject = gateway({ execute: async () => { calls++; await entered.promise; return { response: { ok: true } }; } }, repository);
    const input = request(ws.id, "heartbeat-loss"); const execution = subject.execute(input, { userId: "owner" }); await entered.promise; expect(firstRenewalSucceeded).toBe(true); expect(renewals).toBe(2); releaseRenew.resolve(); await expect(execution).rejects.toMatchObject({ code: "INTERNAL_PROVIDER_ERROR" }); const invocation = await prisma.providerInvocation.findFirstOrThrow({ where: { workspaceId: ws.id } }); expect(invocation.status).toBe("RUNNING"); await expect(subject.execute(input, { userId: "owner" })).resolves.toMatchObject({ status: "RECONCILIATION_REQUIRED" }); expect(calls).toBe(1);
  });

  it.each([["success", "attempt outcome"], ["success", "usage"], ["transient", "attempt outcome"], ["transient", "usage"]] as const)("never replays when %s %s accounting fails", async (kind, boundary) => {
    const ws = await workspace(`v17-${kind}-${boundary}`); let calls = 0; const hugeUsage = { extra: { payload: "x".repeat(8_193) } }; const adapter = { execute: async () => { calls++; if (kind === "transient") throw new ProviderAdapterFailure("TRANSIENT_UPSTREAM", { retryable: true, usage: boundary === "usage" ? hugeUsage : undefined }); return { response: { ok: true }, usage: boundary === "usage" ? hugeUsage : undefined }; } }; const repository = new ProviderExecutionRepository(); if (boundary === "attempt outcome") vi.spyOn(repository, "recordAttemptOutcome").mockRejectedValueOnce(new Error("attempt outcome boundary fault")); const subject = gateway(adapter, repository); const input = request(ws.id, `${kind}-${boundary}`);
    await expect(subject.execute(input, { userId: "owner" })).rejects.toMatchObject({ code: "INTERNAL_PROVIDER_ERROR" }); const invocation = await prisma.providerInvocation.findFirstOrThrow({ where: { workspaceId: ws.id } }); expect(invocation.status).toBe("RECONCILIATION_REQUIRED"); expect(await prisma.providerInvocationAttempt.count({ where: { workspaceId: ws.id, status: "REMOTE_FAILURE" } })).toBe(0); await expect(subject.execute(input, { userId: "owner" })).resolves.toMatchObject({ status: "RECONCILIATION_REQUIRED" }); expect(calls).toBe(1);
  });

  it("classifies the complete stale recovery matrix using PostgreSQL time", async () => {
    const ws = await workspace("v17-recovery"); const repository = new ProviderExecutionRepository(); const make = async (key: string, attemptStatus?: "RUNNING" | "SUCCEEDED" | "REMOTE_FAILURE" | "TIMEOUT" | "CANCELLED_AFTER_REQUEST") => { const snapshot = createExecutionSnapshot(request(ws.id, `recovery-${key}`), route()); const claim = await repository.claimExecution(snapshot, { idempotencyKey: key, fingerprint: key.padEnd(64, "0") }); if (claim.kind !== "OWNER") throw new Error("owner required"); if (attemptStatus) { const attempt = await repository.startAttempt(ws.id, claim.invocationId, claim.claimToken); if (attemptStatus !== "RUNNING") await repository.completeAttempt(ws.id, claim.invocationId, claim.claimToken, attempt.id, attemptStatus, { latencyMs: 1 }); } await expire(ws.id, claim.invocationId); return repository.claimExecution(snapshot, { idempotencyKey: key, fingerprint: key.padEnd(64, "0") }); };
    await expect(make("zero")).resolves.toMatchObject({ kind: "OWNER" }); await expect(make("running", "RUNNING")).resolves.toMatchObject({ kind: "RECONCILIATION_REQUIRED" }); await expect(make("succeeded", "SUCCEEDED")).resolves.toMatchObject({ kind: "RECONCILIATION_REQUIRED" }); await expect(make("failed", "REMOTE_FAILURE")).resolves.toMatchObject({ kind: "TERMINAL_FAILED" }); await expect(make("timeout", "TIMEOUT")).resolves.toMatchObject({ kind: "RECONCILIATION_REQUIRED" }); await expect(make("cancelled", "CANCELLED_AFTER_REQUEST")).resolves.toMatchObject({ kind: "RECONCILIATION_REQUIRED" });
  });

  it("redacts the exact encrypted credential when usage is persisted through Gateway.execute", async () => {
    const ws = await workspace("v17-secret"); const userId = randomUUID(); await prisma.user.create({ data: { id: userId, email: `${userId}@test.invalid` } }); await prisma.workspaceMember.create({ data: { workspaceId: ws.id, userId, role: "OWNER" } }); const cipher = testCipher(); const store = new ProviderGatewayRepository(prisma, cipher); const connection = await store.createConnection({ workspaceId: ws.id, userId }, { providerKey: "fixture", protocol: "TEST", displayName: "fixture" }); const secret = "exact-v17-secret-credential-123456"; await store.rotateCredential({ workspaceId: ws.id, userId }, connection.id, secret); await store.setRoute({ workspaceId: ws.id, userId }, { routeSlot: "BOOK_CHUNK_ANALYSIS", connectionId: connection.id, modelId: "fixture-1" }); let calls = 0;
    const subject = createProductionProviderGateway(registry(), { resolveWorkspaceRoute: input => store.resolveWorkspaceRoute(input) }, { resolve: async () => undefined }, () => ({ execute: async () => { calls++; return { response: { ok: true }, usage: { extra: { nested: { echoed: `Bearer ${secret}` }, wrapped: JSON.stringify({ value: secret }) } } }; } }), { authorize: async () => undefined, assertRouteUsable: async () => undefined, validateEndpoint: async () => undefined, assertBudget: () => undefined, repository: new ProviderExecutionRepository(prisma, cipher), circuit: { admit: async () => undefined, recordSuccess: async () => undefined, recordRetryableFailure: async () => undefined }, rate: { admit: async () => undefined }, concurrency: { acquire: async key => ({ key, token: "lease" }), release: async () => true } });
    await expect(subject.execute(request(ws.id, "exact-secret"), { userId })).resolves.toMatchObject({ status: "SUCCEEDED" }); const usage = await prisma.providerUsageEvent.findFirstOrThrow({ where: { workspaceId: ws.id } }); const serialized = JSON.stringify(usage.metadata); expect(serialized).not.toContain(secret); expect(serialized.length).toBeLessThanOrEqual(8_192); expect(calls).toBe(1);
  });
});
