import { prisma } from "@ai-cognitive/db";
import { randomUUID } from "node:crypto";
import { afterAll, afterEach, describe, expect, it } from "vitest";
import { DeterministicFakeProviderAdapter, ProviderExecutionRepository, ProviderGatewayError, ProviderGatewayRepository, ProviderRegistry, WorkspaceMembershipExecutionAuthorizer, createExecutionSnapshot, createProductionProviderGateway, stableHash, testCipher } from "../src/index.js";
import type { GatewayExecutionDependencies, GatewayRequest, ProviderAdapter, ResolvedRoute } from "../src/index.js";

const workspaces: string[] = []; const users: string[] = [];
const capability = { modelId: "fixture-1", families: ["TEXT_GENERATION"] as const, confidence: "VERIFIED" as const };
const baseRoute = (): ResolvedRoute => ({ source: "PLATFORM", providerKey: "fixture", protocol: "TEST", modelId: "fixture-1", adapterVersion: "test", capability, configuration: {} });
async function workspace(name: string) { const id = randomUUID(); workspaces.push(id); await prisma.workspace.create({ data: { id, name } }); return id; }
async function user(workspaceId: string, role?: "OWNER" | "EDITOR" | "VIEWER") { const id = randomUUID(); users.push(id); await prisma.user.create({ data: { id, email: `${id}@test.invalid` } }); if (role) await prisma.workspaceMember.create({ data: { workspaceId, userId: id, role } }); return id; }
function input(workspaceId: string, idempotencyKey: string, overrides: Partial<GatewayRequest> = {}): GatewayRequest { return { workspaceId, routeSlot: "BOOK_CHUNK_ANALYSIS", correlationId: idempotencyKey, idempotencyKey, inputHash: "a".repeat(64), capability: { family: "TEXT_GENERATION" }, ...overrides }; }
function registry(include = true) { const value = new ProviderRegistry(); if (include) value.register({ providerKey: "fixture", displayName: "Fixture", protocol: "TEST", adapterVersion: "test", models: [capability] }); return value; }
function build(adapter: ProviderAdapter, route: ResolvedRoute | undefined = baseRoute(), deps: Partial<GatewayExecutionDependencies> = {}) { const repository = deps.repository ?? new ProviderExecutionRepository(); return { repository, gateway: createProductionProviderGateway(registry(deps as never ? true : true), { resolveWorkspaceRoute: async () => undefined }, { resolve: async () => route }, () => adapter, { authorize: async () => undefined, assertRouteUsable: async () => undefined, validateEndpoint: async () => undefined, assertBudget: () => undefined, repository, circuit: { admit: async () => undefined, recordSuccess: async () => undefined, recordRetryableFailure: async () => undefined }, rate: { admit: async () => undefined }, concurrency: { acquire: async key => ({ key, token: "lease" }), release: async () => true }, ...deps }) }; }
async function zero(adapter: DeterministicFakeProviderAdapter, workspaceId: string, work: () => Promise<unknown>) { const calls = adapter.calls; const attempts = await prisma.providerInvocationAttempt.count({ where: { workspaceId } }); await work(); expect(adapter.calls - calls).toBe(0); expect(await prisma.providerInvocationAttempt.count({ where: { workspaceId } })).toBe(attempts); }
async function seed(workspaceId: string, key: string, status: "SUCCEEDED" | "FAILED" | "BLOCKED" | "RECONCILIATION_REQUIRED" | "RUNNING") { const repo = new ProviderExecutionRepository(); const snapshot = createExecutionSnapshot(input(workspaceId, key), baseRoute()); const fingerprint = stableHash({ routeSlot: snapshot.routeSlot, providerKey: snapshot.providerKey, protocol: snapshot.protocol, modelId: snapshot.modelId, connectionId: snapshot.connectionId, credentialVersionId: snapshot.credentialVersionId, configuration: snapshot.configuration, capability: { family: "TEXT_GENERATION" }, promptVersion: undefined, schemaVersion: undefined, pipelineVersion: undefined, inputHash: "a".repeat(64) }); const claim = await repo.claimExecution(snapshot, { idempotencyKey: key, fingerprint }); if (claim.kind !== "OWNER") throw new Error("seed owner"); if (status !== "RUNNING") await repo.completeInvocation(workspaceId, claim.invocationId, claim.claimToken, status); return { repo, snapshot, claim }; }
afterEach(async () => { for (const id of workspaces.splice(0)) { await prisma.providerUsageEvent.deleteMany({ where: { workspaceId: id } }); await prisma.providerInvocationAttempt.deleteMany({ where: { workspaceId: id } }); await prisma.providerInvocation.deleteMany({ where: { workspaceId: id } }); await prisma.providerExecutionSnapshot.deleteMany({ where: { workspaceId: id } }); await prisma.providerRouteBinding.deleteMany({ where: { workspaceId: id } }); await prisma.providerCredentialVersion.deleteMany({ where: { workspaceId: id } }); await prisma.providerConnection.deleteMany({ where: { workspaceId: id } }); await prisma.providerAuditEvent.deleteMany({ where: { workspaceId: id } }); await prisma.workspaceMember.deleteMany({ where: { workspaceId: id } }); await prisma.workspace.delete({ where: { id } }); } for (const id of users.splice(0)) await prisma.user.delete({ where: { id } }); }); afterAll(async () => prisma.$disconnect());

describe("Gateway.execute zero-call matrix", () => {
  it.each([
    ["missing principal", "AUTHORIZATION_FAILED", (ws: string, a: DeterministicFakeProviderAdapter) => build(a).gateway.execute(input(ws, "missing"))],
    ["route unavailable", "ROUTE_UNAVAILABLE", (ws: string, a: DeterministicFakeProviderAdapter) => { const repo = new ProviderExecutionRepository(); const g = createProductionProviderGateway(registry(), { resolveWorkspaceRoute: async () => undefined }, { resolve: async () => undefined }, () => a, { authorize: async () => undefined, assertRouteUsable: async () => undefined, validateEndpoint: async () => undefined, assertBudget: () => undefined, repository: repo, circuit: { admit: async () => undefined, recordSuccess: async () => undefined, recordRetryableFailure: async () => undefined }, rate: { admit: async () => undefined }, concurrency: { acquire: async key => ({ key, token: "x" }), release: async () => true } }); return g.execute(input(ws, "route"), { userId: "owner" }); }],
    ["provider missing", "MODEL_NOT_FOUND", (ws: string, a: DeterministicFakeProviderAdapter) => { const r = new ProviderRegistry(); const repo = new ProviderExecutionRepository(); const g = createProductionProviderGateway(r, { resolveWorkspaceRoute: async () => undefined }, { resolve: async () => ({ ...baseRoute(), providerKey: "missing" }) }, () => a, { authorize: async () => undefined, assertRouteUsable: async () => undefined, validateEndpoint: async () => undefined, assertBudget: () => undefined, repository: repo, circuit: { admit: async () => undefined, recordSuccess: async () => undefined, recordRetryableFailure: async () => undefined }, rate: { admit: async () => undefined }, concurrency: { acquire: async key => ({ key, token: "x" }), release: async () => true } }); return g.execute(input(ws, "provider"), { userId: "owner" }); }],
    ["model missing", "MODEL_NOT_FOUND", (ws: string, a: DeterministicFakeProviderAdapter) => build(a, { ...baseRoute(), modelId: "missing" }).gateway.execute(input(ws, "model"), { userId: "owner" })],
    ["capability mismatch", "CAPABILITY_MISMATCH", (ws: string, a: DeterministicFakeProviderAdapter) => build(a).gateway.execute(input(ws, "capability", { capability: { family: "EMBEDDING" } }), { userId: "owner" })],
    ["adapter missing", "ROUTE_UNAVAILABLE", (ws: string, a: DeterministicFakeProviderAdapter) => { void a; const repo = new ProviderExecutionRepository(); const g = createProductionProviderGateway(registry(), { resolveWorkspaceRoute: async () => undefined }, { resolve: async () => baseRoute() }, () => undefined, { authorize: async () => undefined, assertRouteUsable: async () => undefined, validateEndpoint: async () => undefined, assertBudget: () => undefined, repository: repo, circuit: { admit: async () => undefined, recordSuccess: async () => undefined, recordRetryableFailure: async () => undefined }, rate: { admit: async () => undefined }, concurrency: { acquire: async key => ({ key, token: "x" }), release: async () => true } }); return g.execute(input(ws, "adapter"), { userId: "owner" }); }],
    ["unsafe endpoint", "NETWORK_POLICY_REJECTED", (ws: string, a: DeterministicFakeProviderAdapter) => build(a, { ...baseRoute(), endpoint: "https://unsafe.test" }, { validateEndpoint: async () => { throw new ProviderGatewayError("NETWORK_POLICY_REJECTED"); } }).gateway.execute(input(ws, "unsafe"), { userId: "owner" })],
    ["budget exceeded", "BUDGET_EXCEEDED", (ws: string, a: DeterministicFakeProviderAdapter) => build(a).gateway.execute(input(ws, "budget", { budget: { maxInputTokens: 1 }, estimates: { inputTokens: 2 } }), { userId: "owner" })],
    ["invalid input hash", "INVALID_PROVIDER_RESPONSE", (ws: string, a: DeterministicFakeProviderAdapter) => build(a).gateway.execute(input(ws, "hash", { inputHash: "bad" }), { userId: "owner" })],
    ["pre-cancelled", "CANCELLED", (ws: string, a: DeterministicFakeProviderAdapter) => { const controller = new AbortController(); controller.abort(); return build(a).gateway.execute(input(ws, "cancel", { signal: controller.signal }), { userId: "owner" }); }],
    ["circuit open", "CIRCUIT_OPEN", (ws: string, a: DeterministicFakeProviderAdapter) => build(a, baseRoute(), { circuit: { admit: async () => { throw new ProviderGatewayError("CIRCUIT_OPEN"); }, recordSuccess: async () => undefined, recordRetryableFailure: async () => undefined } }).gateway.execute(input(ws, "circuit"), { userId: "owner" })],
    ["rate rejected", "RATE_LIMITED", (ws: string, a: DeterministicFakeProviderAdapter) => build(a, baseRoute(), { rate: { admit: async () => { throw new ProviderGatewayError("RATE_LIMITED"); } } }).gateway.execute(input(ws, "rate"), { userId: "owner" })],
    ["concurrency rejected", "RATE_LIMITED", (ws: string, a: DeterministicFakeProviderAdapter) => build(a, baseRoute(), { concurrency: { acquire: async () => { throw new ProviderGatewayError("RATE_LIMITED"); }, release: async () => true } }).gateway.execute(input(ws, "concurrency"), { userId: "owner" })],
  ])("%s has zero remote and attempt delta", async (_name, code, invoke) => { const ws = await workspace(`zero-${_name}`); const adapter = new DeterministicFakeProviderAdapter(); await zero(adapter, ws, async () => { await expect(invoke(ws, adapter)).rejects.toMatchObject({ code }); }); });

  it("VIEWER, non-member, and cross-workspace use real PostgreSQL membership authorization", async () => { const ws = await workspace("zero-auth"); const other = await workspace("zero-other"); const owner = await user(ws, "OWNER"); const viewer = await user(ws, "VIEWER"); const outsider = await user(other, "OWNER"); const adapter = new DeterministicFakeProviderAdapter(); const authorizer = new WorkspaceMembershipExecutionAuthorizer(prisma); const { gateway } = build(adapter, baseRoute(), { authorize: (principal, request) => authorizer.authorizeExecution(principal, request.workspaceId) }); for (const [name, value, principal] of [["VIEWER", input(ws, "viewer"), viewer], ["non-member", input(ws, "outsider"), outsider], ["cross-workspace", input(other, "cross"), owner]] as const) { void name; await zero(adapter, value.workspaceId, async () => { await expect(gateway.execute(value, { userId: principal })).rejects.toMatchObject({ code: "AUTHORIZATION_FAILED" }); }); } });

  it.each([["disabled connection", "disabled", "CONNECTION_DISABLED"], ["revoked connection", "revoked-connection", "CONNECTION_DISABLED"], ["missing credential", "missing", "AUTHENTICATION_FAILED"], ["revoked credential", "revoked-credential", "CREDENTIAL_REVOKED"]] as const)("%s uses persisted connection and credential state", async (_name, mode, code) => { const ws = await workspace(`zero-${mode}`); const owner = await user(ws, "OWNER"); const cipher = testCipher(); const store = new ProviderGatewayRepository(prisma, cipher); const connection = await store.createConnection({ workspaceId: ws, userId: owner }, { providerKey: "fixture", protocol: "TEST", displayName: mode }); let credential: { id: string } | undefined; if (mode !== "missing") credential = await store.rotateCredential({ workspaceId: ws, userId: owner }, connection.id, "test-secret-not-logged"); await store.setRoute({ workspaceId: ws, userId: owner }, { routeSlot: "BOOK_CHUNK_ANALYSIS", connectionId: connection.id, modelId: "fixture-1" }); if (mode === "disabled") await store.setConnectionEnabled({ workspaceId: ws, userId: owner }, connection.id, false); if (mode === "revoked-connection") await prisma.providerConnection.update({ where: { id_workspaceId: { id: connection.id, workspaceId: ws } }, data: { status: "REVOKED" } }); if (mode === "revoked-credential") await store.revokeCredential({ workspaceId: ws, userId: owner }, credential!.id); const adapter = new DeterministicFakeProviderAdapter(); const repository = new ProviderExecutionRepository(prisma, cipher); const pinned = mode === "revoked-credential" ? { ...baseRoute(), source: "PLATFORM" as const, connectionId: connection.id, credentialVersionId: credential!.id } : undefined; const gateway = createProductionProviderGateway(registry(), { resolveWorkspaceRoute: value => mode === "revoked-credential" ? Promise.resolve(undefined) : store.resolveWorkspaceRoute(value) }, { resolve: async () => pinned }, () => adapter, { authorize: async () => undefined, assertRouteUsable: async () => undefined, validateEndpoint: async () => undefined, assertBudget: () => undefined, repository, circuit: { admit: async () => undefined, recordSuccess: async () => undefined, recordRetryableFailure: async () => undefined }, rate: { admit: async () => undefined }, concurrency: { acquire: async key => ({ key, token: "x" }), release: async () => true } }); await zero(adapter, ws, async () => { await expect(gateway.execute(input(ws, mode), { userId: owner })).rejects.toMatchObject({ code }); }); });

  it("durable idempotency states never create a remote call or attempt", async () => { const ws = await workspace("zero-durable"); const adapter = new DeterministicFakeProviderAdapter(); for (const [key, status, expected] of [["ALREADY_PROCESSED", "SUCCEEDED", "ALREADY_PROCESSED"], ["TERMINAL_FAILED", "FAILED", "TERMINAL_FAILED"], ["BLOCKED_EXISTING", "BLOCKED", "BLOCKED_EXISTING"], ["RECONCILIATION_REQUIRED", "RECONCILIATION_REQUIRED", "RECONCILIATION_REQUIRED"]] as const) { const { repo } = await seed(ws, key, status); const { gateway } = build(adapter, baseRoute(), { repository: repo }); await zero(adapter, ws, async () => { await expect(gateway.execute(input(ws, key), { userId: "owner" })).resolves.toMatchObject({ status: expected }); }); } const { repo } = await seed(ws, "IN_PROGRESS", "RUNNING"); const { gateway } = build(adapter, baseRoute(), { repository: repo }); await zero(adapter, ws, async () => { await expect(gateway.execute(input(ws, "IN_PROGRESS"), { userId: "owner" })).resolves.toMatchObject({ status: "IN_PROGRESS" }); }); await zero(adapter, ws, async () => { await expect(gateway.execute(input(ws, "IN_PROGRESS", { inputHash: "b".repeat(64) }), { userId: "owner" })).rejects.toMatchObject({ code: "IDEMPOTENCY_CONFLICT" }); }); });
});
