import { describe, expect, it } from "vitest";
import { CohereEmbeddingAdapter, DeterministicProviderHttpTransport, GeminiEmbeddingAdapter, OpenAIEmbeddingAdapter, ProviderGatewayError, QwenEmbeddingAdapter, VoyageEmbeddingAdapter, canonicalEmbeddingInputHash, createProviderAdapterResolver, validateEmbeddingInput } from "../src/index.js";
import type { ProtocolFamily, ProviderAdapterResolverInput } from "../src/index.js";

const capability = { modelId: "fixture-embedding", families: ["EMBEDDING"] as const, confidence: "VERIFIED" as const, embeddingDimensions: 3, configurableEmbeddingDimensions: true, embeddingDimensionOptions: [3], maxEmbeddingInputs: 4, embeddingPurposes: ["DOCUMENT", "QUERY", "SEMANTIC_SIMILARITY", "CLASSIFICATION", "CLUSTERING"] as const };
function fixture(providerKey: string, protocol: ProtocolFamily, response: unknown, configuration: Record<string, unknown> = {}) { const transport = new DeterministicProviderHttpTransport(() => ({ status: 200, headers: { "x-request-id": "request-1" }, body: JSON.stringify(response) })); const snapshot = { id: "s", workspaceId: "w", routeSlot: "EMBEDDING" as const, correlationId: "c", source: "PLATFORM" as const, providerKey, protocol, modelId: capability.modelId, adapterVersion: "phase8c", capability, configuration: { embeddingDimensions: 3, ...configuration }, configurationHash: "h", createdAt: new Date() }; const request = { workspaceId: "w", routeSlot: "EMBEDDING" as const, correlationId: "c", idempotencyKey: "i", inputHash: "a".repeat(64), capability: { family: "EMBEDDING" as const }, requestFingerprint: "f", embedding: { texts: ["one", "two"], purpose: "DOCUMENT" as const } }; return { transport, input: { snapshot, request, signal: new AbortController().signal, credential: "credential" } }; }
describe("Phase 8C embedding contract and real adapter fixtures", () => {
  it("hashes ordered runtime text and purpose without retaining it", () => { expect(canonicalEmbeddingInputHash({ texts: ["a", "b"], purpose: "DOCUMENT" })).toBe(canonicalEmbeddingInputHash({ texts: ["a", "b"], purpose: "DOCUMENT" })); expect(canonicalEmbeddingInputHash({ texts: ["a", "b"], purpose: "DOCUMENT" })).not.toBe(canonicalEmbeddingInputHash({ texts: ["b", "a"], purpose: "DOCUMENT" })); expect(canonicalEmbeddingInputHash({ texts: ["a", "b"], purpose: "DOCUMENT" })).not.toBe(canonicalEmbeddingInputHash({ texts: ["a", "b"], purpose: "QUERY" })); });
  it("rejects invalid embedding runtime input before adapter execution", () => { expect(() => validateEmbeddingInput({ texts: ["  "], purpose: "DOCUMENT" }, capability)).toThrow(ProviderGatewayError); expect(() => validateEmbeddingInput({ texts: [], purpose: "DOCUMENT" }, capability)).toThrow(ProviderGatewayError); });
  it.each([
    ["openai", "OPENAI_EMBEDDINGS", OpenAIEmbeddingAdapter, { data: [{ index: 1, embedding: [0, 1, 0] }, { index: 0, embedding: [1, 0, 0] }], model: "text-embedding-3-small", usage: { prompt_tokens: 3 } }],
    ["gemini", "GEMINI_EMBEDDINGS", GeminiEmbeddingAdapter, { embeddings: [{ values: [1, 0, 0] }, { values: [0, 1, 0] }], usageMetadata: { promptTokenCount: 3 } }],
    ["qwen", "OPENAI_COMPATIBLE", QwenEmbeddingAdapter, { data: [{ index: 0, embedding: [1, 0, 0] }, { index: 1, embedding: [0, 1, 0] }], usage: { prompt_tokens: 3 } }],
    ["cohere", "COHERE_EMBEDDINGS_V2", CohereEmbeddingAdapter, { embeddings: { float: [[1, 0, 0], [0, 1, 0]] }, meta: { billed_units: { input_tokens: 3 } } }],
    ["voyage", "VOYAGE_EMBEDDINGS", VoyageEmbeddingAdapter, { data: [{ index: 0, embedding: [1, 0, 0] }, { index: 1, embedding: [0, 1, 0] }], usage: { total_tokens: 3 } }],
  ] as const)("executes %s embeddings with one bounded HTTP request", async (provider, protocol, Adapter, response) => { const value = fixture(provider, protocol, response, provider === "qwen" ? { qwenRegion: "BEIJING", qwenWorkspaceId: "workspace1" } : {}); const result = await new Adapter(value.transport).execute(value.input); expect(result.response).toMatchObject({ dimensions: 3 }); expect(value.transport.calls).toHaveLength(1); expect(JSON.stringify(value.transport.calls[0]?.headers)).toContain("credential"); });
  it.each([["DOCUMENT", "RETRIEVAL_DOCUMENT"], ["QUERY", "RETRIEVAL_QUERY"], ["SEMANTIC_SIMILARITY", "SEMANTIC_SIMILARITY"], ["CLASSIFICATION", "CLASSIFICATION"], ["CLUSTERING", "CLUSTERING"]] as const)("uses Gemini EmbedContentConfig taskType for %s", async (purpose, taskType) => { const value = fixture("gemini", "GEMINI_EMBEDDINGS", { embeddings: [{ values: [1, 0, 0] }, { values: [0, 1, 0] }] }); const input = { ...value.input, request: { ...value.input.request, embedding: { texts: ["one", "two"], purpose } } }; await new GeminiEmbeddingAdapter(value.transport).execute(input); const call = value.transport.calls[0]!; const body = JSON.parse(call.body!) as { requests: Array<Record<string, unknown>> }; expect(call.url).toBe("https://generativelanguage.googleapis.com/v1beta/models/fixture-embedding:batchEmbedContents"); expect(body.requests).toHaveLength(2); for (const [index, request] of body.requests.entries()) { expect(request.model).toBe("models/fixture-embedding"); expect(request.content).toEqual({ parts: [{ text: ["one", "two"][index] }] }); expect(request.embedContentConfig).toEqual({ taskType, autoTruncate: false, outputDimensionality: 3 }); expect(request.taskType).toBeUndefined(); expect(request.autoTruncate).toBeUndefined(); expect(request.outputDimensionality).toBeUndefined(); } });
  it("omits Gemini output dimensionality when dimensions are fixed", async () => { const value = fixture("gemini", "GEMINI_EMBEDDINGS", { embeddings: [{ values: [1, 0, 0] }, { values: [0, 1, 0] }] }); const input = { ...value.input, snapshot: { ...value.input.snapshot, capability: { ...value.input.snapshot.capability, configurableEmbeddingDimensions: false } } }; await new GeminiEmbeddingAdapter(value.transport).execute(input); const body = JSON.parse(value.transport.calls[0]!.body!) as { requests: Array<{ embedContentConfig: Record<string, unknown> }> }; expect(body.requests[0]!.embedContentConfig).toEqual({ taskType: "RETRIEVAL_DOCUMENT", autoTruncate: false }); });
  it("normalizes Gemini prompt tokens only as embedding input tokens", async () => { const withUsage = fixture("gemini", "GEMINI_EMBEDDINGS", { embeddings: [{ values: [1, 0, 0] }, { values: [0, 1, 0] }], usageMetadata: { promptTokenCount: 17 } }); const result = await new GeminiEmbeddingAdapter(withUsage.transport).execute(withUsage.input); expect(result.usage).toEqual({ embeddingInputTokens: 17 }); expect("inputTokens" in (result.usage ?? {})).toBe(false); const withoutUsage = fixture("gemini", "GEMINI_EMBEDDINGS", { embeddings: [{ values: [1, 0, 0] }, { values: [0, 1, 0] }] }); const absent = await new GeminiEmbeddingAdapter(withoutUsage.transport).execute(withoutUsage.input); expect(absent.usage).toBeUndefined(); });
  it("keeps provider and capability selection distinct", () => { const transport = new DeterministicProviderHttpTransport(() => ({ status: 500, headers: {}, body: "{}" })); const resolver = createProviderAdapterResolver(transport); const text: ProviderAdapterResolverInput = { providerKey: "openai", family: "TEXT_GENERATION", protocol: "OPENAI_RESPONSES", modelId: "gpt" }; const embedding: ProviderAdapterResolverInput = { ...text, family: "EMBEDDING", protocol: "OPENAI_EMBEDDINGS", modelId: "text-embedding-3-small" }; expect(resolver(text)?.constructor.name).toBe("OpenAIResponsesAdapter"); expect(resolver(embedding)?.constructor.name).toBe("OpenAIEmbeddingAdapter"); });
  it("rejects malformed, zero, duplicate-index, and unsupported-purpose output safely", async () => { const duplicate = fixture("openai", "OPENAI_EMBEDDINGS", { data: [{ index: 0, embedding: [1, 0, 0] }, { index: 0, embedding: [0, 1, 0] }] }); await expect(new OpenAIEmbeddingAdapter(duplicate.transport).execute(duplicate.input)).rejects.toMatchObject({ code: "INVALID_PROVIDER_RESPONSE" }); const zero = fixture("voyage", "VOYAGE_EMBEDDINGS", { data: [{ index: 0, embedding: [0, 0, 0] }, { index: 1, embedding: [0, 1, 0] }] }); await expect(new VoyageEmbeddingAdapter(zero.transport).execute(zero.input)).rejects.toMatchObject({ code: "INVALID_PROVIDER_RESPONSE" }); const cohere = fixture("cohere", "COHERE_EMBEDDINGS_V2", { embeddings: { float: [] } }); const unsupported = { ...cohere.input, request: { ...cohere.input.request, embedding: { texts: ["one", "two"], purpose: "SEMANTIC_SIMILARITY" as const } } }; await expect(new CohereEmbeddingAdapter(cohere.transport).execute(unsupported)).rejects.toMatchObject({ code: "CAPABILITY_MISMATCH" }); expect(cohere.transport.calls).toHaveLength(0); });
});
