import { describe, expect, it } from "vitest";
import { AnthropicCompatibleAdapter, canonicalTextInputHash, DeterministicProviderHttpTransport, GeminiNativeAdapter, OpenAICompatibleAdapter, OpenAIResponsesAdapter, ProviderGatewayError, validateTextGenerationInput } from "../src/index.js";
import type { AdapterRequest, ExecutionSnapshot, TextGenerationInput } from "../src/index.js";

const text: TextGenerationInput = { system: "system", messages: [{ role: "user", content: "hello" }], generation: { temperature: 0.2, maxOutputTokens: 100 }, structuredOutput: { mode: "STRICT_JSON_SCHEMA", schemaName: "answer", schema: { type: "object", properties: { answer: { type: "string" } }, required: ["answer"] } } };
function input(providerKey: ExecutionSnapshot["providerKey"], protocol: ExecutionSnapshot["protocol"], endpoint?: string) { const snapshot = { id: "s", workspaceId: "w", routeSlot: "BOOK_CHUNK_ANALYSIS", correlationId: "c", source: "PLATFORM" as const, providerKey, protocol, modelId: "model", adapterVersion: "1", capability: { modelId: "model", families: ["TEXT_GENERATION"] as const, confidence: "VERIFIED" as const, structuredOutput: "STRICT_JSON_SCHEMA" as const }, configuration: {}, configurationHash: "hash", createdAt: new Date(), endpoint } as ExecutionSnapshot; return { snapshot, request: { workspaceId: "w", routeSlot: "BOOK_CHUNK_ANALYSIS", correlationId: "c", idempotencyKey: "key", inputHash: "a".repeat(64), capability: { family: "TEXT_GENERATION", structuredOutput: "STRICT_JSON_SCHEMA" }, text, requestFingerprint: "fingerprint" } as AdapterRequest, signal: new AbortController().signal, credential: "secret-credential-123" }; }
function transport(body: unknown, status = 200) { return new DeterministicProviderHttpTransport(() => ({ status, headers: { "x-request-id": "req-1", "retry-after": "2" }, body: JSON.stringify(body) })); }

describe("Phase 8B real text provider adapters", () => {
  it("hashes canonical runtime input without retaining runtime content", () => { expect(canonicalTextInputHash(text)).toBe(canonicalTextInputHash({ ...text, structuredOutput: { ...text.structuredOutput!, schema: { required: ["answer"], properties: { answer: { type: "string" } }, type: "object" } } })); expect(canonicalTextInputHash(text)).not.toBe(canonicalTextInputHash({ ...text, system: "changed" })); expect(canonicalTextInputHash(text)).not.toBe(canonicalTextInputHash({ ...text, messages: [{ role: "user", content: "changed" }] })); expect(canonicalTextInputHash(text)).not.toBe(canonicalTextInputHash({ ...text, generation: { ...text.generation, temperature: 1 } })); });
  it("rejects invalid inputs before transport", () => { expect(() => validateTextGenerationInput({ ...text, messages: [] })).toThrow(ProviderGatewayError); expect(() => validateTextGenerationInput({ ...text, generation: { temperature: 9 } })).toThrow(ProviderGatewayError); expect(() => validateTextGenerationInput({ ...text, structuredOutput: { mode: "STRICT_JSON_SCHEMA", schemaName: "bad name", schema: {} } })).toThrow(ProviderGatewayError); });
  it("maps OpenAI Responses text, strict schema, usage, request id and bearer auth", async () => { const wire = transport({ model: "gpt", status: "completed", output: [{ type: "message", content: [{ type: "output_text", text: '{"answer":"ok"}' }] }], usage: { input_tokens: 3, output_tokens: 2, input_tokens_details: { cached_tokens: 1 } } }); const result = await new OpenAIResponsesAdapter(wire).execute(input("openai", "OPENAI_RESPONSES")); expect(result.response).toMatchObject({ type: "STRUCTURED", structured: { answer: "ok" } }); expect(result.usage).toMatchObject({ cachedInputTokens: 1 }); expect(wire.calls[0]!.headers.authorization).toBe("Bearer secret-credential-123"); expect(wire.calls).toHaveLength(1); });
  it("maps OpenAI-compatible profiles without exposing reasoning fields", async () => { const wire = transport({ model: "deepseek-x", choices: [{ finish_reason: "stop", message: { content: '{"answer":"ok"}', reasoning_content: "never expose" } }], usage: { prompt_tokens: 4, completion_tokens: 3 } }); const result = await new OpenAICompatibleAdapter(wire).execute(input("deepseek", "OPENAI_COMPATIBLE")); expect(result.response).toMatchObject({ structured: { answer: "ok" } }); expect(JSON.stringify(result)).not.toContain("reasoning"); });
  it("maps Anthropic final text while dropping thinking blocks", async () => { const wire = transport({ model: "claude", stop_reason: "end_turn", content: [{ type: "thinking", thinking: "secret reasoning" }, { type: "text", text: '{"answer":"ok"}' }], usage: { input_tokens: 2, output_tokens: 1 } }); const result = await new AnthropicCompatibleAdapter(wire).execute(input("anthropic", "ANTHROPIC_COMPATIBLE")); expect(result.response).toMatchObject({ structured: { answer: "ok" } }); expect(JSON.stringify(result)).not.toContain("thinking"); expect(wire.calls[0]!.headers["x-api-key"]).toBe("secret-credential-123"); });
  it("maps Gemini text, structured JSON, usage and API-key header", async () => { const wire = transport({ responseId: "gem-1", candidates: [{ finishReason: "STOP", content: { parts: [{ text: '{"answer":"ok"}' }] } }], usageMetadata: { promptTokenCount: 5, candidatesTokenCount: 2, cachedContentTokenCount: 1 } }); const result = await new GeminiNativeAdapter(wire).execute(input("gemini", "GEMINI_NATIVE")); expect(result.response).toMatchObject({ structured: { answer: "ok" } }); expect(result.usage).toMatchObject({ inputTokens: 5 }); expect(wire.calls[0]!.headers["x-goog-api-key"]).toBe("secret-credential-123"); });
  it("locally rejects malformed structured provider output and redirects before retry", async () => { const wire = transport({ choices: [{ message: { content: "not json" } }] }); await expect(new OpenAICompatibleAdapter(wire).execute(input("qwen", "OPENAI_COMPATIBLE"))).rejects.toMatchObject({ code: "INVALID_PROVIDER_RESPONSE" }); const redirect = transport({}, 302); await expect(new OpenAICompatibleAdapter(redirect).execute(input("minimax", "OPENAI_COMPATIBLE"))).rejects.toMatchObject({ code: "NETWORK_POLICY_REJECTED" }); expect(redirect.calls).toHaveLength(1); });
  it("does not allow unknown endpoint or a pre-cancelled request to reach HTTP", async () => { const wire = transport({}); await expect(new OpenAICompatibleAdapter(wire).execute(input("deepseek", "OPENAI_COMPATIBLE", "https://evil.example/v1"))).rejects.toMatchObject({ code: "NETWORK_POLICY_REJECTED" }); const aborted = input("deepseek", "OPENAI_COMPATIBLE"); const controller = new AbortController(); controller.abort(); await expect(new OpenAICompatibleAdapter(wire).execute({ ...aborted, signal: controller.signal })).rejects.toMatchObject({ code: "CANCELLED" }); expect(wire.calls).toHaveLength(0); });
});
