import { prisma } from "@ai-cognitive/db";
import { randomUUID } from "node:crypto";
import { afterAll, afterEach, describe, expect, it } from "vitest";
import { CohereEmbeddingAdapter, DeterministicProviderHttpTransport, GeminiEmbeddingAdapter, OpenAIEmbeddingAdapter, ProviderExecutionRepository, ProviderGatewayError, ProviderGatewayRepository, ProviderRegistry, QwenEmbeddingAdapter, VoyageEmbeddingAdapter, WorkspaceMembershipExecutionAuthorizer, createProductionProviderGateway, testCipher, type GatewayRequest, type ProviderAdapter, type ProviderHttpRequest, type ProviderHttpResponse } from "../src/index.js";

const workspaces: string[] = []; const users: string[] = []; const secret = "phase8c-super-secret-credential";
const protocols = { openai: "OPENAI_EMBEDDINGS", gemini: "GEMINI_EMBEDDINGS", qwen: "OPENAI_COMPATIBLE", cohere: "COHERE_EMBEDDINGS_V2", voyage: "VOYAGE_EMBEDDINGS" } as const;
type Provider = keyof typeof protocols;
const capabilities = {
  openai: { modelId: "text-embedding-3-small", families: ["EMBEDDING"] as const, confidence: "VERIFIED" as const, embeddingDimensions: 3, configurableEmbeddingDimensions: true, embeddingDimensionOptions: [3, 4], maxEmbeddingInputs: 2, embeddingPurposes: ["DOCUMENT", "QUERY", "SEMANTIC_SIMILARITY", "CLASSIFICATION", "CLUSTERING"] as const },
  gemini: { modelId: "gemini-embedding-001", families: ["EMBEDDING"] as const, confidence: "VERIFIED" as const, embeddingDimensions: 3, configurableEmbeddingDimensions: true, embeddingDimensionOptions: [3, 4], maxEmbeddingInputs: 2, embeddingPurposes: ["DOCUMENT", "QUERY", "SEMANTIC_SIMILARITY", "CLASSIFICATION", "CLUSTERING"] as const },
  qwen: { modelId: "text-embedding-v4", families: ["EMBEDDING"] as const, confidence: "VERIFIED" as const, embeddingDimensions: 3, configurableEmbeddingDimensions: true, embeddingDimensionOptions: [3, 4], maxEmbeddingInputs: 2, embeddingPurposes: ["DOCUMENT", "QUERY", "SEMANTIC_SIMILARITY", "CLASSIFICATION", "CLUSTERING"] as const },
  cohere: { modelId: "embed-v4.0", families: ["EMBEDDING"] as const, confidence: "VERIFIED" as const, embeddingDimensions: 3, configurableEmbeddingDimensions: false, maxEmbeddingInputs: 2, embeddingPurposes: ["DOCUMENT", "QUERY", "CLASSIFICATION", "CLUSTERING"] as const },
  voyage: { modelId: "voyage-3.5-lite", families: ["EMBEDDING"] as const, confidence: "VERIFIED" as const, embeddingDimensions: 3, configurableEmbeddingDimensions: false, maxEmbeddingInputs: 2, embeddingPurposes: ["DOCUMENT", "QUERY", "SEMANTIC_SIMILARITY"] as const },
};
const vectors = [[1, 0, 0], [0, 1, 0]];
function body(provider: Provider, output: number[][] = vectors, usage = 7) { if (provider === "gemini") return { embeddings: output.map(values => ({ values })), usageMetadata: { promptTokenCount: usage } }; if (provider === "cohere") return { embeddings: { float: output }, meta: { billed_units: { input_tokens: usage } } }; if (provider === "voyage") return { data: output.map((embedding, index) => ({ index, embedding })), usage: { total_tokens: usage } }; return { data: output.map((embedding, index) => ({ index, embedding })), usage: { prompt_tokens: usage } }; }
function adapter(provider: Provider, transport: DeterministicProviderHttpTransport): ProviderAdapter { return provider === "openai" ? new OpenAIEmbeddingAdapter(transport) : provider === "gemini" ? new GeminiEmbeddingAdapter(transport) : provider === "qwen" ? new QwenEmbeddingAdapter(transport) : provider === "cohere" ? new CohereEmbeddingAdapter(transport) : new VoyageEmbeddingAdapter(transport); }
function registry(maxEmbeddingInputs = 2) { const value = new ProviderRegistry(); for (const provider of Object.keys(protocols) as Provider[]) value.register({ providerKey: provider, displayName: provider, protocol: protocols[provider], adapterVersion: "phase8c", models: [{ ...capabilities[provider], maxEmbeddingInputs }] }); return value; }
function request(workspaceId: string, key: string, embedding: GatewayRequest["embedding"] = { texts: ["one", "two"], purpose: "DOCUMENT" }) { return { workspaceId, routeSlot: "EMBEDDING" as const, correlationId: key, idempotencyKey: key, inputHash: "a".repeat(64), capability: { family: "EMBEDDING" as const }, embedding }; }
async function fixture(provider: Provider, responder: (request: ProviderHttpRequest) => ProviderHttpResponse | Promise<ProviderHttpResponse> = () => ({ status: 200, headers: { "x-request-id": "phase8c-request" }, body: JSON.stringify(body(provider)) }), options: { maxAttempts?: number; configuration?: Record<string, unknown>; platform?: boolean; platformCredential?: string; platformProvider?: Provider; alternateProvider?: Provider; alternateResponder?: (request: ProviderHttpRequest) => ProviderHttpResponse | Promise<ProviderHttpResponse>; control?: "CIRCUIT_OPEN" | "RATE_LIMITED" | "CONCURRENCY"; maxEmbeddingInputs?: number; beforeRetry?: (context: { workspaceId: string; userId: string; store: ProviderGatewayRepository; connection: { id: string }; credential: { id: string } }) => Promise<void> } = {}) {
  const workspaceId = randomUUID(), userId = randomUUID(); workspaces.push(workspaceId); users.push(userId); await prisma.workspace.create({ data: { id: workspaceId, name: workspaceId } }); await prisma.user.create({ data: { id: userId, email: `${userId}@test.invalid` } }); await prisma.workspaceMember.create({ data: { workspaceId, userId, role: "OWNER" } });
  const cipher = testCipher(), store = new ProviderGatewayRepository(prisma, cipher), transport = new DeterministicProviderHttpTransport(responder), alternateTransport = options.alternateProvider ? new DeterministicProviderHttpTransport(options.alternateResponder ?? (() => ({ status: 200, headers: {}, body: JSON.stringify(body(options.alternateProvider!)) }))) : undefined; let connection: { id: string } | undefined; let credential: { id: string } | undefined;
  if (!options.platform) { connection = await store.createConnection({ workspaceId, userId }, { providerKey: provider, protocol: protocols[provider], displayName: provider }); credential = await store.rotateCredential({ workspaceId, userId }, connection.id, secret); await store.setRoute({ workspaceId, userId }, { routeSlot: "EMBEDDING", connectionId: connection.id, modelId: capabilities[provider].modelId, configuration: provider === "qwen" ? { qwenRegion: "BEIJING", qwenWorkspaceId: "phase8cworkspace", ...options.configuration } : { ...options.configuration } }); }
  let platformCalls = 0; const platformProvider = options.platformProvider ?? provider; const gateway = createProductionProviderGateway(registry(options.maxEmbeddingInputs), { resolveWorkspaceRoute: value => store.resolveWorkspaceRoute(value) }, { resolve: async () => options.platform || options.platformProvider ? ({ source: "PLATFORM" as const, providerKey: platformProvider, protocol: protocols[platformProvider], modelId: capabilities[platformProvider].modelId, adapterVersion: "phase8c", capability: { ...capabilities[platformProvider], maxEmbeddingInputs: options.maxEmbeddingInputs ?? 2 }, configuration: options.configuration ?? {} }) : undefined }, input => input.providerKey === provider ? adapter(provider, transport) : input.providerKey === options.alternateProvider && alternateTransport ? adapter(options.alternateProvider, alternateTransport) : undefined, { authorize: (principal, value) => new WorkspaceMembershipExecutionAuthorizer(prisma).authorizeExecution(principal, value.workspaceId), assertRouteUsable: async () => undefined, validateEndpoint: async () => undefined, assertBudget: () => undefined, repository: new ProviderExecutionRepository(prisma, cipher), platformCredentials: { resolve: async () => { platformCalls++; return options.platformCredential ?? secret; } }, circuit: { admit: async () => { if (options.control === "CIRCUIT_OPEN") throw new ProviderGatewayError("CIRCUIT_OPEN"); }, recordSuccess: async () => undefined, recordRetryableFailure: async () => undefined }, rate: { admit: async () => { if (options.control === "RATE_LIMITED") throw new ProviderGatewayError("RATE_LIMITED"); } }, concurrency: { acquire: async key => { if (options.control === "CONCURRENCY") throw new ProviderGatewayError("RATE_LIMITED"); return { key, token: "lease" }; }, release: async () => true }, maxAttempts: options.maxAttempts ?? 1, sleep: async () => { if (options.beforeRetry && connection && credential) await options.beforeRetry({ workspaceId, userId, store, connection, credential }); }, random: () => 0 });
  return { workspaceId, userId, store, connection, credential, transport, alternateTransport, gateway, platformCalls: () => platformCalls };
}
async function durable(workspaceId: string) { const [snapshots, invocations, attempts, usage, audit] = await Promise.all([prisma.providerExecutionSnapshot.findMany({ where: { workspaceId } }), prisma.providerInvocation.findMany({ where: { workspaceId } }), prisma.providerInvocationAttempt.findMany({ where: { workspaceId } }), prisma.providerUsageEvent.findMany({ where: { workspaceId } }), prisma.providerAuditEvent.findMany({ where: { workspaceId } })]); return JSON.stringify({ snapshots, invocations, attempts, usage, audit }); }
afterEach(async () => { for (const workspaceId of workspaces.splice(0)) { await prisma.providerUsageEvent.deleteMany({ where: { workspaceId } }); await prisma.providerInvocationAttempt.deleteMany({ where: { workspaceId } }); await prisma.providerInvocation.deleteMany({ where: { workspaceId } }); await prisma.providerExecutionSnapshot.deleteMany({ where: { workspaceId } }); await prisma.providerRouteBinding.deleteMany({ where: { workspaceId } }); await prisma.providerCredentialVersion.deleteMany({ where: { workspaceId } }); await prisma.providerConnection.deleteMany({ where: { workspaceId } }); await prisma.providerAuditEvent.deleteMany({ where: { workspaceId } }); await prisma.workspaceMember.deleteMany({ where: { workspaceId } }); await prisma.workspace.delete({ where: { id: workspaceId } }); } for (const userId of users.splice(0)) await prisma.user.delete({ where: { id: userId } }); }); afterAll(async () => prisma.$disconnect());

describe("Phase 8C production embedding Gateway acceptance", () => {
  it.each(["openai", "gemini", "qwen", "cohere", "voyage"] as const)("executes %s through the real Gateway, adapter, PostgreSQL, and credential vault", async provider => { const value = await fixture(provider); const result = await value.gateway.execute(request(value.workspaceId, `success-${provider}`), { userId: value.userId }); expect(result).toMatchObject({ status: "SUCCEEDED", response: { dimensions: 3 }, usage: { embeddingInputTokens: 7 } }); expect(value.transport.calls).toHaveLength(1); expect(value.transport.calls[0]?.headers.authorization ?? value.transport.calls[0]?.headers["x-goog-api-key"]).toContain(secret); const snapshot = await prisma.providerExecutionSnapshot.findFirstOrThrow({ where: { workspaceId: value.workspaceId } }); expect(snapshot).toMatchObject({ providerKey: provider, protocol: protocols[provider], modelId: capabilities[provider].modelId }); expect(await prisma.providerUsageEvent.count({ where: { workspaceId: value.workspaceId, embeddingInputTokens: 7 } })).toBe(1); });
  it("enforces real embedding idempotency, canonical input conflicts, and dimension provenance", async () => { const value = await fixture("openai"); const base = request(value.workspaceId, "same"); await expect(value.gateway.execute(base, { userId: value.userId })).resolves.toMatchObject({ status: "SUCCEEDED" }); await expect(value.gateway.execute(base, { userId: value.userId })).resolves.toMatchObject({ status: "ALREADY_PROCESSED" }); for (const embedding of [{ texts: ["changed", "two"], purpose: "DOCUMENT" as const }, { texts: ["two", "one"], purpose: "DOCUMENT" as const }, { texts: ["one", "two"], purpose: "QUERY" as const }]) await expect(value.gateway.execute(request(value.workspaceId, "same", embedding), { userId: value.userId })).rejects.toMatchObject({ code: "IDEMPOTENCY_CONFLICT" }); await value.store.setRoute({ workspaceId: value.workspaceId, userId: value.userId }, { routeSlot: "EMBEDDING", connectionId: value.connection!.id, modelId: capabilities.openai.modelId, configuration: { embeddingDimensions: 4 } }); await expect(value.gateway.execute(base, { userId: value.userId })).rejects.toMatchObject({ code: "IDEMPOTENCY_CONFLICT" }); expect(value.transport.calls).toHaveLength(1); expect(await prisma.providerInvocationAttempt.count({ where: { workspaceId: value.workspaceId } })).toBe(1); });
  it("pins the selected embedding provider/model/dimension and retired credential across retry", async () => { let calls = 0; const replacement = "phase8c-replacement-credential"; const value = await fixture("openai", () => ++calls === 1 ? ({ status: 500, headers: {}, body: "{}" }) : ({ status: 200, headers: {}, body: JSON.stringify(body("openai")) }), { maxAttempts: 2, alternateProvider: "qwen", beforeRetry: async context => { await context.store.rotateCredential({ workspaceId: context.workspaceId, userId: context.userId }, context.connection.id, replacement); const qwen = await context.store.createConnection({ workspaceId: context.workspaceId, userId: context.userId }, { providerKey: "qwen", protocol: protocols.qwen, displayName: "qwen" }); await context.store.rotateCredential({ workspaceId: context.workspaceId, userId: context.userId }, qwen.id, replacement); await context.store.setRoute({ workspaceId: context.workspaceId, userId: context.userId }, { routeSlot: "EMBEDDING", connectionId: qwen.id, modelId: capabilities.qwen.modelId, configuration: { qwenRegion: "BEIJING", qwenWorkspaceId: "phase8cworkspace", embeddingDimensions: 4 } }); } }); const result = await value.gateway.execute(request(value.workspaceId, "pinned"), { userId: value.userId }); expect(result).toMatchObject({ status: "SUCCEEDED", attempt: 2, response: { dimensions: 3 } }); expect(value.transport.calls).toHaveLength(2); expect(value.alternateTransport!.calls).toHaveLength(0); for (const call of value.transport.calls) { expect(call.headers.authorization).toBe(`Bearer ${secret}`); expect(call.body).toContain(capabilities.openai.modelId); expect(call.body).toContain('"dimensions":3'); expect(call.body).not.toContain(replacement); } });
  it("rejects revoked pinned credentials before a second embedding HTTP call", async () => { let calls = 0; const value = await fixture("openai", () => ({ status: 500, headers: {}, body: "{}" }), { maxAttempts: 2 }); const gateway = createProductionProviderGateway(registry(), { resolveWorkspaceRoute: value.store.resolveWorkspaceRoute.bind(value.store) }, { resolve: async () => undefined }, () => new OpenAIEmbeddingAdapter(value.transport), { authorize: (principal, input) => new WorkspaceMembershipExecutionAuthorizer(prisma).authorizeExecution(principal, input.workspaceId), assertRouteUsable: async () => undefined, validateEndpoint: async () => undefined, assertBudget: () => undefined, repository: new ProviderExecutionRepository(prisma, testCipher()), circuit: { admit: async () => undefined, recordSuccess: async () => undefined, recordRetryableFailure: async () => undefined }, rate: { admit: async () => undefined }, concurrency: { acquire: async key => ({ key, token: "lease" }), release: async () => true }, maxAttempts: 2, sleep: async () => { calls++; await value.store.revokeCredential({ workspaceId: value.workspaceId, userId: value.userId }, value.credential!.id); }, random: () => 0 }); await expect(gateway.execute(request(value.workspaceId, "revoked"), { userId: value.userId })).rejects.toMatchObject({ code: "CREDENTIAL_REVOKED" }); expect(calls).toBe(1); expect(value.transport.calls).toHaveLength(1); });
  it("uses platform only when the workspace embedding route is absent and fails closed for missing platform credentials", async () => { const positive = await fixture("voyage", undefined, { platform: true }); await expect(positive.gateway.execute(request(positive.workspaceId, "platform"), { userId: positive.userId })).resolves.toMatchObject({ status: "SUCCEEDED" }); expect(positive.transport.calls).toHaveLength(1); expect(positive.platformCalls()).toBe(1); expect(await prisma.providerCredentialVersion.count({ where: { workspaceId: positive.workspaceId } })).toBe(0); const missing = await fixture("voyage", undefined, { platform: true, platformCredential: "" }); await expect(missing.gateway.execute(request(missing.workspaceId, "missing-platform"), { userId: missing.userId })).rejects.toMatchObject({ code: "AUTHENTICATION_FAILED" }); expect(missing.transport.calls).toHaveLength(0); });
  it("WORKSPACE_BYOK_PRECEDENCE uses the selected workspace credential before a configured platform default", async () => { const value = await fixture("openai", undefined, { platformProvider: "qwen", alternateProvider: "qwen" }); await expect(value.gateway.execute(request(value.workspaceId, "precedence"), { userId: value.userId })).resolves.toMatchObject({ status: "SUCCEEDED" }); expect(value.transport.calls).toHaveLength(1); expect(value.transport.calls[0]!.headers.authorization).toBe(`Bearer ${secret}`); expect(value.alternateTransport!.calls).toHaveLength(0); expect(value.platformCalls()).toBe(0); });
  it.each([401, 429, 500])("NO_RUNTIME_PROVIDER_FALLBACK keeps workspace OpenAI selected for %i", async status => { const value = await fixture("openai", () => ({ status, headers: {}, body: JSON.stringify({ marker: secret }) }), { maxAttempts: 2, platformProvider: "qwen", alternateProvider: "qwen" }); await expect(value.gateway.execute(request(value.workspaceId, `no-fallback-${status}`), { userId: value.userId })).rejects.toMatchObject({ code: status === 401 ? "AUTHENTICATION_FAILED" : status === 429 ? "RATE_LIMITED" : "TRANSIENT_UPSTREAM" }); expect(value.transport.calls).toHaveLength(status === 401 ? 1 : 2); expect(value.alternateTransport!.calls).toHaveLength(0); expect(value.platformCalls()).toBe(0); });
  it("ADAPTER_RETRY_OWNERSHIP and GATEWAY_RETRY_OWNERSHIP keep retry policy in the Gateway", async () => { const direct = new DeterministicProviderHttpTransport(() => ({ status: 500, headers: {}, body: "{}" })); const directFixture = { snapshot: { id: "s", workspaceId: "w", routeSlot: "EMBEDDING" as const, correlationId: "c", source: "PLATFORM" as const, providerKey: "openai", protocol: protocols.openai, modelId: capabilities.openai.modelId, adapterVersion: "phase8c", capability: capabilities.openai, configuration: { embeddingDimensions: 3 }, configurationHash: "h", createdAt: new Date() }, request: { ...request("w", "direct"), requestFingerprint: "f" }, signal: new AbortController().signal, credential: secret }; await expect(new OpenAIEmbeddingAdapter(direct).execute(directFixture)).rejects.toMatchObject({ code: "TRANSIENT_UPSTREAM" }); expect(direct.calls).toHaveLength(1); let calls = 0; const gateway = await fixture("openai", () => ++calls === 1 ? ({ status: 500, headers: {}, body: "{}" }) : ({ status: 200, headers: {}, body: JSON.stringify(body("openai")) }), { maxAttempts: 2 }); await expect(gateway.gateway.execute(request(gateway.workspaceId, "gateway-retry"), { userId: gateway.userId })).resolves.toMatchObject({ status: "SUCCEEDED", attempt: 2 }); expect(gateway.transport.calls).toHaveLength(2); });
  it("IN_FLIGHT_CANCELLATION propagates the caller AbortSignal through the production adapter transport without retry", async () => { let entered!: () => void; let observed!: () => void; const enteredRequest = new Promise<void>(resolve => { entered = resolve; }); const observedAbort = new Promise<void>(resolve => { observed = resolve; }); const value = await fixture("openai", request => new Promise((_resolve, reject) => { entered(); request.signal.addEventListener("abort", () => { observed(); reject(new DOMException("aborted", "AbortError")); }, { once: true }); }), { maxAttempts: 2 }); const controller = new AbortController(); const execution = value.gateway.execute({ ...request(value.workspaceId, "in-flight"), signal: controller.signal }, { userId: value.userId }); await enteredRequest; controller.abort(); await observedAbort; await expect(execution).rejects.toMatchObject({ code: "CANCELLED" }); expect(value.transport.calls).toHaveLength(1); expect(await prisma.providerInvocationAttempt.count({ where: { workspaceId: value.workspaceId } })).toBe(1); });
  it("QWEN_WORKSPACE_ID_SECURITY rejects invalid DNS-label workspace ids pre-HTTP and accepts exact boundaries", async () => { const value = await fixture("qwen"); const invalid = ["", "-abc", "abc-", "a".repeat(64), "a.b", "a/b", "a\\b", "a@b", "a:b", "a?b", "a#b", "a%b", "a b", "ｅxample"]; for (const [index, qwenWorkspaceId] of invalid.entries()) { await value.store.setRoute({ workspaceId: value.workspaceId, userId: value.userId }, { routeSlot: "EMBEDDING", connectionId: value.connection!.id, modelId: capabilities.qwen.modelId, configuration: { qwenRegion: "SINGAPORE", qwenWorkspaceId } }); await expect(value.gateway.execute(request(value.workspaceId, `qwen-invalid-${index}`), { userId: value.userId })).rejects.toMatchObject({ code: "NETWORK_POLICY_REJECTED" }); } expect(value.transport.calls).toHaveLength(0); for (const [index, qwenWorkspaceId] of ["a", "a".repeat(63), "phase8c-workspace"].entries()) { await value.store.setRoute({ workspaceId: value.workspaceId, userId: value.userId }, { routeSlot: "EMBEDDING", connectionId: value.connection!.id, modelId: capabilities.qwen.modelId, configuration: { qwenRegion: "BEIJING", qwenWorkspaceId } }); await expect(value.gateway.execute(request(value.workspaceId, `qwen-valid-${index}`), { userId: value.userId })).resolves.toMatchObject({ status: "SUCCEEDED" }); } expect(value.transport.calls).toHaveLength(3); });
  it.each([["DISTRIBUTED_CIRCUIT_GATE", "CIRCUIT_OPEN"], ["DISTRIBUTED_RATE_GATE", "RATE_LIMITED"]] as const)("%s rejects embedding execution before HTTP", async (_gate, control) => { const value = await fixture("openai", undefined, { control }); const attempts = await prisma.providerInvocationAttempt.count({ where: { workspaceId: value.workspaceId } }); await expect(value.gateway.execute(request(value.workspaceId, `control-${control}`), { userId: value.userId })).rejects.toMatchObject({ code: control }); expect(value.transport.calls).toHaveLength(0); expect(await prisma.providerInvocationAttempt.count({ where: { workspaceId: value.workspaceId } })).toBe(attempts); });
  it("DISTRIBUTED_CONCURRENCY_GATE rejects embedding execution before HTTP", async () => { const value = await fixture("openai", undefined, { control: "CONCURRENCY" }); const attempts = await prisma.providerInvocationAttempt.count({ where: { workspaceId: value.workspaceId } }); await expect(value.gateway.execute(request(value.workspaceId, "control-concurrency"), { userId: value.userId })).rejects.toMatchObject({ code: "RATE_LIMITED" }); expect(value.transport.calls).toHaveLength(0); expect(await prisma.providerInvocationAttempt.count({ where: { workspaceId: value.workspaceId } })).toBe(attempts); });
  it("does not persist embedding content, vectors, provider bodies, or credential echoes", async () => { const marker = "EMBEDDING-RUNTIME-SECRET-CONTENT-8C"; const value = await fixture("openai", () => ({ status: 500, headers: {}, body: JSON.stringify({ error: { message: secret, nested: `Bearer ${secret}` }, marker }) })); const error = await value.gateway.execute(request(value.workspaceId, "redaction", { texts: [marker, "two"], purpose: "DOCUMENT" }), { userId: value.userId }).catch(error => error); expect(error).toMatchObject({ code: "TRANSIENT_UPSTREAM" }); expect(JSON.stringify(error)).not.toContain(secret); const persisted = await durable(value.workspaceId); for (const forbidden of [marker, secret, `Bearer ${secret}`, "[1,0,0]"]) expect(persisted).not.toContain(forbidden); });
  it("fails closed before HTTP for cancellation, invalid dimensions, unsupported purposes, and malformed vectors", async () => { const cancelled = await fixture("openai"); const controller = new AbortController(); controller.abort(); await expect(cancelled.gateway.execute({ ...request(cancelled.workspaceId, "cancel"), signal: controller.signal }, { userId: cancelled.userId })).rejects.toMatchObject({ code: "CANCELLED" }); expect(cancelled.transport.calls).toHaveLength(0); const invalidDimension = await fixture("openai", undefined, { configuration: { embeddingDimensions: 99 } }); await expect(invalidDimension.gateway.execute(request(invalidDimension.workspaceId, "dimension"), { userId: invalidDimension.userId })).rejects.toMatchObject({ code: "CAPABILITY_MISMATCH" }); expect(invalidDimension.transport.calls).toHaveLength(0); const unsupported = await fixture("cohere"); await expect(unsupported.gateway.execute(request(unsupported.workspaceId, "purpose", { texts: ["one"], purpose: "SEMANTIC_SIMILARITY" as never }), { userId: unsupported.userId })).rejects.toMatchObject({ code: "CAPABILITY_MISMATCH" }); expect(unsupported.transport.calls).toHaveLength(0); const malformed = await fixture("openai", () => ({ status: 200, headers: {}, body: JSON.stringify(body("openai", [[0, 0, 0], [1, 0, 0]])) })); await expect(malformed.gateway.execute(request(malformed.workspaceId, "vectors"), { userId: malformed.userId })).rejects.toMatchObject({ code: "INVALID_PROVIDER_RESPONSE" }); expect(malformed.transport.calls).toHaveLength(1); });
  it("preserves provider-specific no-truncation wire contracts and one request per logical attempt", async () => { for (const provider of ["gemini", "cohere", "voyage"] as const) { const value = await fixture(provider); await value.gateway.execute(request(value.workspaceId, `wire-${provider}`, { texts: ["exact-marker", "two"], purpose: "DOCUMENT" }), { userId: value.userId }); const wire = JSON.parse(value.transport.calls[0]!.body) as Record<string, unknown>; expect(JSON.stringify(wire)).toContain("exact-marker"); if (provider === "gemini") expect((wire.requests as Array<{ embedContentConfig: { autoTruncate: boolean } }>)[0]!.embedContentConfig.autoTruncate).toBe(false); if (provider === "cohere") expect(wire.truncate).toBe("NONE"); if (provider === "voyage") expect(wire.truncation).toBe(false); expect(value.transport.calls).toHaveLength(1); } });
  it("ZERO_HTTP_MATRIX authorizes only owners and editors before route resolution or durable attempts", async () => {
    const value = await fixture("openai");
    const editorId = randomUUID(), viewerId = randomUUID(), strangerId = randomUUID(); users.push(editorId, viewerId, strangerId);
    for (const id of [editorId, viewerId, strangerId]) await prisma.user.create({ data: { id, email: `${id}@test.invalid` } });
    await prisma.workspaceMember.createMany({ data: [{ workspaceId: value.workspaceId, userId: editorId, role: "EDITOR" }, { workspaceId: value.workspaceId, userId: viewerId, role: "VIEWER" }] });
    await expect(value.gateway.execute(request(value.workspaceId, "owner"), { userId: value.userId })).resolves.toMatchObject({ status: "SUCCEEDED" });
    await expect(value.gateway.execute(request(value.workspaceId, "editor"), { userId: editorId })).resolves.toMatchObject({ status: "SUCCEEDED" });
    const attempts = await prisma.providerInvocationAttempt.count({ where: { workspaceId: value.workspaceId } });
    for (const principal of [{ userId: viewerId }, { userId: strangerId }, undefined]) await expect(value.gateway.execute(request(value.workspaceId, `denied-${principal?.userId ?? "missing"}`), principal)).rejects.toMatchObject({ code: "AUTHORIZATION_FAILED" });
    expect(value.transport.calls).toHaveLength(2);
    expect(await prisma.providerInvocationAttempt.count({ where: { workspaceId: value.workspaceId } })).toBe(attempts);
  });
  it("ZERO_HTTP_MATRIX rejects unavailable routes, unknown models, invalid embedding payloads, budget, and pre-cancellation", async () => {
    const missing = await fixture("openai");
    await prisma.providerRouteBinding.delete({ where: { workspaceId_routeSlot: { workspaceId: missing.workspaceId, routeSlot: "EMBEDDING" } } });
    await expect(missing.gateway.execute(request(missing.workspaceId, "no-route"), { userId: missing.userId })).rejects.toMatchObject({ code: "ROUTE_UNAVAILABLE" });
    expect(missing.transport.calls).toHaveLength(0);
    const unknown = await fixture("openai");
    await unknown.store.setRoute({ workspaceId: unknown.workspaceId, userId: unknown.userId }, { routeSlot: "EMBEDDING", connectionId: unknown.connection!.id, modelId: "unknown-embedding-model" });
    await expect(unknown.gateway.execute(request(unknown.workspaceId, "unknown-model"), { userId: unknown.userId })).rejects.toMatchObject({ code: "MODEL_NOT_FOUND" });
    const invalid = await fixture("openai");
    const cases = [
      { embedding: { texts: [], purpose: "DOCUMENT" as const } },
      { embedding: { texts: ["   "], purpose: "DOCUMENT" as const } },
      { embedding: { texts: ["one", "two", "three"], purpose: "DOCUMENT" as const } },
      { embedding: { texts: ["x".repeat(200_001)], purpose: "DOCUMENT" as const } },
      { embedding: { texts: ["x".repeat(200_000), "x".repeat(200_000), "x".repeat(200_000), "x".repeat(200_000), "x".repeat(200_001)], purpose: "DOCUMENT" as const } },
      { embedding: { texts: ["one"], purpose: "NOT_A_PURPOSE" as never } },
      { text: { messages: [] }, embedding: { texts: ["one"], purpose: "DOCUMENT" as const } },
      { text: { messages: [] } },
    ];
    for (const [index, patch] of cases.entries()) await expect(invalid.gateway.execute({ ...request(invalid.workspaceId, `invalid-${index}`), ...patch } as GatewayRequest, { userId: invalid.userId })).rejects.toBeInstanceOf(ProviderGatewayError);
    await expect(invalid.gateway.execute({ ...request(invalid.workspaceId, "budget"), budget: { maxEmbeddingInputTokens: 1 }, estimates: { embeddingInputTokens: 2 } }, { userId: invalid.userId })).rejects.toMatchObject({ code: "BUDGET_EXCEEDED" });
    const controller = new AbortController(); controller.abort();
    await expect(invalid.gateway.execute({ ...request(invalid.workspaceId, "pre-cancel"), signal: controller.signal }, { userId: invalid.userId })).rejects.toMatchObject({ code: "CANCELLED" });
    expect(invalid.transport.calls).toHaveLength(0);
    expect(await prisma.providerInvocationAttempt.count({ where: { workspaceId: invalid.workspaceId } })).toBe(0);
  });
  it("INPUT_BOUNDARY_MATRIX distinguishes model and global input limits without splitting or truncating accepted texts", async () => {
    const model = await fixture("openai");
    await expect(model.gateway.execute(request(model.workspaceId, "model-2"), { userId: model.userId })).resolves.toMatchObject({ status: "SUCCEEDED" });
    await expect(model.gateway.execute(request(model.workspaceId, "model-3", { texts: ["one", "two", "three"], purpose: "DOCUMENT" }), { userId: model.userId })).rejects.toMatchObject({ code: "INVALID_PROVIDER_RESPONSE" });
    expect(model.transport.calls).toHaveLength(1);
    const boundaryVectors = (count: number) => Array.from({ length: count }, (_value, index) => index === 0 ? [1, 0, 0] : [0, 1, 0]);
    const global = await fixture("openai", request => ({ status: 200, headers: {}, body: JSON.stringify(body("openai", boundaryVectors((JSON.parse(request.body) as { input: string[] }).input.length))) }), { maxEmbeddingInputs: 96 });
    const distinctive = ["prefix:: phase8c", "middle:: untouched", "suffix:: exact"];
    await expect(global.gateway.execute(request(global.workspaceId, "global-96", { texts: Array.from({ length: 96 }, (_value, index) => `item-${index}`), purpose: "DOCUMENT" }), { userId: global.userId })).resolves.toMatchObject({ status: "SUCCEEDED" });
    await expect(global.gateway.execute(request(global.workspaceId, "global-97", { texts: Array.from({ length: 97 }, (_value, index) => `item-${index}`), purpose: "DOCUMENT" }), { userId: global.userId })).rejects.toMatchObject({ code: "INVALID_PROVIDER_RESPONSE" });
    await expect(global.gateway.execute(request(global.workspaceId, "text-200000", { texts: ["x".repeat(200_000)], purpose: "DOCUMENT" }), { userId: global.userId })).resolves.toMatchObject({ status: "SUCCEEDED" });
    await expect(global.gateway.execute(request(global.workspaceId, "total-1000000", { texts: Array.from({ length: 5 }, () => "x".repeat(200_000)), purpose: "DOCUMENT" }), { userId: global.userId })).resolves.toMatchObject({ status: "SUCCEEDED" });
    await expect(global.gateway.execute(request(global.workspaceId, "exact-wire", { texts: distinctive, purpose: "DOCUMENT" }), { userId: global.userId })).resolves.toMatchObject({ status: "SUCCEEDED" });
    expect((JSON.parse(global.transport.calls.at(-1)!.body) as { input: string[] }).input).toEqual(distinctive);
    expect(global.transport.calls).toHaveLength(4);
  });
  it("REMOTE_REQUEST_ID_POLICY persists bounded provider IDs and never stores oversized hostile IDs", async () => {
    const normal = await fixture("openai", () => ({ status: 200, headers: { "x-request-id": "remote-request-8c" }, body: JSON.stringify(body("openai")) }));
    const result = await normal.gateway.execute(request(normal.workspaceId, "request-id-normal"), { userId: normal.userId });
    expect(result).toMatchObject({ remoteRequestId: "remote-request-8c" });
    expect(await prisma.providerInvocationAttempt.findFirstOrThrow({ where: { workspaceId: normal.workspaceId } })).toMatchObject({ remoteRequestId: "remote-request-8c" });
    expect(await prisma.providerUsageEvent.findFirstOrThrow({ where: { workspaceId: normal.workspaceId } })).toMatchObject({ remoteRequestId: "remote-request-8c" });
    const hostile = `HOSTILE-REQUEST-ID-SECRET-${"x".repeat(257)}`;
    const oversized = await fixture("openai", () => ({ status: 200, headers: { "request-id": hostile }, body: JSON.stringify(body("openai")) }));
    await oversized.gateway.execute(request(oversized.workspaceId, "request-id-oversized"), { userId: oversized.userId });
    expect((await prisma.providerInvocationAttempt.findFirstOrThrow({ where: { workspaceId: oversized.workspaceId } })).remoteRequestId).toBeNull();
    expect((await prisma.providerUsageEvent.findFirstOrThrow({ where: { workspaceId: oversized.workspaceId } })).remoteRequestId).toBeNull();
    expect(await durable(oversized.workspaceId)).not.toContain(hostile);
  });
  it("WORKSPACE_ISOLATION prevents cross-workspace execution and repository credential or route administration", async () => {
    const a = await fixture("openai"), b = await fixture("qwen");
    await expect(a.gateway.execute(request(a.workspaceId, "owner-a"), { userId: a.userId })).resolves.toMatchObject({ status: "SUCCEEDED" });
    const attempts = await prisma.providerInvocationAttempt.count({ where: { workspaceId: a.workspaceId } });
    await expect(a.gateway.execute(request(a.workspaceId, "owner-b-on-a"), { userId: b.userId })).rejects.toMatchObject({ code: "AUTHORIZATION_FAILED" });
    await expect(b.gateway.execute(request(b.workspaceId, "owner-a-on-b"), { userId: a.userId })).rejects.toMatchObject({ code: "AUTHORIZATION_FAILED" });
    await expect(b.store.rotateCredential({ workspaceId: a.workspaceId, userId: b.userId }, a.connection!.id, "cross-tenant")).rejects.toMatchObject({ code: "AUTHORIZATION_FAILED" });
    await expect(b.store.revokeCredential({ workspaceId: a.workspaceId, userId: b.userId }, a.credential!.id)).rejects.toMatchObject({ code: "AUTHORIZATION_FAILED" });
    await expect(b.store.setRoute({ workspaceId: a.workspaceId, userId: b.userId }, { routeSlot: "EMBEDDING", connectionId: b.connection!.id, modelId: capabilities.qwen.modelId })).rejects.toMatchObject({ code: "AUTHORIZATION_FAILED" });
    expect(a.transport.calls).toHaveLength(1);
    expect(b.transport.calls).toHaveLength(0);
    expect(await prisma.providerInvocationAttempt.count({ where: { workspaceId: a.workspaceId } })).toBe(attempts);
  });
});
