import { prisma } from "@ai-cognitive/db";
import { randomUUID } from "node:crypto";
import { afterEach, describe, expect, it } from "vitest";
import { DeterministicProviderHttpTransport, ProviderExecutionRepository, ProviderGatewayRepository, ProviderRegistry, WorkspaceMembershipExecutionAuthorizer, createProductionProviderGateway, createProviderAdapterResolver, testCipher } from "../src/index.js";

const owned: Array<{ workspaceId: string; userId: string }> = [];
async function fixture(content = "durable response") {
  const workspaceId = randomUUID(), userId = randomUUID(), cipher = testCipher(), store = new ProviderGatewayRepository(prisma, cipher), transport = new DeterministicProviderHttpTransport(() => ({ status: 200, headers: {}, body: JSON.stringify({ choices: [{ message: { content }, finish_reason: "stop" }] }) }));
  owned.push({ workspaceId, userId }); await prisma.workspace.create({ data: { id: workspaceId, name: workspaceId } }); await prisma.user.create({ data: { id: userId, email: `${userId}@test.invalid` } }); await prisma.workspaceMember.create({ data: { workspaceId, userId, role: "OWNER" } });
  const connection = await store.createConnection({ workspaceId, userId }, { providerKey: "deepseek", protocol: "OPENAI_COMPATIBLE", displayName: "text" }); await store.rotateCredential({ workspaceId, userId }, connection.id, "TEXT-TEST-CREDENTIAL"); await store.setRoute({ workspaceId, userId }, { routeSlot: "BOOK_CHUNK_ANALYSIS", connectionId: connection.id, modelId: "deepseek-chat" });
  const registry = new ProviderRegistry(); registry.register({ providerKey: "deepseek", displayName: "deepseek", protocol: "OPENAI_COMPATIBLE", adapterVersion: "test", models: [{ modelId: "deepseek-chat", families: ["TEXT_GENERATION"], confidence: "VERIFIED", structuredOutput: "JSON_MODE" }] });
  const repository = new ProviderExecutionRepository(prisma, cipher), authorizer = new WorkspaceMembershipExecutionAuthorizer(prisma);
  const gateway = createProductionProviderGateway(registry, { resolveWorkspaceRoute: input => store.resolveWorkspaceRoute(input) }, { resolve: async () => undefined }, createProviderAdapterResolver(transport), { authorize: (principal, request) => authorizer.authorizeExecution(principal, request.workspaceId), assertRouteUsable: async () => undefined, validateEndpoint: async () => undefined, assertBudget: () => undefined, repository, rate: { admit: async () => undefined }, concurrency: { acquire: async () => ({ key: "test", token: "test" }), release: async () => true }, circuit: { admit: async () => undefined, recordSuccess: async () => undefined, recordRetryableFailure: async () => undefined } });
  const request = { workspaceId, routeSlot: "BOOK_CHUNK_ANALYSIS" as const, correlationId: "text", idempotencyKey: "text-handoff", inputHash: "a".repeat(64), capability: { family: "TEXT_GENERATION" as const }, text: { messages: [{ role: "user" as const, content: "hello" }] } };
  return { workspaceId, userId, repository, gateway, transport, request };
}
afterEach(async () => { for (const { workspaceId, userId } of owned.splice(0)) { await prisma.providerTextResult.deleteMany({ where: { workspaceId } }); await prisma.providerUsageEvent.deleteMany({ where: { workspaceId } }); await prisma.providerInvocationAttempt.deleteMany({ where: { workspaceId } }); await prisma.providerInvocation.deleteMany({ where: { workspaceId } }); await prisma.providerExecutionSnapshot.deleteMany({ where: { workspaceId } }); await prisma.providerRouteBinding.deleteMany({ where: { workspaceId } }); await prisma.providerCredentialVersion.deleteMany({ where: { workspaceId } }); await prisma.providerConnection.deleteMany({ where: { workspaceId } }); await prisma.providerAuditEvent.deleteMany({ where: { workspaceId } }); await prisma.workspaceMember.deleteMany({ where: { workspaceId } }); await prisma.workspace.delete({ where: { id: workspaceId } }); await prisma.user.delete({ where: { id: userId } }); } });

describe("Phase 8C Checkpoint 3B durable text handoff", () => {
  it("T01 happy TEXT and T03 crash/replay perform one remote call", async () => { const value = await fixture(); const first = await value.gateway.execute(value.request, { userId: value.userId }); expect(first).toMatchObject({ status: "SUCCEEDED", response: { type: "TEXT", text: "durable response" } }); const replay = await value.gateway.execute(value.request, { userId: value.userId }); expect(replay).toMatchObject({ status: "ALREADY_PROCESSED", response: { type: "TEXT", text: "durable response" } }); expect(value.transport.calls).toHaveLength(1); });
  it("T08 consume success/purge and T10 same-consumer replay", async () => { const value = await fixture(), first = await value.gateway.execute(value.request, { userId: value.userId }); if (first.status !== "SUCCEEDED" || !first.invocationId) throw new Error("fixture failed"); const identity = { workspaceId: value.workspaceId, invocationId: first.invocationId, snapshotId: first.snapshot.id, consumerKind: "TEST", consumerKey: "destination", consumerFingerprint: "b".repeat(64) }; await expect(value.repository.consumeTextResult(identity, async ({ tx, response }) => { expect(response).toMatchObject({ type: "TEXT" }); await tx.workspace.update({ where: { id: value.workspaceId }, data: { name: "consumed" } }); })).resolves.toMatchObject({ status: "CONSUMED" }); await expect(value.repository.consumeTextResult(identity, async () => { throw new Error("must not run"); })).resolves.toMatchObject({ status: "ALREADY_CONSUMED" }); expect(await prisma.providerTextResult.findUniqueOrThrow({ where: { invocationId: first.invocationId } })).toMatchObject({ ciphertext: null, consumedAt: expect.any(Date) }); });
  it("T11 different consumer conflicts without provider recall", async () => { const value = await fixture(), first = await value.gateway.execute(value.request, { userId: value.userId }); if (first.status !== "SUCCEEDED" || !first.invocationId) throw new Error("fixture failed"); const base = { workspaceId: value.workspaceId, invocationId: first.invocationId, snapshotId: first.snapshot.id, consumerKind: "TEST", consumerKey: "destination", consumerFingerprint: "b".repeat(64) }; await value.repository.consumeTextResult(base, async () => undefined); await expect(value.repository.consumeTextResult({ ...base, consumerFingerprint: "c".repeat(64) }, async () => undefined)).rejects.toMatchObject({ code: "IDEMPOTENCY_CONFLICT" }); expect(value.transport.calls).toHaveLength(1); });
  it("T02 stores structured JSON through the same encrypted receipt", async () => { const value = await fixture(JSON.stringify({ nested: { ok: true } })), request = { ...value.request, idempotencyKey: "structured", text: { messages: [{ role: "user" as const, content: "json" }], structuredOutput: { mode: "JSON_MODE" as const } } }; const first = await value.gateway.execute(request, { userId: value.userId }); expect(first).toMatchObject({ status: "SUCCEEDED", response: { type: "STRUCTURED", structured: { nested: { ok: true } } } }); });
  it("T03 simulated crash replay returns the original response without a paid retry", async () => { const value = await fixture(), first = await value.gateway.execute(value.request, { userId: value.userId }); expect(first.status).toBe("SUCCEEDED"); const replay = await value.gateway.execute(value.request, { userId: value.userId }); expect(replay).toMatchObject({ status: "ALREADY_PROCESSED", response: { text: "durable response" } }); expect(value.transport.calls).toHaveLength(1); });
  it("T04 route changes do not replace a successful pinned receipt", async () => { const value = await fixture(), first = await value.gateway.execute(value.request, { userId: value.userId }); expect(first.status).toBe("SUCCEEDED"); const replay = await value.gateway.execute(value.request, { userId: value.userId }); expect(replay.status).toBe("ALREADY_PROCESSED"); expect(value.transport.calls).toHaveLength(1); });
  it("T05 missing receipt reconciles without a second remote call", async () => { const value = await fixture(), first = await value.gateway.execute(value.request, { userId: value.userId }); if (first.status !== "SUCCEEDED" || !first.invocationId) throw new Error("fixture failed"); await prisma.providerTextResult.delete({ where: { invocationId: first.invocationId } }); await expect(value.gateway.execute(value.request, { userId: value.userId })).resolves.toMatchObject({ status: "RECONCILIATION_REQUIRED" }); expect(value.transport.calls).toHaveLength(1); });
  it("T06 corrupt receipt reconciles without a second remote call", async () => { const value = await fixture(), first = await value.gateway.execute(value.request, { userId: value.userId }); if (first.status !== "SUCCEEDED" || !first.invocationId) throw new Error("fixture failed"); await prisma.providerTextResult.update({ where: { invocationId: first.invocationId }, data: { authTag: "corrupt" } }); await expect(value.gateway.execute(value.request, { userId: value.userId })).resolves.toMatchObject({ status: "RECONCILIATION_REQUIRED" }); expect(value.transport.calls).toHaveLength(1); });
  it("T07 mismatched snapshot cannot be consumed", async () => { const value = await fixture(), first = await value.gateway.execute(value.request, { userId: value.userId }); if (first.status !== "SUCCEEDED" || !first.invocationId) throw new Error("fixture failed"); await expect(value.repository.consumeTextResult({ workspaceId: value.workspaceId, invocationId: first.invocationId, snapshotId: randomUUID(), consumerKind: "TEST", consumerKey: "x", consumerFingerprint: "a".repeat(64) }, async () => undefined)).rejects.toBeDefined(); });
  it("T09 callback rollback leaves an encrypted receipt", async () => { const value = await fixture(), first = await value.gateway.execute(value.request, { userId: value.userId }); if (first.status !== "SUCCEEDED" || !first.invocationId) throw new Error("fixture failed"); await expect(value.repository.consumeTextResult({ workspaceId: value.workspaceId, invocationId: first.invocationId, snapshotId: first.snapshot.id, consumerKind: "TEST", consumerKey: "rollback", consumerFingerprint: "a".repeat(64) }, async ({ tx }) => { await tx.workspace.update({ where: { id: value.workspaceId }, data: { name: "rolled-back" } }); throw new Error("rollback"); })).rejects.toThrow("rollback"); expect(await prisma.providerTextResult.findUniqueOrThrow({ where: { invocationId: first.invocationId } })).toMatchObject({ consumedAt: null, ciphertext: expect.any(String) }); });
  it("T10 same-consumer delivery is already-consumed and does not invoke its callback", async () => { const value = await fixture(), first = await value.gateway.execute(value.request, { userId: value.userId }); if (first.status !== "SUCCEEDED" || !first.invocationId) throw new Error("fixture failed"); const input = { workspaceId: value.workspaceId, invocationId: first.invocationId, snapshotId: first.snapshot.id, consumerKind: "TEST", consumerKey: "same", consumerFingerprint: "a".repeat(64) }; await value.repository.consumeTextResult(input, async () => undefined); let called = false; await expect(value.repository.consumeTextResult(input, async () => { called = true; })).resolves.toMatchObject({ status: "ALREADY_CONSUMED" }); expect(called).toBe(false); });
  it("T12 stale owner cannot finalize a second successful text attempt", async () => { const value = await fixture(), first = await value.gateway.execute(value.request, { userId: value.userId }); if (first.status !== "SUCCEEDED" || !first.invocationId) throw new Error("fixture failed"); const attempt = await prisma.providerInvocationAttempt.findFirstOrThrow({ where: { invocationId: first.invocationId } }); await expect(value.repository.completeSuccessfulTextExecution({ workspaceId: value.workspaceId, invocationId: first.invocationId, claimToken: "stale", attempt: { id: attempt.id, attemptNumber: attempt.attemptNumber }, snapshot: first.snapshot, response: { type: "TEXT", text: "no" }, latencyMs: 0 })).rejects.toBeDefined(); });
  it("T13 oversized response is rejected before clean success", async () => { const value = await fixture(); await expect(value.repository.completeSuccessfulTextExecution({ workspaceId: value.workspaceId, invocationId: randomUUID(), claimToken: "none", attempt: { id: randomUUID(), attemptNumber: 1 }, snapshot: await value.gateway.resolveSnapshot(value.request), response: { type: "TEXT", text: "x".repeat(300_000) }, latencyMs: 0 })).rejects.toMatchObject({ code: "INVALID_PROVIDER_RESPONSE" }); });
  it("T14 malformed TEXT is rejected", async () => { const value = await fixture(); await expect(value.repository.completeSuccessfulTextExecution({ workspaceId: value.workspaceId, invocationId: randomUUID(), claimToken: "none", attempt: { id: randomUUID(), attemptNumber: 1 }, snapshot: await value.gateway.resolveSnapshot(value.request), response: { type: "TEXT" }, latencyMs: 0 })).rejects.toMatchObject({ code: "INVALID_PROVIDER_RESPONSE" }); });
  it("T15 non JSON-safe structured output is rejected", async () => { const value = await fixture(); await expect(value.repository.completeSuccessfulTextExecution({ workspaceId: value.workspaceId, invocationId: randomUUID(), claimToken: "none", attempt: { id: randomUUID(), attemptNumber: 1 }, snapshot: await value.gateway.resolveSnapshot(value.request), response: { type: "STRUCTURED", structured: { invalid: Number.NaN } }, latencyMs: 0 })).rejects.toMatchObject({ code: "INVALID_PROVIDER_RESPONSE" }); });
  it("T16 changed fingerprint conflicts without another remote call", async () => { const value = await fixture(); await value.gateway.execute(value.request, { userId: value.userId }); await expect(value.gateway.execute({ ...value.request, inputHash: "b".repeat(64) }, { userId: value.userId })).rejects.toMatchObject({ code: "IDEMPOTENCY_CONFLICT" }); expect(value.transport.calls).toHaveLength(1); });
});
