import { describe, expect, it } from "vitest";
import { createProductionProviderGateway, DeterministicFakeProviderAdapter, ProviderGateway, ProviderGatewayError, ProviderRegistry, VersionedAesGcmCipher, createExecutionSnapshot, redactSecrets, resolveRoute, safeProviderDetail, stableHash, validateProviderEndpoint, withRetry } from "../src/index.js";
import type { GatewayRequest, ResolvedRoute } from "../src/index.js";

const request: GatewayRequest = { workspaceId: "ws-a", routeSlot: "BOOK_CHUNK_ANALYSIS", correlationId: "corr", idempotencyKey: "key", requestFingerprint: "fingerprint", capability: { family: "TEXT_GENERATION", structuredOutput: "STRICT_JSON_SCHEMA" } };
const route: ResolvedRoute = { source: "WORKSPACE", providerKey: "fixture", protocol: "TEST", modelId: "text-1", adapterVersion: "1", connectionId: "connection", credentialVersionId: "credential-1", capability: { modelId: "text-1", families: ["TEXT_GENERATION"], confidence: "VERIFIED", structuredOutput: "STRICT_JSON_SCHEMA" }, configuration: { temperature: 0 } };

describe("Phase 8A provider gateway", () => {
  it("uses stable machine provider identities and hard capability gates", () => { const registry = new ProviderRegistry(); registry.register({ providerKey: "fixture", displayName: "Fixture", protocol: "TEST", adapterVersion: "1", models: [route.capability] }); expect(registry.resolveCapability("fixture", "text-1", request.capability).modelId).toBe("text-1"); expect(() => registry.resolveCapability("fixture", "text-1", { family: "EMBEDDING" })).toThrow(/CAPABILITY_MISMATCH/); });
  it("prefers a workspace route, falls back to the platform resolver, and fails closed", async () => { expect((await resolveRoute(request, { resolveWorkspaceRoute: async () => route }, { resolve: async () => undefined })).source).toBe("WORKSPACE"); expect((await resolveRoute(request, { resolveWorkspaceRoute: async () => undefined }, { resolve: async () => ({ ...route, source: "PLATFORM", connectionId: undefined, credentialVersionId: undefined }) })).source).toBe("PLATFORM"); await expect(resolveRoute(request, { resolveWorkspaceRoute: async () => undefined }, { resolve: async () => undefined })).rejects.toMatchObject({ code: "ROUTE_UNAVAILABLE" }); });
  it("pins immutable routing and credential provenance", () => { const snapshot = createExecutionSnapshot(request, route, new Date("2026-01-01"), "snapshot"); const changed = { ...route, modelId: "text-2", credentialVersionId: "credential-2" }; expect(snapshot.modelId).toBe("text-1"); expect(snapshot.credentialVersionId).toBe("credential-1"); expect(snapshot).not.toMatchObject(changed); expect(stableHash({ b: 1, a: 2 })).toBe(stableHash({ a: 2, b: 1 })); });
  it("encrypts credentials with versioned AES-GCM and tenant-bound AAD", () => { const cipher = new VersionedAesGcmCipher("v1", new Map([["v1", Buffer.alloc(32, 9)], ["v2", Buffer.alloc(32, 8)]])); const aad = { workspaceId: "a", connectionId: "c", credentialVersionId: "v", providerKey: "fixture" }; const encrypted = cipher.encrypt("sk-secret-123456", aad); expect(encrypted.ciphertext).not.toContain("sk-secret"); expect(cipher.decrypt(encrypted, aad)).toBe("sk-secret-123456"); expect(() => cipher.decrypt(encrypted, { ...aad, workspaceId: "b" })).toThrow(ProviderGatewayError); expect(() => cipher.decrypt({ ...encrypted, authTag: "AAAA" }, aad)).toThrow(ProviderGatewayError); });
  it("redacts secrets and rejects unsafe endpoint resolutions", async () => { expect(JSON.stringify(redactSecrets({ authorization: "Bearer sk-secret-123456", message: "token-key-abcdef" }))).not.toContain("secret"); const dns = { lookup: async () => ["127.0.0.1"] }; await expect(validateProviderEndpoint("https://gateway.test", { environment: "production", allowPrivateEndpoints: true, dns })).rejects.toMatchObject({ code: "NETWORK_POLICY_REJECTED" }); await expect(validateProviderEndpoint("https://gateway.test", { environment: "development", allowPrivateEndpoints: true, dns })).resolves.toMatchObject({ addresses: ["127.0.0.1"] }); });
  it("does bounded deterministic retries and never retries non-retryable errors", async () => { let calls = 0; await expect(withRetry(async () => { calls++; throw new ProviderGatewayError("TRANSIENT_UPSTREAM"); }, { maxAttempts: 3, sleep: async () => undefined, random: () => 0 })).rejects.toMatchObject({ code: "TRANSIENT_UPSTREAM" }); expect(calls).toBe(3); calls = 0; await expect(withRetry(async () => { calls++; throw new ProviderGatewayError("AUTHENTICATION_FAILED"); }, { maxAttempts: 3 })).rejects.toMatchObject({ code: "AUTHENTICATION_FAILED" }); expect(calls).toBe(1); });
  it("has deterministic offline adapters and never serializes a malicious secret echo", async () => { const adapter = new DeterministicFakeProviderAdapter("secret_echo", "sk-malicious-123456"); await expect(adapter.execute({ snapshot: createExecutionSnapshot(request, route), request, signal: new AbortController().signal })).rejects.toThrow("sk-malicious"); expect(safeProviderDetail({ detail: "sk-malicious-123456" })).not.toContain("malicious"); });
  it("executes through trusted preflights and normalizes an arbitrary adapter secret", async () => { const registry = new ProviderRegistry(); registry.register({ providerKey: "fixture", displayName: "Fixture", protocol: "TEST", adapterVersion: "1", models: [route.capability] }); const adapter = new DeterministicFakeProviderAdapter("secret_echo", "correct-horse-battery-staple-987654"); const gateway = new ProviderGateway(registry, { resolveWorkspaceRoute: async () => route }, { resolve: async () => undefined }, () => adapter, { reserveIdempotency: async () => "OWNER", beforeAttempt: async () => ({ credential: "correct-horse-battery-staple-987654" }) }); await expect(gateway.execute(request, { workspaceId: "ws-a", userId: "server-user", trusted: true })).rejects.toMatchObject({ code: "INTERNAL_PROVIDER_ERROR", message: "Provider execution failed" }); expect(adapter.calls).toBe(1); await expect(gateway.execute(request, { workspaceId: "ws-b", userId: "server-user", trusted: true })).rejects.toMatchObject({ code: "AUTHORIZATION_FAILED" }); });
  it("fails closed when production construction omits a mandatory control", () => { const registry = new ProviderRegistry(); expect(() => createProductionProviderGateway(registry, { resolveWorkspaceRoute: async () => route }, { resolve: async () => undefined }, () => undefined, {})).toThrow(/Missing mandatory/); });
});
