import { prisma } from "@ai-cognitive/db";
import { randomUUID } from "node:crypto";
import { afterAll, afterEach, describe, expect, it } from "vitest";
import { DeterministicProviderHttpTransport, OpenAICompatibleAdapter, ProviderExecutionRepository, ProviderGatewayRepository, ProviderRegistry, WorkspaceMembershipExecutionAuthorizer, createProductionProviderGateway, testCipher } from "../src/index.js";
import type { GatewayRequest } from "../src/index.js";

const workspaces: string[] = []; const users: string[] = []; const capability = (modelId: string, structuredOutput: "PROMPT_ONLY" | "STRICT_JSON_SCHEMA" = "PROMPT_ONLY") => ({ modelId, families: ["TEXT_GENERATION"] as const, confidence: "VERIFIED" as const, structuredOutput });
const aSecret = "phase8b-evidence-a-secret-123"; const bSecret = "phase8b-evidence-b-secret-456";
async function owner() { const workspaceId = randomUUID(), userId = randomUUID(); workspaces.push(workspaceId); users.push(userId); await prisma.workspace.create({ data: { id: workspaceId, name: workspaceId } }); await prisma.user.create({ data: { id: userId, email: `${userId}@test.invalid` } }); await prisma.workspaceMember.create({ data: { workspaceId, userId, role: "OWNER" } }); return { workspaceId, userId }; }
async function byok(providerKey: "deepseek" | "qwen", modelId: string, structuredOutput: "PROMPT_ONLY" | "STRICT_JSON_SCHEMA" = "PROMPT_ONLY") { const identity = await owner(); const cipher = testCipher(), store = new ProviderGatewayRepository(prisma, cipher); const connection = await store.createConnection(identity, { providerKey, protocol: "OPENAI_COMPATIBLE", displayName: providerKey }); const credential = await store.rotateCredential(identity, connection.id, aSecret); await store.setRoute(identity, { routeSlot: "BOOK_CHUNK_ANALYSIS", connectionId: connection.id, modelId, configuration: providerKey === "qwen" ? { qwenRegion: "US_VIRGINIA" } : {} }); return { ...identity, cipher, store, connection, credential, model: capability(modelId, structuredOutput) }; }
function request(workspaceId: string, idempotencyKey: string, text: GatewayRequest["text"], strict = false): GatewayRequest { return { workspaceId, routeSlot: "BOOK_CHUNK_ANALYSIS", correlationId: idempotencyKey, idempotencyKey, inputHash: "a".repeat(64), capability: { family: "TEXT_GENERATION", ...(strict ? { structuredOutput: "STRICT_JSON_SCHEMA" as const } : {}) }, text }; }
function gateway(registry: ProviderRegistry, store: ProviderGatewayRepository, cipher: ReturnType<typeof testCipher>, resolver: (key: string) => OpenAICompatibleAdapter | undefined, options: { platform?: () => Promise<import("../src/index.js").ResolvedRoute | undefined>; platformCredential?: string; sleep?: () => Promise<void>; maxAttempts?: number } = {}) { return createProductionProviderGateway(registry, { resolveWorkspaceRoute: input => store.resolveWorkspaceRoute(input) }, { resolve: options.platform ?? (async () => undefined) }, resolver, { authorize: (principal, input) => new WorkspaceMembershipExecutionAuthorizer(prisma).authorizeExecution(principal, input.workspaceId), assertRouteUsable: async () => undefined, validateEndpoint: async () => undefined, assertBudget: () => undefined, repository: new ProviderExecutionRepository(prisma, cipher), platformCredentials: { resolve: async () => options.platformCredential }, circuit: { admit: async () => undefined, recordSuccess: async () => undefined, recordRetryableFailure: async () => undefined }, rate: { admit: async () => undefined }, concurrency: { acquire: async key => ({ key, token: "lease" }), release: async () => true }, maxAttempts: options.maxAttempts ?? 2, sleep: options.sleep ?? (async () => undefined), random: () => 0 }); }
function registry(...models: readonly ReturnType<typeof capability>[]) { const value = new ProviderRegistry(); for (const model of models) value.register({ providerKey: model.modelId.startsWith("qwen") ? "qwen" : "deepseek", displayName: model.modelId, protocol: "OPENAI_COMPATIBLE", adapterVersion: "phase8b", models: [model] }); return value; }
afterEach(async () => { for (const id of workspaces.splice(0)) { await prisma.providerUsageEvent.deleteMany({ where: { workspaceId: id } }); await prisma.providerInvocationAttempt.deleteMany({ where: { workspaceId: id } }); await prisma.providerInvocation.deleteMany({ where: { workspaceId: id } }); await prisma.providerExecutionSnapshot.deleteMany({ where: { workspaceId: id } }); await prisma.providerRouteBinding.deleteMany({ where: { workspaceId: id } }); await prisma.providerCredentialVersion.deleteMany({ where: { workspaceId: id } }); await prisma.providerConnection.deleteMany({ where: { workspaceId: id } }); await prisma.providerAuditEvent.deleteMany({ where: { workspaceId: id } }); await prisma.workspaceMember.deleteMany({ where: { workspaceId: id } }); await prisma.workspace.delete({ where: { id } }); } for (const id of users.splice(0)) await prisma.user.delete({ where: { id } }); }); afterAll(async () => prisma.$disconnect());

describe("Phase 8B final acceptance evidence", () => {
  it("proves real text idempotency fingerprints include system, message, generation, and strict schema", async () => { const value = await byok("deepseek", "deepseek-strict", "STRICT_JSON_SCHEMA"); const wire = new DeterministicProviderHttpTransport(() => ({ status: 200, headers: {}, body: JSON.stringify({ choices: [{ message: { content: '{"ok":true}' } }] }) })); const g = gateway(registry(value.model), value.store, value.cipher, () => new OpenAICompatibleAdapter(wire)); const base = { system: "system", messages: [{ role: "user" as const, content: "message" }], generation: { temperature: 0.2 }, structuredOutput: { mode: "STRICT_JSON_SCHEMA" as const, schemaName: "answer", schema: { type: "object", properties: { ok: { type: "boolean" } }, required: ["ok"] } } }; await expect(g.execute(request(value.workspaceId, "same", base, true), { userId: value.userId })).resolves.toMatchObject({ status: "SUCCEEDED" }); await expect(g.execute(request(value.workspaceId, "same", base, true), { userId: value.userId })).resolves.toMatchObject({ status: "ALREADY_PROCESSED" }); expect(wire.calls).toHaveLength(1); for (const changed of [{ ...base, system: "changed" }, { ...base, messages: [{ role: "user" as const, content: "changed" }] }, { ...base, generation: { temperature: 0.7 } }, { ...base, structuredOutput: { ...base.structuredOutput, schema: { type: "object", properties: { changed: { type: "boolean" } } } } }]) await expect(g.execute(request(value.workspaceId, "same", changed, true), { userId: value.userId })).rejects.toMatchObject({ code: "IDEMPOTENCY_CONFLICT" }); expect(wire.calls).toHaveLength(1); });
  it("pins a real text adapter route and retired credential across retry", async () => { const value = await byok("deepseek", "deepseek-a"); let attempts = 0; const a = new DeterministicProviderHttpTransport(() => ++attempts === 1 ? ({ status: 500, headers: {}, body: "{}" }) : ({ status: 200, headers: {}, body: JSON.stringify({ choices: [{ message: { content: "ok" } }] }) })); const b = new DeterministicProviderHttpTransport(() => ({ status: 200, headers: {}, body: JSON.stringify({ choices: [{ message: { content: "wrong" } }] }) })); const g = gateway(registry(value.model, capability("qwen-b")), value.store, value.cipher, key => key === "deepseek" ? new OpenAICompatibleAdapter(a) : new OpenAICompatibleAdapter(b), { sleep: async () => { await value.store.rotateCredential({ workspaceId: value.workspaceId, userId: value.userId }, value.connection.id, bSecret); const connection = await value.store.createConnection({ workspaceId: value.workspaceId, userId: value.userId }, { providerKey: "qwen", protocol: "OPENAI_COMPATIBLE", displayName: "B" }); await value.store.rotateCredential({ workspaceId: value.workspaceId, userId: value.userId }, connection.id, bSecret); await value.store.setRoute({ workspaceId: value.workspaceId, userId: value.userId }, { routeSlot: "BOOK_CHUNK_ANALYSIS", connectionId: connection.id, modelId: "qwen-b", configuration: { qwenRegion: "US_VIRGINIA" } }); } }); await expect(g.execute(request(value.workspaceId, "pinned", { messages: [{ role: "user", content: "x" }] }), { userId: value.userId })).resolves.toMatchObject({ status: "SUCCEEDED", attempt: 2 }); expect(a.calls).toHaveLength(2); expect(b.calls).toHaveLength(0); expect(a.calls[1]?.headers.authorization).toBe(`Bearer ${aSecret}`); });
  it("blocks a revoked pinned credential before a second real adapter call", async () => { const value = await byok("deepseek", "deepseek-a"); const wire = new DeterministicProviderHttpTransport(() => ({ status: 500, headers: {}, body: "{}" })); const g = gateway(registry(value.model), value.store, value.cipher, () => new OpenAICompatibleAdapter(wire), { sleep: async () => { await value.store.revokeCredential({ workspaceId: value.workspaceId, userId: value.userId }, value.credential.id); } }); await expect(g.execute(request(value.workspaceId, "revoked", { messages: [{ role: "user", content: "x" }] }), { userId: value.userId })).rejects.toMatchObject({ code: "CREDENTIAL_REVOKED" }); expect(wire.calls).toHaveLength(1); });
  it("never falls back from a selected workspace text provider and uses platform only when absent", async () => { for (const status of [401, 429, 500]) { const value = await byok("deepseek", "deepseek-a"); const a = new DeterministicProviderHttpTransport(() => ({ status, headers: {}, body: JSON.stringify({ error: { type: status === 429 ? "rate_limit_error" : undefined } }) })); const b = new DeterministicProviderHttpTransport(() => ({ status: 200, headers: {}, body: JSON.stringify({ choices: [{ message: { content: "platform" } }] }) })); let platformResolves = 0; const g = gateway(registry(value.model, capability("qwen-b")), value.store, value.cipher, key => key === "deepseek" ? new OpenAICompatibleAdapter(a) : new OpenAICompatibleAdapter(b), { platform: async () => { platformResolves++; return { source: "PLATFORM", providerKey: "qwen", protocol: "OPENAI_COMPATIBLE", modelId: "qwen-b", adapterVersion: "phase8b", capability: capability("qwen-b"), configuration: { qwenRegion: "US_VIRGINIA" } }; }, platformCredential: bSecret }); await g.execute(request(value.workspaceId, `no-fallback-${status}`, { messages: [{ role: "user", content: "x" }] }), { userId: value.userId }).catch(() => undefined); expect(a.calls.length).toBeGreaterThan(0); expect(b.calls).toHaveLength(0); expect(platformResolves).toBe(0); }
    const identity = await owner(); const cipher = testCipher(), store = new ProviderGatewayRepository(prisma, cipher), b = new DeterministicProviderHttpTransport(() => ({ status: 200, headers: {}, body: JSON.stringify({ choices: [{ message: { content: "platform" } }] }) })); const g = gateway(registry(capability("qwen-b")), store, cipher, () => new OpenAICompatibleAdapter(b), { platform: async () => ({ source: "PLATFORM", providerKey: "qwen", protocol: "OPENAI_COMPATIBLE", modelId: "qwen-b", adapterVersion: "phase8b", capability: capability("qwen-b"), configuration: { qwenRegion: "US_VIRGINIA" } }), platformCredential: bSecret }); await expect(g.execute(request(identity.workspaceId, "platform-positive", { messages: [{ role: "user", content: "x" }] }), { userId: identity.userId })).resolves.toMatchObject({ status: "SUCCEEDED" }); expect(b.calls).toHaveLength(1); });
});
