import { prisma } from "@ai-cognitive/db";
import { randomUUID } from "node:crypto";
import { afterAll, afterEach, describe, expect, it } from "vitest";
import { CohereEmbeddingAdapter, DeterministicProviderHttpTransport, GeminiEmbeddingAdapter, OpenAIEmbeddingAdapter, ProviderExecutionRepository, ProviderGatewayRepository, ProviderRegistry, QwenEmbeddingAdapter, VoyageEmbeddingAdapter, WorkspaceMembershipExecutionAuthorizer, createProductionProviderGateway, testCipher, type GatewayRequest, type ProviderAdapter, type ProviderHttpRequest, type ProviderHttpResponse } from "../src/index.js";

const workspaces: string[] = []; const users: string[] = []; const secret = "phase8c-super-secret-credential";
const protocols = { openai: "OPENAI_EMBEDDINGS", gemini: "GEMINI_EMBEDDINGS", qwen: "OPENAI_COMPATIBLE", cohere: "COHERE_EMBEDDINGS_V2", voyage: "VOYAGE_EMBEDDINGS" } as const;
type Provider = keyof typeof protocols;
const capabilities = {
  openai: { modelId: "text-embedding-3-small", families: ["EMBEDDING"] as const, confidence: "VERIFIED" as const, embeddingDimensions: 3, configurableEmbeddingDimensions: true, embeddingDimensionOptions: [3, 4], maxEmbeddingInputs: 2, embeddingPurposes: ["DOCUMENT", "QUERY", "SEMANTIC_SIMILARITY", "CLASSIFICATION", "CLUSTERING"] as const },
  gemini: { modelId: "gemini-embedding-001", families: ["EMBEDDING"] as const, confidence: "VERIFIED" as const, embeddingDimensions: 3, configurableEmbeddingDimensions: true, embeddingDimensionOptions: [3, 4], maxEmbeddingInputs: 2, embeddingPurposes: ["DOCUMENT", "QUERY", "SEMANTIC_SIMILARITY", "CLASSIFICATION", "CLUSTERING"] as const },
  qwen: { modelId: "text-embedding-v4", families: ["EMBEDDING"] as const, confidence: "VERIFIED" as const, embeddingDimensions: 3, configurableEmbeddingDimensions: true, embeddingDimensionOptions: [3, 4], maxEmbeddingInputs: 2, embeddingPurposes: ["DOCUMENT", "QUERY", "SEMANTIC_SIMILARITY", "CLASSIFICATION", "CLUSTERING"] as const },
  cohere: { modelId: "embed-v4.0", families: ["EMBEDDING"] as const, confidence: "VERIFIED" as const, embeddingDimensions: 3, configurableEmbeddingDimensions: false, maxEmbeddingInputs: 2, embeddingPurposes: ["DOCUMENT", "QUERY", "CLASSIFICATION", "CLUSTERING"] as const },
  voyage: { modelId: "voyage-3.5-lite", families: ["EMBEDDING"] as const, confidence: "VERIFIED" as const, embeddingDimensions: 3, configurableEmbeddingDimensions: false, maxEmbeddingInputs: 2, embeddingPurposes: ["DOCUMENT", "QUERY", "SEMANTIC_SIMILARITY"] as const },
};
const vectors = [[1, 0, 0], [0, 1, 0]];
function body(provider: Provider, output: number[][] = vectors, usage = 7) { if (provider === "gemini") return { embeddings: output.map(values => ({ values })), usageMetadata: { promptTokenCount: usage } }; if (provider === "cohere") return { embeddings: { float: output }, meta: { billed_units: { input_tokens: usage } } }; if (provider === "voyage") return { data: output.map((embedding, index) => ({ index, embedding })), usage: { total_tokens: usage } }; return { data: output.map((embedding, index) => ({ index, embedding })), usage: { prompt_tokens: usage } }; }
function adapter(provider: Provider, transport: DeterministicProviderHttpTransport): ProviderAdapter { return provider === "openai" ? new OpenAIEmbeddingAdapter(transport) : provider === "gemini" ? new GeminiEmbeddingAdapter(transport) : provider === "qwen" ? new QwenEmbeddingAdapter(transport) : provider === "cohere" ? new CohereEmbeddingAdapter(transport) : new VoyageEmbeddingAdapter(transport); }
function registry() { const value = new ProviderRegistry(); for (const provider of Object.keys(protocols) as Provider[]) value.register({ providerKey: provider, displayName: provider, protocol: protocols[provider], adapterVersion: "phase8c", models: [capabilities[provider]] }); return value; }
function request(workspaceId: string, key: string, embedding: GatewayRequest["embedding"] = { texts: ["one", "two"], purpose: "DOCUMENT" }) { return { workspaceId, routeSlot: "EMBEDDING" as const, correlationId: key, idempotencyKey: key, inputHash: "a".repeat(64), capability: { family: "EMBEDDING" as const }, embedding }; }
async function fixture(provider: Provider, responder: (request: ProviderHttpRequest) => ProviderHttpResponse | Promise<ProviderHttpResponse> = () => ({ status: 200, headers: { "x-request-id": "phase8c-request" }, body: JSON.stringify(body(provider)) }), options: { maxAttempts?: number; configuration?: Record<string, unknown>; platform?: boolean; platformCredential?: string } = {}) {
  const workspaceId = randomUUID(), userId = randomUUID(); workspaces.push(workspaceId); users.push(userId); await prisma.workspace.create({ data: { id: workspaceId, name: workspaceId } }); await prisma.user.create({ data: { id: userId, email: `${userId}@test.invalid` } }); await prisma.workspaceMember.create({ data: { workspaceId, userId, role: "OWNER" } });
  const cipher = testCipher(), store = new ProviderGatewayRepository(prisma, cipher), transport = new DeterministicProviderHttpTransport(responder); let connection: { id: string } | undefined; let credential: { id: string } | undefined;
  if (!options.platform) { connection = await store.createConnection({ workspaceId, userId }, { providerKey: provider, protocol: protocols[provider], displayName: provider }); credential = await store.rotateCredential({ workspaceId, userId }, connection.id, secret); await store.setRoute({ workspaceId, userId }, { routeSlot: "EMBEDDING", connectionId: connection.id, modelId: capabilities[provider].modelId, configuration: provider === "qwen" ? { qwenRegion: "BEIJING", qwenWorkspaceId: "phase8cworkspace", ...options.configuration } : { ...options.configuration } }); }
  let platformCalls = 0; const gateway = createProductionProviderGateway(registry(), { resolveWorkspaceRoute: value => store.resolveWorkspaceRoute(value) }, { resolve: async () => options.platform ? ({ source: "PLATFORM" as const, providerKey: provider, protocol: protocols[provider], modelId: capabilities[provider].modelId, adapterVersion: "phase8c", capability: capabilities[provider], configuration: options.configuration ?? {} }) : undefined }, input => input.providerKey === provider ? adapter(provider, transport) : undefined, { authorize: (principal, value) => new WorkspaceMembershipExecutionAuthorizer(prisma).authorizeExecution(principal, value.workspaceId), assertRouteUsable: async () => undefined, validateEndpoint: async () => undefined, assertBudget: () => undefined, repository: new ProviderExecutionRepository(prisma, cipher), platformCredentials: { resolve: async () => { platformCalls++; return options.platformCredential ?? secret; } }, circuit: { admit: async () => undefined, recordSuccess: async () => undefined, recordRetryableFailure: async () => undefined }, rate: { admit: async () => undefined }, concurrency: { acquire: async key => ({ key, token: "lease" }), release: async () => true }, maxAttempts: options.maxAttempts ?? 1, sleep: async () => undefined, random: () => 0 });
  return { workspaceId, userId, store, connection, credential, transport, gateway, platformCalls: () => platformCalls };
}
async function durable(workspaceId: string) { const [snapshots, invocations, attempts, usage, audit] = await Promise.all([prisma.providerExecutionSnapshot.findMany({ where: { workspaceId } }), prisma.providerInvocation.findMany({ where: { workspaceId } }), prisma.providerInvocationAttempt.findMany({ where: { workspaceId } }), prisma.providerUsageEvent.findMany({ where: { workspaceId } }), prisma.providerAuditEvent.findMany({ where: { workspaceId } })]); return JSON.stringify({ snapshots, invocations, attempts, usage, audit }); }
afterEach(async () => { for (const workspaceId of workspaces.splice(0)) { await prisma.providerUsageEvent.deleteMany({ where: { workspaceId } }); await prisma.providerInvocationAttempt.deleteMany({ where: { workspaceId } }); await prisma.providerInvocation.deleteMany({ where: { workspaceId } }); await prisma.providerExecutionSnapshot.deleteMany({ where: { workspaceId } }); await prisma.providerRouteBinding.deleteMany({ where: { workspaceId } }); await prisma.providerCredentialVersion.deleteMany({ where: { workspaceId } }); await prisma.providerConnection.deleteMany({ where: { workspaceId } }); await prisma.providerAuditEvent.deleteMany({ where: { workspaceId } }); await prisma.workspaceMember.deleteMany({ where: { workspaceId } }); await prisma.workspace.delete({ where: { id: workspaceId } }); } for (const userId of users.splice(0)) await prisma.user.delete({ where: { id: userId } }); }); afterAll(async () => prisma.$disconnect());

describe("Phase 8C production embedding Gateway acceptance", () => {
  it.each(["openai", "gemini", "qwen", "cohere", "voyage"] as const)("executes %s through the real Gateway, adapter, PostgreSQL, and credential vault", async provider => { const value = await fixture(provider); const result = await value.gateway.execute(request(value.workspaceId, `success-${provider}`), { userId: value.userId }); expect(result).toMatchObject({ status: "SUCCEEDED", response: { dimensions: 3 }, usage: { embeddingInputTokens: 7 } }); expect(value.transport.calls).toHaveLength(1); expect(value.transport.calls[0]?.headers.authorization ?? value.transport.calls[0]?.headers["x-goog-api-key"]).toContain(secret); const snapshot = await prisma.providerExecutionSnapshot.findFirstOrThrow({ where: { workspaceId: value.workspaceId } }); expect(snapshot).toMatchObject({ providerKey: provider, protocol: protocols[provider], modelId: capabilities[provider].modelId }); expect(await prisma.providerUsageEvent.count({ where: { workspaceId: value.workspaceId, embeddingInputTokens: 7 } })).toBe(1); });
  it("enforces real embedding idempotency, canonical input conflicts, and dimension provenance", async () => { const value = await fixture("openai"); const base = request(value.workspaceId, "same"); await expect(value.gateway.execute(base, { userId: value.userId })).resolves.toMatchObject({ status: "SUCCEEDED" }); await expect(value.gateway.execute(base, { userId: value.userId })).resolves.toMatchObject({ status: "ALREADY_PROCESSED" }); for (const embedding of [{ texts: ["changed", "two"], purpose: "DOCUMENT" as const }, { texts: ["two", "one"], purpose: "DOCUMENT" as const }, { texts: ["one", "two"], purpose: "QUERY" as const }]) await expect(value.gateway.execute(request(value.workspaceId, "same", embedding), { userId: value.userId })).rejects.toMatchObject({ code: "IDEMPOTENCY_CONFLICT" }); await value.store.setRoute({ workspaceId: value.workspaceId, userId: value.userId }, { routeSlot: "EMBEDDING", connectionId: value.connection!.id, modelId: capabilities.openai.modelId, configuration: { embeddingDimensions: 4 } }); await expect(value.gateway.execute(base, { userId: value.userId })).rejects.toMatchObject({ code: "IDEMPOTENCY_CONFLICT" }); expect(value.transport.calls).toHaveLength(1); expect(await prisma.providerInvocationAttempt.count({ where: { workspaceId: value.workspaceId } })).toBe(1); });
  it("pins the selected embedding provider/model/dimension and retired credential across retry", async () => { let calls = 0; const value = await fixture("openai", () => ++calls === 1 ? ({ status: 500, headers: {}, body: "{}" }) : ({ status: 200, headers: {}, body: JSON.stringify(body("openai")) }), { maxAttempts: 2 }); const original = value.gateway; const result = await original.execute(request(value.workspaceId, "pinned"), { userId: value.userId }); expect(result).toMatchObject({ status: "SUCCEEDED", attempt: 2 }); expect(value.transport.calls).toHaveLength(2); expect(value.transport.calls[1]?.headers.authorization).toBe(`Bearer ${secret}`); });
  it("rejects revoked pinned credentials before a second embedding HTTP call", async () => { let calls = 0; const value = await fixture("openai", () => ({ status: 500, headers: {}, body: "{}" }), { maxAttempts: 2 }); const gateway = createProductionProviderGateway(registry(), { resolveWorkspaceRoute: value.store.resolveWorkspaceRoute.bind(value.store) }, { resolve: async () => undefined }, () => new OpenAIEmbeddingAdapter(value.transport), { authorize: (principal, input) => new WorkspaceMembershipExecutionAuthorizer(prisma).authorizeExecution(principal, input.workspaceId), assertRouteUsable: async () => undefined, validateEndpoint: async () => undefined, assertBudget: () => undefined, repository: new ProviderExecutionRepository(prisma, testCipher()), circuit: { admit: async () => undefined, recordSuccess: async () => undefined, recordRetryableFailure: async () => undefined }, rate: { admit: async () => undefined }, concurrency: { acquire: async key => ({ key, token: "lease" }), release: async () => true }, maxAttempts: 2, sleep: async () => { calls++; await value.store.revokeCredential({ workspaceId: value.workspaceId, userId: value.userId }, value.credential!.id); }, random: () => 0 }); await expect(gateway.execute(request(value.workspaceId, "revoked"), { userId: value.userId })).rejects.toMatchObject({ code: "CREDENTIAL_REVOKED" }); expect(calls).toBe(1); expect(value.transport.calls).toHaveLength(1); });
  it("uses platform only when the workspace embedding route is absent and fails closed for missing platform credentials", async () => { const positive = await fixture("voyage", undefined, { platform: true }); await expect(positive.gateway.execute(request(positive.workspaceId, "platform"), { userId: positive.userId })).resolves.toMatchObject({ status: "SUCCEEDED" }); expect(positive.transport.calls).toHaveLength(1); expect(positive.platformCalls()).toBe(1); expect(await prisma.providerCredentialVersion.count({ where: { workspaceId: positive.workspaceId } })).toBe(0); const missing = await fixture("voyage", undefined, { platform: true, platformCredential: "" }); await expect(missing.gateway.execute(request(missing.workspaceId, "missing-platform"), { userId: missing.userId })).rejects.toMatchObject({ code: "AUTHENTICATION_FAILED" }); expect(missing.transport.calls).toHaveLength(0); });
  it("does not persist embedding content, vectors, provider bodies, or credential echoes", async () => { const marker = "EMBEDDING-RUNTIME-SECRET-CONTENT-8C"; const value = await fixture("openai", () => ({ status: 500, headers: {}, body: JSON.stringify({ error: { message: secret, nested: `Bearer ${secret}` }, marker }) })); const error = await value.gateway.execute(request(value.workspaceId, "redaction", { texts: [marker, "two"], purpose: "DOCUMENT" }), { userId: value.userId }).catch(error => error); expect(error).toMatchObject({ code: "TRANSIENT_UPSTREAM" }); expect(JSON.stringify(error)).not.toContain(secret); const persisted = await durable(value.workspaceId); for (const forbidden of [marker, secret, `Bearer ${secret}`, "[1,0,0]"]) expect(persisted).not.toContain(forbidden); });
  it("fails closed before HTTP for cancellation, invalid dimensions, unsupported purposes, and malformed vectors", async () => { const cancelled = await fixture("openai"); const controller = new AbortController(); controller.abort(); await expect(cancelled.gateway.execute({ ...request(cancelled.workspaceId, "cancel"), signal: controller.signal }, { userId: cancelled.userId })).rejects.toMatchObject({ code: "CANCELLED" }); expect(cancelled.transport.calls).toHaveLength(0); const invalidDimension = await fixture("openai", undefined, { configuration: { embeddingDimensions: 99 } }); await expect(invalidDimension.gateway.execute(request(invalidDimension.workspaceId, "dimension"), { userId: invalidDimension.userId })).rejects.toMatchObject({ code: "CAPABILITY_MISMATCH" }); expect(invalidDimension.transport.calls).toHaveLength(0); const unsupported = await fixture("cohere"); await expect(unsupported.gateway.execute(request(unsupported.workspaceId, "purpose", { texts: ["one"], purpose: "SEMANTIC_SIMILARITY" as never }), { userId: unsupported.userId })).rejects.toMatchObject({ code: "CAPABILITY_MISMATCH" }); expect(unsupported.transport.calls).toHaveLength(0); const malformed = await fixture("openai", () => ({ status: 200, headers: {}, body: JSON.stringify(body("openai", [[0, 0, 0], [1, 0, 0]])) })); await expect(malformed.gateway.execute(request(malformed.workspaceId, "vectors"), { userId: malformed.userId })).rejects.toMatchObject({ code: "INVALID_PROVIDER_RESPONSE" }); expect(malformed.transport.calls).toHaveLength(1); });
  it("preserves provider-specific no-truncation wire contracts and one request per logical attempt", async () => { for (const provider of ["gemini", "cohere", "voyage"] as const) { const value = await fixture(provider); await value.gateway.execute(request(value.workspaceId, `wire-${provider}`, { texts: ["exact-marker", "two"], purpose: "DOCUMENT" }), { userId: value.userId }); const wire = JSON.parse(value.transport.calls[0]!.body) as Record<string, unknown>; expect(JSON.stringify(wire)).toContain("exact-marker"); if (provider === "gemini") expect((wire.requests as Array<{ embedContentConfig: { autoTruncate: boolean } }>)[0]!.embedContentConfig.autoTruncate).toBe(false); if (provider === "cohere") expect(wire.truncate).toBe("NONE"); if (provider === "voyage") expect(wire.truncation).toBe(false); expect(value.transport.calls).toHaveLength(1); } });
});
