import { prisma } from "@ai-cognitive/db";
import { randomUUID } from "node:crypto";
import { afterEach, describe, expect, it } from "vitest";
import { DeterministicProviderHttpTransport, ProviderExecutionRepository, ProviderGatewayRepository, ProviderRegistry, WorkspaceMembershipExecutionAuthorizer, createProductionProviderGateway, createProviderAdapterResolver, testCipher } from "../src/index.js";

const owned: Array<{ workspaceId: string; userId: string }> = [];
const secret = "phase8c-speech-test-secret";
const capability = { modelId: "gpt-4o-mini-tts", families: ["SPEECH"] as const, confidence: "VERIFIED" as const, speechFormats: ["wav"] as const, languages: ["en"] as const };
const request = (workspaceId: string, idempotencyKey: string, text = "durable speech", voiceVersion = "1") => ({ workspaceId, routeSlot: "PODCAST_TTS" as const, correlationId: "trace-only", idempotencyKey, inputHash: "a".repeat(64), capability: { family: "SPEECH" as const, outputFormat: "wav" }, speech: { text, language: "en", voice: { providerVoiceId: "alloy", voiceVersion, speakingRate: 1, pitch: 0 }, outputFormat: "wav" }, pipelineVersion: "speech-v1" });
async function fixture() {
  const workspaceId = randomUUID(), userId = randomUUID(), cipher = testCipher(); owned.push({ workspaceId, userId }); await prisma.workspace.create({ data: { id: workspaceId, name: workspaceId } }); await prisma.user.create({ data: { id: userId, email: `${userId}@test.invalid` } }); await prisma.workspaceMember.create({ data: { workspaceId, userId, role: "OWNER" } });
  const store = new ProviderGatewayRepository(prisma, cipher), connection = await store.createConnection({ workspaceId, userId }, { providerKey: "openai", protocol: "CUSTOM_SPEECH", displayName: "speech-a" }); await store.rotateCredential({ workspaceId, userId }, connection.id, secret); await store.setRoute({ workspaceId, userId }, { routeSlot: "PODCAST_TTS", connectionId: connection.id, modelId: capability.modelId, configuration: { modelVersion: "v1", sampleRate: 24_000, channels: 1 } });
  const transport = new DeterministicProviderHttpTransport(() => ({ status: 500, headers: {}, body: "unused" }), () => ({ status: 200, headers: { "content-type": "audio/wav" }, bytes: new Uint8Array([82, 73, 70, 70, 1]) })); const registry = new ProviderRegistry(); registry.register({ providerKey: "openai", displayName: "OpenAI", protocol: "CUSTOM_SPEECH", adapterVersion: "phase8c", models: [capability] }); const repository = new ProviderExecutionRepository(prisma, cipher);
  const gateway = createProductionProviderGateway(registry, { resolveWorkspaceRoute: value => store.resolveWorkspaceRoute(value) }, { resolve: async () => undefined }, createProviderAdapterResolver(transport), { authorize: (principal, input) => new WorkspaceMembershipExecutionAuthorizer(prisma).authorizeExecution(principal, input.workspaceId), assertRouteUsable: async () => undefined, validateEndpoint: async () => undefined, assertBudget: () => undefined, repository, circuit: { admit: async () => undefined, recordSuccess: async () => undefined, recordRetryableFailure: async () => undefined }, rate: { admit: async () => undefined }, concurrency: { acquire: async key => ({ key, token: "lease" }), release: async () => true }, maxAttempts: 1 });
  return { workspaceId, userId, store, connection, repository, gateway, transport };
}
afterEach(async () => { for (const value of owned.splice(0)) { await prisma.providerSpeechResult.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.providerUsageEvent.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.providerInvocationAttempt.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.providerInvocation.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.providerExecutionSnapshot.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.providerRouteBinding.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.providerCredentialVersion.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.providerConnection.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.workspaceMember.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.workspace.delete({ where: { id: value.workspaceId } }); await prisma.user.delete({ where: { id: value.userId } }); } });

describe("Phase 8C real PostgreSQL speech receipt acceptance", () => {
  it("persists encrypted receipt, replays exactly, rejects semantic changes, and pins route A across A to B", async () => {
    const value = await fixture(), base = request(value.workspaceId, "podcast-tts:run:chunk"); const first = await value.gateway.execute(base, { userId: value.userId }); expect(first).toMatchObject({ status: "SUCCEEDED" }); const receipt = await prisma.providerSpeechResult.findFirstOrThrow({ where: { workspaceId: value.workspaceId } }); expect(receipt).toMatchObject({ ciphertext: expect.any(String), iv: expect.any(String), authTag: expect.any(String), keyVersion: expect.any(String), format: "wav" }); expect(await Promise.all([prisma.providerInvocation.count({ where: { workspaceId: value.workspaceId } }), prisma.providerInvocationAttempt.count({ where: { workspaceId: value.workspaceId, status: "SUCCEEDED" } }), prisma.providerUsageEvent.count({ where: { workspaceId: value.workspaceId } })])).toEqual([1, 1, 1]);
    const replay = await value.gateway.execute(base, { userId: value.userId }); expect(replay).toMatchObject({ status: "ALREADY_PROCESSED", invocationId: first.invocationId }); expect(value.transport.calls).toHaveLength(1); await expect(value.gateway.execute(request(value.workspaceId, base.idempotencyKey, "changed"), { userId: value.userId })).rejects.toMatchObject({ code: "IDEMPOTENCY_CONFLICT" }); await expect(value.gateway.execute(request(value.workspaceId, base.idempotencyKey, "durable speech", "changed"), { userId: value.userId })).rejects.toMatchObject({ code: "IDEMPOTENCY_CONFLICT" });
    const b = await value.store.createConnection({ workspaceId: value.workspaceId, userId: value.userId }, { providerKey: "openai", protocol: "CUSTOM_SPEECH", displayName: "speech-b" }); await value.store.rotateCredential({ workspaceId: value.workspaceId, userId: value.userId }, b.id, secret); await value.store.setRoute({ workspaceId: value.workspaceId, userId: value.userId }, { routeSlot: "PODCAST_TTS", connectionId: b.id, modelId: capability.modelId, configuration: { modelVersion: "v1", sampleRate: 24_000, channels: 1 } }); await value.gateway.execute(base, { userId: value.userId }); expect(value.transport.calls).toHaveLength(1); expect(await value.repository.recoverSpeechHandoff(value.workspaceId, first.invocationId!)).toMatchObject({ kind: "RECOVERABLE", response: { bytes: expect.any(Uint8Array) } });
  });
});
