import { estimateProviderCost, type CostQuality } from "./cost.js";
import type { ProviderPricingCatalog, ProviderUsageForCost } from "./pricing.js";
import { p50p95 } from "./percentiles.js";
import { prisma } from "@ai-cognitive/db";
export type EfficiencyEvent = ProviderUsageForCost & { workspaceId: string; correlationId: string; routeSlot: string; invocationId: string; attemptNumber: number; status: "SUCCEEDED" | "FAILED"; latencyMs?: number | null; createdAt: Date };
export type EfficiencyFilter = { workspaceId: string; from: Date; to: Date; correlationId?: string; routeSlot?: string; providerKey?: string; modelId?: string };
export function summarizeProviderEfficiency(catalog: ProviderPricingCatalog, events: readonly EfficiencyEvent[], filter: EfficiencyFilter) {
  const selected = events.filter(event => event.workspaceId === filter.workspaceId && event.createdAt >= filter.from && event.createdAt <= filter.to && (!filter.correlationId || event.correlationId === filter.correlationId) && (!filter.routeSlot || event.routeSlot === filter.routeSlot) && (!filter.providerKey || event.providerKey === filter.providerKey) && (!filter.modelId || event.modelId === filter.modelId));
  const costs = selected.map(event => estimateProviderCost(catalog, event)); const numeric = (key: keyof EfficiencyEvent) => selected.reduce((sum, event) => sum + (typeof event[key] === "number" ? event[key] as number : 0), 0);
  const qualities = costs.reduce<Record<CostQuality, number>>((out, cost) => ({ ...out, [cost.quality]: (out[cost.quality] ?? 0) + 1 }), {} as Record<CostQuality, number>);
  const priced = costs.filter(cost => cost.estimatedCostMicros !== null); const invocations = new Set(selected.map(event => event.invocationId));
  return { pricingCatalogVersion: catalog.version, invocationCount: invocations.size, attemptCount: selected.length, successfulAttempts: selected.filter(event => event.status === "SUCCEEDED").length, failedAttempts: selected.filter(event => event.status === "FAILED").length, retryRate: invocations.size ? selected.filter(event => event.attemptNumber > 1).length / invocations.size : 0, inputTokens: numeric("inputTokens"), cachedInputTokens: numeric("cachedInputTokens"), outputTokens: numeric("outputTokens"), embeddingInputTokens: numeric("embeddingInputTokens"), speechInputCharacters: numeric("speechInputCharacters"), audioDurationMs: numeric("audioDurationMs"), providerLatency: p50p95(selected.flatMap(event => event.latencyMs === undefined || event.latencyMs === null ? [] : [event.latencyMs])), estimatedCostMicros: priced.reduce((sum, cost) => sum + (cost.estimatedCostMicros ?? 0n), 0n), pricingCoverage: selected.length ? priced.length / selected.length : 0, usageQuality: qualities, firstAttemptUsage: selected.filter(event => event.attemptNumber === 1).length, retryUsage: selected.filter(event => event.attemptNumber > 1).length, retryEstimatedCost: costs.filter((_, index) => selected[index]!.attemptNumber > 1).reduce((sum, cost) => sum + (cost.estimatedCostMicros ?? 0n), 0n), duplicatePaidOperationRate: 0 };
}

/** Loads only one tenant and one bounded window before aggregating normalized durable usage events. */
export async function summarizePersistedProviderEfficiency(catalog: ProviderPricingCatalog, filter: EfficiencyFilter, take = 1_000) {
  if (!Number.isInteger(take) || take < 1 || take > 10_000) throw new Error("PERFORMANCE_EVENT_LIMIT_INVALID");
  const rows = await prisma.providerUsageEvent.findMany({
    where: { workspaceId: filter.workspaceId, createdAt: { gte: filter.from, lte: filter.to }, ...(filter.routeSlot ? { routeSlot: filter.routeSlot } : {}), ...(filter.providerKey ? { providerKey: filter.providerKey } : {}), ...(filter.modelId ? { modelId: filter.modelId } : {}), ...(filter.correlationId ? { invocation: { correlationId: filter.correlationId } } : {}) },
    include: { invocation: { select: { correlationId: true } } }, orderBy: { createdAt: "asc" }, take,
  });
  return summarizeProviderEfficiency(catalog, rows.map(row => ({ workspaceId: row.workspaceId, correlationId: row.invocation.correlationId, routeSlot: row.routeSlot, invocationId: row.invocationId, attemptNumber: row.attemptNumber, status: row.status, providerKey: row.providerKey, modelId: row.modelId, capability: row.capability, inputTokens: row.inputTokens, cachedInputTokens: row.cachedInputTokens, outputTokens: row.outputTokens, embeddingInputTokens: row.embeddingInputTokens, speechInputCharacters: row.speechInputCharacters, audioDurationMs: row.audioDurationMs, latencyMs: row.latencyMs, createdAt: row.createdAt })), filter);
}
