import { prisma } from "../../db/src/index.js";

export const BOOK_ANALYSIS_EXECUTION_OWNERSHIP_LOST = "BOOK_ANALYSIS_EXECUTION_OWNERSHIP_LOST";
type OwnedTx = Parameters<Parameters<typeof prisma.$transaction>[0]>[0];
export async function withOwnedAnalysisTransaction<T>(analysisRunId: string, claimToken: string, work: (tx: OwnedTx) => Promise<T>): Promise<T> { return prisma.$transaction(async (tx) => { const owned = await tx.$queryRaw<Array<{ id: string }>>`SELECT "id" FROM "BookAnalysisRun" WHERE "id" = ${analysisRunId} AND "executionClaimToken" = ${claimToken} AND "executionLeaseUntil" > NOW() AND "status" = 'RUNNING'::"AnalysisRunStatus" FOR UPDATE`; if (owned.length !== 1) throw new Error(BOOK_ANALYSIS_EXECUTION_OWNERSHIP_LOST); return work(tx); }); }
export async function claimBookAnalysisRun(analysisRunId: string, claimToken: string): Promise<boolean> { return prisma.$transaction(async (tx) => { const rows = await tx.$queryRaw<Array<{ jobId: string }>>`UPDATE "BookAnalysisRun" SET "status" = 'RUNNING'::"AnalysisRunStatus", "analysisStage" = CASE WHEN "analysisStage" = 'QUEUED'::"AnalysisRunStage" THEN 'CHUNK_ANALYSIS'::"AnalysisRunStage" ELSE "analysisStage" END, "startedAt" = COALESCE("startedAt", NOW()), "completedAt" = NULL, "errorCode" = NULL, "executionClaimToken" = ${claimToken}, "executionClaimedAt" = NOW(), "executionLeaseUntil" = NOW() + INTERVAL '2 minutes' WHERE "id" = ${analysisRunId} AND "status" IN ('QUEUED'::"AnalysisRunStatus", 'RUNNING'::"AnalysisRunStatus") AND ("executionClaimToken" IS NULL OR "executionLeaseUntil" < NOW()) RETURNING "jobId"`; if (rows.length !== 1) return false; await tx.$executeRaw`UPDATE "Job" SET "status" = 'RUNNING'::"JobStatus", "startedAt" = COALESCE("startedAt", NOW()), "completedAt" = NULL, "error" = NULL, "attemptCount" = "attemptCount" + 1 WHERE "id" = ${rows[0]!.jobId}`; return true; }); }
export async function advanceBookAnalysisStage(analysisRunId: string, claimToken: string, expected: string, next: string): Promise<void> { const changed = await prisma.$executeRaw`UPDATE "BookAnalysisRun" SET "analysisStage" = CAST(${next} AS "AnalysisRunStage") WHERE "id" = ${analysisRunId} AND "executionClaimToken" = ${claimToken} AND "executionLeaseUntil" > NOW() AND "status" = 'RUNNING'::"AnalysisRunStatus" AND "analysisStage" = CAST(${expected} AS "AnalysisRunStage")`; if (changed !== 1) throw new Error(BOOK_ANALYSIS_EXECUTION_OWNERSHIP_LOST); }
export async function renewBookAnalysisLease(analysisRunId: string, claimToken: string, leaseMs = 120_000): Promise<void> { const changed = await prisma.$executeRaw`UPDATE "BookAnalysisRun" SET "executionLeaseUntil" = NOW() + (${leaseMs} * INTERVAL '1 millisecond') WHERE "id" = ${analysisRunId} AND "executionClaimToken" = ${claimToken} AND "executionLeaseUntil" > NOW() AND "status" = 'RUNNING'::"AnalysisRunStatus"`; if (changed !== 1) throw new Error(BOOK_ANALYSIS_EXECUTION_OWNERSHIP_LOST); }
export async function assertBookAnalysisOwnership(analysisRunId: string, claimToken: string): Promise<void> { const rows = await prisma.$queryRaw<Array<{ id: string }>>`SELECT "id" FROM "BookAnalysisRun" WHERE "id" = ${analysisRunId} AND "executionClaimToken" = ${claimToken} AND "executionLeaseUntil" > NOW() AND "status" = 'RUNNING'::"AnalysisRunStatus"`; if (rows.length !== 1) throw new Error(BOOK_ANALYSIS_EXECUTION_OWNERSHIP_LOST); }
export async function failOwnedBookAnalysis(analysisRunId: string, jobId: string, claimToken: string, errorCode: string): Promise<boolean> { return prisma.$transaction(async (tx) => { const owned = await tx.$executeRaw`UPDATE "BookAnalysisRun" SET "status" = 'FAILED'::"AnalysisRunStatus", "errorCode" = ${errorCode}, "completedAt" = NOW(), "executionClaimToken" = NULL, "executionClaimedAt" = NULL, "executionLeaseUntil" = NULL WHERE "id" = ${analysisRunId} AND "executionClaimToken" = ${claimToken} AND "executionLeaseUntil" > NOW() AND "status" = 'RUNNING'::"AnalysisRunStatus"`; if (owned !== 1) return false; await tx.$executeRaw`UPDATE "Job" SET "status" = 'FAILED'::"JobStatus", "error" = ${JSON.stringify({ code: errorCode })}::jsonb, "completedAt" = NOW() WHERE "id" = ${jobId}`; return true; }); }
