"use client";
import { useEffect, useState } from "react";
export function PodcastQualityFeedback({ revisionId }: { revisionId: string }) {
  const key = `acs_phase17_podcast_feedback:${revisionId}`, listenedKey = `acs_phase17_listened:${revisionId}`;
  const [visible, setVisible] = useState(false), [naturalness, setNaturalness] = useState(""), [value, setValue] = useState(""), [message, setMessage] = useState("");
  useEffect(() => { const unlock = (event: Event) => { if ((event as CustomEvent<string>).detail === revisionId && !localStorage.getItem(key)) setVisible(true); }; if (localStorage.getItem(listenedKey) && !localStorage.getItem(key)) setVisible(true); window.addEventListener("acs-phase17-podcast-listened", unlock); return () => window.removeEventListener("acs-phase17-podcast-listened", unlock); }, [key, listenedKey, revisionId]);
  async function submit() { const ratings = [{ dimension: "PODCAST_NATURALNESS", rating: naturalness }, { dimension: "PODCAST_VALUE", rating: value }].filter((item) => item.rating); const responses = await Promise.all(ratings.map((item) => fetch("/api/studio/feedback", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ category: "QUALITY", dimension: item.dimension, rating: Number(item.rating), entityType: "PODCAST_AUDIO_REVISION", entityId: revisionId, message: message || undefined, route: window.location.pathname }) }))); if (!responses.every((response) => response.ok)) return; localStorage.setItem(key, "submitted"); setVisible(false); }
  function dismiss() { localStorage.setItem(key, "dismissed"); setVisible(false); }
  if (!visible) return null;
  return <section className="card-panel" aria-label="播客质量反馈" style={{ marginTop: 16 }}><h3 className="section-title">这段播客感觉如何？</h3><p className="page-desc">可选反馈会帮助我们验证播客是否更自然、更有价值。</p><label className="field-label">自然度</label><select className="field-input" value={naturalness} onChange={(event) => setNaturalness(event.target.value)}><option value="">跳过</option>{[1, 2, 3, 4, 5].map((rating) => <option key={rating} value={rating}>{rating}/5</option>)}</select><label className="field-label">价值</label><select className="field-input" value={value} onChange={(event) => setValue(event.target.value)}><option value="">跳过</option>{[1, 2, 3, 4, 5].map((rating) => <option key={rating} value={rating}>{rating}/5</option>)}</select><textarea className="field-input" rows={3} maxLength={2000} placeholder="可选评论" value={message} onChange={(event) => setMessage(event.target.value)} /><div style={{ display: "flex", gap: 8, marginTop: 12 }}><button className="btn btn-primary" disabled={!naturalness && !value} onClick={submit}>提交</button><button className="btn btn-secondary" onClick={dismiss}>暂不反馈</button></div></section>;
}
