"use client";

import { useEffect, useState } from "react";

type Model = { modelId: string; families: string[]; speechFormats?: string[] };
type Provider = { providerKey: string; displayName: string; protocol: string; capabilityProtocols?: Record<string, string>; models: Model[] };
type Connection = { id: string; providerKey: string; protocol: string; displayName: string; endpoint: string | null; region: string | null; status: string; health: string; credential: { id?: string; exists: boolean; displayHint?: string | null; status?: string } };
type Route = { id: string; routeSlot: string; connectionId: string; modelId: string; configuration: Record<string, unknown>; connection: { displayName: string } };
type State = { manifest: { providers: Provider[] }; connections: Connection[]; routes: Route[]; readiness: Record<string, { state: string; missing: string[] }> };
const routeSlots = ["BOOK_CHUNK_ANALYSIS", "BOOK_REDUCTION_ANALYSIS", "BOOK_SYNTHESIS", "EMBEDDING", "PODCAST_SCRIPT", "PODCAST_TTS", "SHORT_VIDEO_SCRIPT", "SHORT_VIDEO_TTS"];

export function ProviderSettings() {
  const [state, setState] = useState<State | null>(null), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const refresh = async () => { const response = await fetch("/api/studio/providers", { cache: "no-store" }); const body = await response.json() as State & { error?: string }; if (!response.ok) throw new Error(body.error ?? "PROVIDER_SETTINGS_LOAD_FAILED"); setState(body); };
  useEffect(() => { queueMicrotask(() => void refresh().catch(error => setMessage(error instanceof Error ? error.message : "PROVIDER_SETTINGS_LOAD_FAILED"))); }, []);
  async function submit(payload: Record<string, unknown>) { setBusy(true); setMessage(""); try { const response = await fetch("/api/studio/providers", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json() as State & { error?: string }; if (!response.ok) throw new Error(body.error ?? "PROVIDER_SETTINGS_SAVE_FAILED"); setState(body); } catch (error) { setMessage(error instanceof Error ? error.message : "PROVIDER_SETTINGS_SAVE_FAILED"); } finally { setBusy(false); } }
  if (!state) return <section className="panel"><p aria-live="polite">{message || "正在加载 AI Provider 设置…"}</p></section>;
  return <div className="stack"><section className="panel"><h2>可用性</h2>{Object.entries(state.readiness).map(([name, item]) => <p key={name}><strong>{name}</strong> · {item.state}{item.missing.length ? ` (${item.missing.join(", ")})` : ""}</p>)}</section><section className="panel"><h2>添加连接</h2><ConnectionForm providers={state.manifest.providers} busy={busy} submit={submit} /></section><section className="panel"><h2>连接与密钥</h2>{state.connections.map(connection => <article className="memory" key={connection.id}><strong>{connection.displayName}</strong><p>{connection.providerKey} · {connection.protocol} · {connection.status} · {connection.credential.exists ? `已配置 ${connection.credential.displayHint ?? ""}` : "未配置密钥"}</p><form action={form => void submit({ action: "SET_CREDENTIAL", connectionId: connection.id, secret: form.get("secret") })}><label>API 密钥<input name="secret" type="password" autoComplete="new-password" required /></label><button className="button secondary" disabled={busy}>加密保存/轮换</button></form>{connection.credential.id && connection.credential.status === "ACTIVE" ? <button className="button secondary" disabled={busy} onClick={() => void submit({ action: "REVOKE_CREDENTIAL", credentialVersionId: connection.credential.id })}>撤销密钥</button> : null}<button className="button secondary" disabled={busy} onClick={() => void submit({ action: "SET_ENABLED", connectionId: connection.id, enabled: connection.status !== "ACTIVE" })}>{connection.status === "ACTIVE" ? "停用" : "启用"}</button></article>)}</section><section className="panel"><h2>执行路由</h2>{routeSlots.map(slot => <RouteForm key={slot} slot={slot} connections={state.connections} providers={state.manifest.providers} existing={state.routes.find(route => route.routeSlot === slot)} busy={busy} submit={submit} />)}</section><p aria-live="polite" className="error">{message}</p></div>;
}

function ConnectionForm({ providers, busy, submit }: { providers: Provider[]; busy: boolean; submit(payload: Record<string, unknown>): Promise<void> }) { const [providerKey, setProviderKey] = useState(providers[0]?.providerKey ?? ""); const provider = providers.find(item => item.providerKey === providerKey); const protocols = provider ? [...new Set([provider.protocol, ...Object.values(provider.capabilityProtocols ?? {})])] : []; return <form action={form => void submit({ action: "CREATE_CONNECTION", providerKey, protocol: form.get("protocol"), displayName: form.get("displayName"), endpoint: form.get("endpoint"), region: form.get("region") || undefined, configuration: parseConfiguration(form.get("configuration")) })}><label>提供商<select value={providerKey} onChange={event => setProviderKey(event.target.value)}>{providers.map(provider => <option value={provider.providerKey} key={provider.providerKey}>{provider.displayName}</option>)}</select></label><label>协议<select name="protocol">{protocols.map(protocol => <option value={protocol} key={protocol}>{protocol}</option>)}</select></label><label>显示名称<input name="displayName" required maxLength={160} /></label><label>执行端点（必填，HTTPS）<input name="endpoint" type="url" required placeholder="https://api.example.com/v1" /></label><label>区域<input name="region" /></label><label>安全配置 JSON<textarea name="configuration" defaultValue="{}" /></label><button className="button" disabled={busy || !provider}>创建连接</button></form>; }

function RouteForm({ slot, connections, providers, existing, busy, submit }: { slot: string; connections: Connection[]; providers: Provider[]; existing?: Route; busy: boolean; submit(payload: Record<string, unknown>): Promise<void> }) { const [selectedConnectionId, setSelectedConnectionId] = useState(existing?.connectionId ?? ""); const connectionId = connections.some(connection => connection.id === selectedConnectionId) ? selectedConnectionId : existing?.connectionId ?? connections[0]?.id ?? ""; const connection = connections.find(item => item.id === connectionId); const provider = providers.find(item => item.providerKey === connection?.providerKey); const capability = slot === "EMBEDDING" ? "EMBEDDING" : slot.endsWith("TTS") ? "SPEECH" : "TEXT_GENERATION"; const models = provider?.models.filter(model => model.families.includes(capability)) ?? []; return <form className="memory" action={form => void submit({ action: "SET_ROUTE", routeSlot: slot, connectionId, modelId: form.get("modelId"), configuration: parseConfiguration(form.get("configuration")) })}><strong>{slot}</strong><label>连接<select value={connectionId} onChange={event => setSelectedConnectionId(event.target.value)}>{connections.map(connection => <option value={connection.id} key={connection.id}>{connection.displayName} ({connection.protocol})</option>)}</select></label><label>模型<select name="modelId" defaultValue={existing?.modelId}>{models.map(model => <option value={model.modelId} key={model.modelId}>{model.modelId}</option>)}</select></label><label>安全路由配置 JSON<textarea name="configuration" defaultValue={JSON.stringify(existing?.configuration ?? {}, null, 2)} /></label><button className="button secondary" disabled={busy || !connection || !models.length}>保存路由</button></form>; }
function parseConfiguration(value: FormDataEntryValue | null): Record<string, unknown> { if (typeof value !== "string" || !value.trim()) return {}; try { const parsed: unknown = JSON.parse(value); return parsed && typeof parsed === "object" && !Array.isArray(parsed) ? parsed as Record<string, unknown> : {}; } catch { return {}; } }
