import { createHash } from "node:crypto";
import { afterAll, afterEach, describe, expect, it } from "vitest";
import { prisma } from "@ai-cognitive/db";
import { S3CompatibleStorageProvider } from "@ai-cognitive/storage";
import { readEnvironment } from "@ai-cognitive/shared/server";
import { createEpisode, createEpisodeAudioConfig, createPodcastProject, createVoiceProfile, processPodcastAudioGenerationRun, requestPodcastAudioGeneration, type SpeechSynthesisProvider } from "../src/index.js";

process.env.NODE_ENV = "test";
process.env.REDIS_URL ??= "redis://localhost:6379";
process.env.DATABASE_URL = process.env.DATABASE_URL_TEST ?? "postgresql://app:app@localhost:5433/ai_cognitive_studio_test?schema=public";
const environment = readEnvironment();
const storage = new S3CompatibleStorageProvider({ endpoint: environment.S3_ENDPOINT, publicEndpoint: environment.S3_PUBLIC_ENDPOINT, region: environment.S3_REGION, bucket: environment.S3_BUCKET, accessKey: environment.S3_ACCESS_KEY, secretKey: environment.S3_SECRET_KEY, forcePathStyle: environment.S3_FORCE_PATH_STYLE });
const sha = (bytes: Uint8Array) => createHash("sha256").update(bytes).digest("hex");
const workspaces: string[] = [], users: string[] = [];
function wav(seed: number) { const samples = 8_000, bytes = new Uint8Array(44 + samples * 2), view = new DataView(bytes.buffer); bytes.set(new TextEncoder().encode("RIFF")); view.setUint32(4, bytes.length - 8, true); bytes.set(new TextEncoder().encode("WAVEfmt "), 8); view.setUint32(16, 16, true); view.setUint16(20, 1, true); view.setUint16(22, 1, true); view.setUint32(24, 8_000, true); view.setUint32(28, 16_000, true); view.setUint16(32, 2, true); view.setUint16(34, 16, true); bytes.set(new TextEncoder().encode("data"), 36); view.setUint32(40, samples * 2, true); for (let i = 0; i < samples; i++) view.setInt16(44 + i * 2, Math.sin(i * seed / 20) * 2_000, true); return bytes; }
class Tts implements SpeechSynthesisProvider { readonly identity = { provider: "durable-wav", model: "fixture", modelVersion: "1" }; readonly capabilities = { supportsSSML: false, supportedOutputFormats: ["wav"] }; readonly calls = new Map<string, number>(); fail = false; gate?: { entered: () => void; wait: Promise<void> }; async synthesize(input: Parameters<SpeechSynthesisProvider["synthesize"]>[0]) { const key = input.text; this.calls.set(key, (this.calls.get(key) ?? 0) + 1); if (this.gate) { this.gate.entered(); await this.gate.wait; } if (this.fail) throw new Error("TTS_DETERMINISTIC_FAILURE"); return { bytes: wav(this.calls.get(key)!), mediaType: "audio/wav", format: "wav", sampleRate: 8_000, channels: 1 }; } }
async function fixture(marker = "A") { const suffix = crypto.randomUUID(), user = await prisma.user.create({ data: { email: `${suffix}@audio.test` } }); users.push(user.id); const workspace = await prisma.workspace.create({ data: { name: suffix } }); workspaces.push(workspace.id); await prisma.workspaceMember.create({ data: { workspaceId: workspace.id, userId: user.id, role: "OWNER" } }); const context = { workspaceId: workspace.id, userId: user.id }; const source = await prisma.source.create({ data: { workspaceId: workspace.id, kind: "FILE", displayName: suffix } }); const blob = await prisma.sourceBlob.create({ data: { workspaceId: workspace.id, sha256: suffix, sizeBytes: 1, mediaType: "text/plain", storageKey: `fixture/${suffix}` } }); const document = await prisma.sourceDocument.create({ data: { workspaceId: workspace.id, sourceId: source.id, sourceBlobId: blob.id, version: 1, sha256: suffix, sizeBytes: 1, mediaType: "text/plain", storageKey: blob.storageKey } }); const project = await createPodcastProject(context, { name: suffix, sourceDocumentIds: [document.id] }); const episode = await createEpisode(context, { podcastProjectId: project.id, title: suffix, targetDurationMinutes: 1 }); const hosts = await prisma.podcastHost.findMany({ where: { podcastProjectId: project.id }, orderBy: { ordinal: "asc" } }); const utterances = Array.from({ length: 8 }, (_, i) => ({ id: `${marker}-${i}`, segmentId: `segment-${Math.floor(i / 4)}`, speakerHostId: hosts[i % 2]!.id, text: `${marker} durable utterance ${i}`, utteranceType: "STATEMENT" })); const script = await prisma.podcastScriptRevision.create({ data: { workspaceId: workspace.id, episodeId: episode.id, revisionNumber: 1, source: "GENERATED", status: "FINAL", estimatedDurationSeconds: 8, scriptSnapshot: { episode: { language: "en" }, utterances } } }); await prisma.currentPodcastScript.create({ data: { workspaceId: workspace.id, episodeId: episode.id, revisionId: script.id } }); const voices = await Promise.all(hosts.map((host, i) => createVoiceProfile(context, { podcastProjectId: project.id, displayName: host.displayName, language: "en", provider: "durable-wav", providerVoiceId: `voice-${i}-${suffix}`, voiceVersion: "1", model: "fixture", modelVersion: "1" }))); const config = await createEpisodeAudioConfig(context, { episodeId: episode.id, outputFormat: "wav", sampleRate: 8_000, channels: 1 }); const requested = await requestPodcastAudioGeneration(context, { episodeId: episode.id, audioConfigId: config.id, provider: "durable-wav", model: "fixture", modelVersion: "1", pipelineVersion: marker, speechPreparationVersion: "v1", assemblyVersion: "v1", normalizationVersion: "v1", hostVoiceProfileIds: Object.fromEntries(hosts.map((host, i) => [host.id, voices[i]!.id])) }); return { context, workspace, project, episode, script, requested, utterances }; }
async function expire(runId: string) { await prisma.$executeRaw`UPDATE "AudioGenerationRun" SET "executionLeaseUntil"=NOW()-INTERVAL '1 second' WHERE "id"=${runId}`; }
afterEach(async () => { for (const id of workspaces.splice(0)) { const runs = await prisma.audioGenerationRun.findMany({ where: { workspaceId: id }, select: { id: true } }); await prisma.currentPodcastAudio.deleteMany({ where: { workspaceId: id } }); await prisma.podcastAudioRevision.deleteMany({ where: { workspaceId: id } }); await prisma.audioGenerationRun.deleteMany({ where: { workspaceId: id } }); await prisma.outboxEvent.deleteMany({ where: { aggregateId: { in: runs.map(run => run.id) } } }); await prisma.job.deleteMany({ where: { workspaceId: id } }); await prisma.currentPodcastScript.deleteMany({ where: { workspaceId: id } }); await prisma.podcastScriptRevision.deleteMany({ where: { workspaceId: id } }); await prisma.podcastProject.deleteMany({ where: { workspaceId: id } }); await prisma.sourceDocument.deleteMany({ where: { workspaceId: id } }); await prisma.source.deleteMany({ where: { workspaceId: id } }); await prisma.sourceBlob.deleteMany({ where: { workspaceId: id } }); await prisma.workspace.delete({ where: { id } }); } await prisma.user.deleteMany({ where: { id: { in: users.splice(0) } } }); }); afterAll(() => prisma.$disconnect());

describe("Phase 4 audio durability", () => {
  it("resumes partial synthesis without re-synthesizing authoritative chunks", async () => { const data = await fixture(); const tts = new Tts(); let completed = 0; await expect(processPodcastAudioGenerationRun(data.requested.run.id, { provider: tts, storage, faultInjector: async point => { if (point === "before-utterance-synthesis" && ++completed === 4) throw new Error("CRASH_BEFORE_CHUNK_FOUR"); } })).rejects.toThrow("CRASH_BEFORE_CHUNK_FOUR"); const first = new Map(tts.calls); await processPodcastAudioGenerationRun(data.requested.run.id, { provider: tts, storage }); const [run, chunks, utterances, revision] = await Promise.all([prisma.audioGenerationRun.findUniqueOrThrow({ where: { id: data.requested.run.id } }), prisma.utteranceSpeechChunk.findMany({ where: { speechPlan: { audioGenerationRunId: data.requested.run.id } } }), prisma.utteranceAudioArtifact.findMany({ where: { audioGenerationRunId: data.requested.run.id } }), prisma.podcastAudioRevision.findMany({ where: { episodeId: data.episode.id } })]); expect(run.status).toBe("SUCCEEDED"); expect(chunks).toHaveLength(8); expect(utterances).toHaveLength(8); expect(revision).toHaveLength(1); for (const [text, count] of first) expect(tts.calls.get(text)).toBe(count); });
  it("prevents stale workers from publishing bytes or stale failure after lease loss", async () => { const data = await fixture(); const a = new Tts(); let entered!: () => void, release!: () => void; const enteredP = new Promise<void>(resolve => entered = resolve), releaseP = new Promise<void>(resolve => release = resolve); a.gate = { entered, wait: releaseP }; const stale = processPodcastAudioGenerationRun(data.requested.run.id, { provider: a, storage }); await enteredP; await expire(data.requested.run.id); const b = new Tts(); await processPodcastAudioGenerationRun(data.requested.run.id, { provider: b, storage }); const before = await prisma.podcastAudioRevision.findFirstOrThrow({ where: { audioGenerationRunId: data.requested.run.id } }); const beforeBytes = await storage.getObjectBytes(before.storageKey); a.fail = true; release(); await expect(stale).rejects.toThrow(); const [run, job, current, after] = await Promise.all([prisma.audioGenerationRun.findUniqueOrThrow({ where: { id: data.requested.run.id } }), prisma.job.findUniqueOrThrow({ where: { id: data.requested.job.id } }), prisma.currentPodcastAudio.findUniqueOrThrow({ where: { episodeId: data.episode.id } }), prisma.podcastAudioRevision.findFirstOrThrow({ where: { audioGenerationRunId: data.requested.run.id } })]); expect([run.status, run.stage, job.status, current.revisionId, after.storageKey, sha(await storage.getObjectBytes(after.storageKey))]).toEqual(["SUCCEEDED", "COMPLETED", "SUCCEEDED", before.id, before.storageKey, before.sha256]); expect(sha(beforeBytes)).toBe(before.sha256); });
  it("is terminal-redelivery idempotent and pins the requested script revision", async () => { const data = await fixture("A"); const tts = new Tts(); await processPodcastAudioGenerationRun(data.requested.run.id, { provider: tts, storage }); const snapshot = await prisma.audioGenerationRun.findUniqueOrThrow({ where: { id: data.requested.run.id }, include: { job: true } }); const calls = [...tts.calls.values()].reduce((a, b) => a + b, 0); const b = await prisma.podcastScriptRevision.create({ data: { workspaceId: data.workspace.id, episodeId: data.episode.id, revisionNumber: 2, source: "USER_EDIT", status: "FINAL", estimatedDurationSeconds: 1, scriptSnapshot: { utterances: [{ id: "b", segmentId: "b", speakerHostId: data.utterances[0]!.speakerHostId, text: "B_ONLY_MARKER", utteranceType: "STATEMENT" }] } } }); await prisma.currentPodcastScript.update({ where: { episodeId: data.episode.id }, data: { revisionId: b.id } }); await processPodcastAudioGenerationRun(data.requested.run.id, { provider: tts, storage }); const revision = await prisma.podcastAudioRevision.findFirstOrThrow({ where: { audioGenerationRunId: data.requested.run.id } }); expect([revision.scriptRevisionId, snapshot.job.attemptCount, [...tts.calls.values()].reduce((a, c) => a + c, 0), [...tts.calls.keys()].some(x => x.includes("B_ONLY_MARKER"))]).toEqual([data.script.id, snapshot.job.attemptCount, calls, false]); });
  it("rejects corrupt media and incompatible voices before they can become current", async () => { const data = await fixture(); const invalid: SpeechSynthesisProvider = { identity: { provider: "durable-wav", model: "fixture", modelVersion: "1" }, capabilities: { supportsSSML: false, supportedOutputFormats: ["wav"] }, async synthesize() { return { bytes: new Uint8Array([1, 2, 3]), mediaType: "audio/wav", format: "wav", sampleRate: 8_000, channels: 1 }; } }; await expect(processPodcastAudioGenerationRun(data.requested.run.id, { provider: invalid, storage })).rejects.toThrow("AUDIO_DECODE_FAILED"); expect(await prisma.currentPodcastAudio.findUnique({ where: { episodeId: data.episode.id } })).toBeNull(); await expect(requestPodcastAudioGeneration(data.context, { episodeId: data.episode.id, provider: "other", model: "other", pipelineVersion: "bad", speechPreparationVersion: "v1", assemblyVersion: "v1", normalizationVersion: "v1", hostVoiceProfileIds: Object.fromEntries((await prisma.podcastHost.findMany({ where: { podcastProjectId: data.project.id } })).map(host => [host.id, "missing"])) })).rejects.toThrow(); });
});
