import { createHash, randomUUID } from "node:crypto";
import { afterAll, afterEach, describe, expect, it } from "vitest";
import { prisma } from "@ai-cognitive/db";
import { ProviderExecutionRepository, createExecutionSnapshot } from "@ai-cognitive/provider-gateway";
import { createEpisode, createEpisodeAudioConfig, createPodcastProject, createVoiceProfile, openPodcastAudioPaidOutcomeQuarantine, podcastAudioSemanticIdentity, processPodcastAudioGenerationRun, requestPodcastAudioGeneration, resolvePodcastAudioPaidOutcomeQuarantine } from "../src/index.js";

process.env.NODE_ENV = "test";
process.env.DATABASE_URL = process.env.DATABASE_URL_TEST ?? "postgresql://app:app@localhost:5433/ai_cognitive_studio_test?schema=public";
const ids: string[] = [];
const sha = (value: unknown) => createHash("sha256").update(JSON.stringify(value)).digest("hex");

async function fixture(correlationId?: string) {
  const token = randomUUID(), user = await prisma.user.create({ data: { email: `${token}@quarantine.test` } });
  const workspace = await prisma.workspace.create({ data: { name: token } }); ids.push(workspace.id);
  await prisma.workspaceMember.create({ data: { workspaceId: workspace.id, userId: user.id, role: "OWNER" } });
  const context = { workspaceId: workspace.id, userId: user.id };
  const source = await prisma.source.create({ data: { workspaceId: workspace.id, kind: "FILE", displayName: token } });
  const blob = await prisma.sourceBlob.create({ data: { workspaceId: workspace.id, sha256: token, sizeBytes: 1, mediaType: "text/plain", storageKey: `q/${token}` } });
  const document = await prisma.sourceDocument.create({ data: { workspaceId: workspace.id, sourceId: source.id, sourceBlobId: blob.id, version: 1, sha256: token, sizeBytes: 1, mediaType: "text/plain", storageKey: blob.storageKey } });
  const project = await createPodcastProject(context, { name: token, sourceDocumentIds: [document.id] });
  const episode = await createEpisode(context, { podcastProjectId: project.id, title: token, targetDurationMinutes: 1 });
  const hosts = await prisma.podcastHost.findMany({ where: { podcastProjectId: project.id }, orderBy: { ordinal: "asc" } });
  const script = await prisma.podcastScriptRevision.create({ data: { workspaceId: workspace.id, episodeId: episode.id, revisionNumber: 1, source: "GENERATED", status: "FINAL", estimatedDurationSeconds: 1, scriptSnapshot: { utterances: hosts.map((host, ordinal) => ({ id: `${token}-${ordinal}`, segmentId: "s", speakerHostId: host.id, text: "hello", utteranceType: "STATEMENT" })) } } });
  await prisma.currentPodcastScript.create({ data: { workspaceId: workspace.id, episodeId: episode.id, revisionId: script.id } });
  const voices = await Promise.all(hosts.map((host, ordinal) => createVoiceProfile(context, { podcastProjectId: project.id, displayName: host.displayName, language: "en", provider: "quarantine", providerVoiceId: `${token}-${ordinal}`, voiceVersion: "1", model: "test", modelVersion: "1" })));
  const config = await createEpisodeAudioConfig(context, { episodeId: episode.id, outputFormat: "wav", sampleRate: 8_000, channels: 1 });
  const input = { episodeId: episode.id, audioConfigId: config.id, provider: "quarantine", model: "test", modelVersion: "1", pipelineVersion: "q1", speechPreparationVersion: "v1", assemblyVersion: "v1", normalizationVersion: "v1", hostVoiceProfileIds: Object.fromEntries(hosts.map((host, ordinal) => [host.id, voices[ordinal]!.id])), correlationId };
  const requested = await requestPodcastAudioGeneration(context, input);
  await prisma.$transaction(async tx => { await tx.audioGenerationRun.update({ where: { id: requested.run.id }, data: { status: "FAILED", errorCode: "REMOTE_OUTCOME_UNKNOWN" } }); await tx.job.update({ where: { id: requested.job.id }, data: { status: "FAILED" } }); });
  const semantic = podcastAudioSemanticIdentity({ episodeId: episode.id, scriptRevisionId: script.id, audioConfig: config, hostVoices: voices.map(v => ({ voiceIdentityHash: sha([v.provider, v.providerVoiceId, v.voiceVersion, v.model, v.modelVersion ?? ""]) })), provider: input.provider, model: input.model, modelVersion: input.modelVersion, pipelineVersion: input.pipelineVersion, speechPreparationVersion: input.speechPreparationVersion, assemblyVersion: input.assemblyVersion, normalizationVersion: input.normalizationVersion, outputFormat: config.outputFormat });
  const snapshot = await prisma.providerExecutionSnapshot.create({ data: { workspaceId: workspace.id, routeSlot: "PODCAST_TTS", providerKey: "custom", protocol: "CUSTOM_SPEECH", modelId: "test", capability: {}, configuration: { mutable: true }, configurationHash: token, adapterVersion: "1", correlationId: requested.run.id } });
  const invocation = await prisma.providerInvocation.create({ data: { workspaceId: workspace.id, snapshotId: snapshot.id, providerKey: "custom", protocol: "CUSTOM_SPEECH", modelId: "test", routeSlot: "PODCAST_TTS", idempotencyKey: `podcast-tts:${requested.run.id}:fixture`, requestFingerprint: token, correlationId: requested.run.id, status: "RECONCILIATION_REQUIRED" } });
  const attempt = await prisma.providerInvocationAttempt.create({ data: { workspaceId: workspace.id, invocationId: invocation.id, attemptNumber: 1, status: "REMOTE_OUTCOME_UNKNOWN", completedAt: new Date() } });
  return { user, workspace, context, episode, config, input, requested, semantic, snapshot, invocation, attempt };
}
async function open(data: Awaited<ReturnType<typeof fixture>>, faultInjector?: (point: "open.after-create" | "resolve.after-update") => void | Promise<void>) { return openPodcastAudioPaidOutcomeQuarantine({ workspaceId: data.workspace.id, audioGenerationRunId: data.requested.run.id, providerInvocationId: data.invocation.id, providerInvocationAttemptId: data.attempt.id, faultInjector }); }
async function counts(workspaceId: string) { const runs = await prisma.audioGenerationRun.findMany({ where: { workspaceId }, select: { id: true } }); return Promise.all([Promise.resolve(runs.length), prisma.job.count({ where: { workspaceId } }), prisma.outboxEvent.count({ where: { aggregateId: { in: runs.map(run => run.id) } } }), prisma.providerInvocation.count({ where: { workspaceId } }), prisma.podcastAudioPaidOutcomeQuarantine.count({ where: { workspaceId } })]); }

afterEach(async () => { for (const workspaceId of ids.splice(0)) { const runs = await prisma.audioGenerationRun.findMany({ where: { workspaceId }, select: { id: true } }); await prisma.podcastAudioPaidOutcomeQuarantine.deleteMany({ where: { workspaceId } }); await prisma.providerInvocationAttempt.deleteMany({ where: { workspaceId } }); await prisma.providerInvocation.deleteMany({ where: { workspaceId } }); await prisma.providerExecutionSnapshot.deleteMany({ where: { workspaceId } }); await prisma.outboxEvent.deleteMany({ where: { aggregateId: { in: runs.map(run => run.id) } } }); await prisma.audioGenerationRun.deleteMany({ where: { workspaceId } }); await prisma.job.deleteMany({ where: { workspaceId } }); await prisma.currentPodcastScript.deleteMany({ where: { workspaceId } }); await prisma.podcastScriptRevision.deleteMany({ where: { workspaceId } }); await prisma.podcastProject.deleteMany({ where: { workspaceId } }); await prisma.sourceDocument.deleteMany({ where: { workspaceId } }); await prisma.source.deleteMany({ where: { workspaceId } }); await prisma.sourceBlob.deleteMany({ where: { workspaceId } }); await prisma.workspace.delete({ where: { id: workspaceId } }); } });
afterAll(() => prisma.$disconnect());

describe("paid outcome quarantine PostgreSQL acceptance", () => {
  it("pins NONE for custom snapshots and atomically creates one durable open gate", async () => { const data = await fixture(); expect(data.snapshot.outcomeRecoveryCapability).toBe("NONE"); await prisma.providerExecutionSnapshot.update({ where: { id: data.snapshot.id }, data: { configuration: { mutable: false } } }); expect((await prisma.providerExecutionSnapshot.findUniqueOrThrow({ where: { id: data.snapshot.id } })).outcomeRecoveryCapability).toBe("NONE"); const opened = await open(data); expect(opened).toMatchObject({ workspaceId: data.workspace.id, audioGenerationRunId: data.requested.run.id, semanticIdentityHash: data.semantic, providerInvocationId: data.invocation.id, providerInvocationAttemptId: data.attempt.id, status: "OPEN", reasonCode: "REMOTE_OUTCOME_UNKNOWN" }); });
  it("uses the PostgreSQL unique index under concurrent genuine ambiguity", async () => { const data = await fixture(); const opened = await Promise.all(Array.from({ length: 10 }, () => open(data))); expect(new Set(opened.map(row => row.id)).size).toBe(1); expect(await prisma.podcastAudioPaidOutcomeQuarantine.count({ where: { workspaceId: data.workspace.id, status: "OPEN" } })).toBe(1); const metadata = await prisma.$queryRaw<Array<{ indexdef: string }>>`SELECT indexdef FROM pg_indexes WHERE indexname='PodcastAudioPaidOutcomeQuarantine_one_open_semantic'`; expect(metadata[0]?.indexdef).toContain('WHERE (status = \'OPEN\''); });
  it("enforces tenant-qualified uniqueness in PostgreSQL even when the service is bypassed", async () => { const data = await fixture(); const first = await open(data); await expect(prisma.podcastAudioPaidOutcomeQuarantine.create({ data: { workspaceId: data.workspace.id, audioGenerationRunId: data.requested.run.id, semanticIdentityHash: data.semantic, providerInvocationId: data.invocation.id, providerInvocationAttemptId: data.attempt.id, reasonCode: "REMOTE_OUTCOME_UNKNOWN" } })).rejects.toMatchObject({ code: "P2002" }); expect(await prisma.podcastAudioPaidOutcomeQuarantine.findUniqueOrThrow({ where: { id: first.id } })).toMatchObject({ status: "OPEN" }); });
  it("uses normal snapshot persistence, does not cross tenant lookup, and rejects both non-owner roles", async () => { const data = await fixture(); const route = { source: "PLATFORM" as const, providerKey: "fixture", protocol: "TEST" as const, modelId: "fixture", adapterVersion: "1", capability: { modelId: "fixture", families: ["SPEECH"] as const, confidence: "VERIFIED" as const }, configuration: { revision: 1 } }; const snapshot = createExecutionSnapshot({ workspaceId: data.workspace.id, routeSlot: "PODCAST_TTS", correlationId: "normal-snapshot", idempotencyKey: "normal-snapshot", inputHash: "a".repeat(64), capability: { family: "SPEECH" } }, route); const claim = await new ProviderExecutionRepository().claimExecution(snapshot, { idempotencyKey: "normal-snapshot", fingerprint: "a".repeat(64) }); if (claim.kind !== "OWNER") throw new Error("normal snapshot owner required"); const changedRoute = { ...route, configuration: { revision: 2 } }; expect(changedRoute.configuration.revision).toBe(2); expect((await new ProviderExecutionRepository().loadExecutionSnapshot(data.workspace.id, snapshot.id)).outcomeRecoveryCapability).toBe("NONE"); const foreign = await fixture(); const q = await open(data); expect(await prisma.podcastAudioPaidOutcomeQuarantine.findFirst({ where: { workspaceId: foreign.workspace.id, semanticIdentityHash: q.semanticIdentityHash, status: "OPEN" } })).toBeNull(); const foreignBefore = await counts(foreign.workspace.id); await requestPodcastAudioGeneration(foreign.context, foreign.input); expect((await counts(foreign.workspace.id))[0]).toBe(foreignBefore[0] + 1); for (const role of ["VIEWER", "EDITOR"] as const) { const user = await prisma.user.create({ data: { email: `${randomUUID()}@${role}.test` } }); await prisma.workspaceMember.create({ data: { workspaceId: data.workspace.id, userId: user.id, role } }); await expect(resolvePodcastAudioPaidOutcomeQuarantine({ workspaceId: data.workspace.id, quarantineId: q.id, actorId: user.id, resolution: "DEFINITIVE_REMOTE_FAILURE", reason: "no" })).rejects.toThrow("AUDIO_PAID_OUTCOME_OPERATOR_ACCESS_DENIED"); } await expect(resolvePodcastAudioPaidOutcomeQuarantine({ workspaceId: foreign.workspace.id, quarantineId: q.id, actorId: foreign.user.id, resolution: "DEFINITIVE_REMOTE_FAILURE", reason: "wrong tenant" })).rejects.toThrow("AUDIO_PAID_OUTCOME_QUARANTINE_NOT_FOUND"); expect((await prisma.podcastAudioPaidOutcomeQuarantine.findUniqueOrThrow({ where: { id: q.id } })).status).toBe("OPEN"); });
  it("rolls back both post-write open and resolution failures", async () => { const data = await fixture(); await expect(open(data, () => { throw new Error("OPEN_INJECTED_FAILURE"); })).rejects.toThrow("OPEN_INJECTED_FAILURE"); expect(await prisma.podcastAudioPaidOutcomeQuarantine.count({ where: { workspaceId: data.workspace.id } })).toBe(0); const q = await open(data); await expect(resolvePodcastAudioPaidOutcomeQuarantine({ workspaceId: data.workspace.id, quarantineId: q.id, actorId: data.user.id, resolution: "DEFINITIVE_REMOTE_FAILURE", reason: "will roll back", faultInjector: () => { throw new Error("RESOLVE_INJECTED_FAILURE"); } })).rejects.toThrow("RESOLVE_INJECTED_FAILURE"); expect(await prisma.podcastAudioPaidOutcomeQuarantine.findUniqueOrThrow({ where: { id: q.id } })).toMatchObject({ status: "OPEN", resolution: null, resolvedAt: null }); });
  it("uses paid operation lineage, not a custom correlation id, to quarantine the real Audio failure path", async () => { const trace = "trace-id-not-equal-to-run-id", data = await fixture(trace); expect(data.requested.run.id).not.toBe(trace); await prisma.podcastAudioPaidOutcomeQuarantine.deleteMany({ where: { workspaceId: data.workspace.id } }); await prisma.providerInvocationAttempt.deleteMany({ where: { workspaceId: data.workspace.id } }); await prisma.providerInvocation.deleteMany({ where: { workspaceId: data.workspace.id } }); await prisma.providerExecutionSnapshot.deleteMany({ where: { workspaceId: data.workspace.id } }); const provider = { identity: { provider: "quarantine", model: "test", modelVersion: "1" }, capabilities: { supportsSSML: false, supportedOutputFormats: ["wav"] }, synthesize: async () => { throw new Error("must not synthesize"); } }; await expect(processPodcastAudioGenerationRun(data.requested.run.id, { provider, storage: {} as never, correlationId: trace, faultInjector: async point => { if (point !== "after-speech-preparation") return; const chunk = await prisma.utteranceSpeechChunk.findFirstOrThrow({ where: { audioGenerationRunId: data.requested.run.id } }); const snapshot = await prisma.providerExecutionSnapshot.create({ data: { workspaceId: data.workspace.id, routeSlot: "PODCAST_TTS", providerKey: "custom", protocol: "CUSTOM_SPEECH", modelId: "test", capability: {}, configuration: {}, configurationHash: randomUUID(), adapterVersion: "1", correlationId: trace } }); const invocation = await prisma.providerInvocation.create({ data: { workspaceId: data.workspace.id, snapshotId: snapshot.id, providerKey: "custom", protocol: "CUSTOM_SPEECH", modelId: "test", routeSlot: "PODCAST_TTS", idempotencyKey: `podcast-tts:${data.requested.run.id}:${chunk.id}`, requestFingerprint: randomUUID(), correlationId: trace, status: "RECONCILIATION_REQUIRED" } }); const attempt = await prisma.providerInvocationAttempt.create({ data: { workspaceId: data.workspace.id, invocationId: invocation.id, attemptNumber: 1, status: "REMOTE_OUTCOME_UNKNOWN", completedAt: new Date() } }); void attempt; throw new Error("FORCED_REMOTE_UNKNOWN"); } })).rejects.toThrow("FORCED_REMOTE_UNKNOWN"); const quarantine = await prisma.podcastAudioPaidOutcomeQuarantine.findFirstOrThrow({ where: { workspaceId: data.workspace.id, status: "OPEN" }, include: { providerInvocation: true, providerInvocationAttempt: true } }); expect([quarantine.audioGenerationRunId, quarantine.providerInvocation.correlationId, quarantine.providerInvocation.idempotencyKey.startsWith(`podcast-tts:${data.requested.run.id}:`), quarantine.providerInvocationAttempt.status]).toEqual([data.requested.run.id, trace, true, "REMOTE_OUTCOME_UNKNOWN"]); const before = await counts(data.workspace.id); const blocked = await requestPodcastAudioGeneration(data.context, data.input); expect("quarantine" in blocked).toBe(true); expect(await counts(data.workspace.id)).toEqual(before); });
  it("rejects a ProviderInvocation whose run-scoped paid operation belongs to another Audio run", async () => { const data = await fixture(); const snapshot = await prisma.providerExecutionSnapshot.create({ data: { workspaceId: data.workspace.id, routeSlot: "PODCAST_TTS", providerKey: "custom", protocol: "CUSTOM_SPEECH", modelId: "test", capability: {}, configuration: {}, configurationHash: randomUUID(), adapterVersion: "1", correlationId: "untrusted" } }); const invocation = await prisma.providerInvocation.create({ data: { workspaceId: data.workspace.id, snapshotId: snapshot.id, providerKey: "custom", protocol: "CUSTOM_SPEECH", modelId: "test", routeSlot: "PODCAST_TTS", idempotencyKey: "podcast-tts:other-run:chunk", requestFingerprint: randomUUID(), correlationId: "untrusted", status: "RECONCILIATION_REQUIRED" } }); const attempt = await prisma.providerInvocationAttempt.create({ data: { workspaceId: data.workspace.id, invocationId: invocation.id, attemptNumber: 1, status: "REMOTE_OUTCOME_UNKNOWN", completedAt: new Date() } }); await expect(openPodcastAudioPaidOutcomeQuarantine({ workspaceId: data.workspace.id, audioGenerationRunId: data.requested.run.id, providerInvocationId: invocation.id, providerInvocationAttemptId: attempt.id })).rejects.toThrow("AUDIO_PAID_OUTCOME_NOT_AMBIGUOUS"); expect(await prisma.podcastAudioPaidOutcomeQuarantine.count({ where: { workspaceId: data.workspace.id } })).toBe(0); });
  it("blocks ordinary and concurrent retries without durable row deltas, while a material semantic change proceeds", async () => { const data = await fixture(); await open(data); const before = await counts(data.workspace.id); const blocked = await Promise.all(Array.from({ length: 10 }, () => requestPodcastAudioGeneration(data.context, data.input))); expect(blocked.every(value => "quarantine" in value)).toBe(true); expect(await counts(data.workspace.id)).toEqual(before); const changed = await requestPodcastAudioGeneration(data.context, { ...data.input, pipelineVersion: "q2" }); expect(changed.run.id).not.toBe(data.requested.run.id); });
  it("keeps the gate authoritative across terminal history and enforces auditable owner-only resolution", async () => { const data = await fixture(); const q = await open(data); const viewer = await prisma.user.create({ data: { email: `${randomUUID()}@viewer.test` } }); await prisma.workspaceMember.create({ data: { workspaceId: data.workspace.id, userId: viewer.id, role: "VIEWER" } }); await expect(resolvePodcastAudioPaidOutcomeQuarantine({ workspaceId: data.workspace.id, quarantineId: q.id, actorId: viewer.id, resolution: "DEFINITIVE_REMOTE_FAILURE", reason: "confirmed" })).rejects.toThrow("AUDIO_PAID_OUTCOME_OPERATOR_ACCESS_DENIED"); await expect(resolvePodcastAudioPaidOutcomeQuarantine({ workspaceId: data.workspace.id, quarantineId: q.id, actorId: data.user.id, resolution: "ABANDON_AND_ALLOW_RETRY", reason: "", riskAcknowledged: false })).rejects.toThrow("AUDIO_PAID_OUTCOME_RESOLUTION_REASON_REQUIRED"); const resolved = await resolvePodcastAudioPaidOutcomeQuarantine({ workspaceId: data.workspace.id, quarantineId: q.id, actorId: data.user.id, resolution: "DEFINITIVE_REMOTE_FAILURE", reason: "confirmed remote failure" }); expect(resolved).toMatchObject({ status: "RESOLVED", resolution: "DEFINITIVE_REMOTE_FAILURE", resolutionActorId: data.user.id, riskAcknowledged: false }); await expect(resolvePodcastAudioPaidOutcomeQuarantine({ workspaceId: data.workspace.id, quarantineId: q.id, actorId: data.user.id, resolution: "DEFINITIVE_REMOTE_FAILURE", reason: "confirmed remote failure" })).resolves.toMatchObject({ id: q.id }); await expect(resolvePodcastAudioPaidOutcomeQuarantine({ workspaceId: data.workspace.id, quarantineId: q.id, actorId: data.user.id, resolution: "ABANDON_AND_ALLOW_RETRY", reason: "different", riskAcknowledged: true })).rejects.toThrow("AUDIO_PAID_OUTCOME_CONTRADICTORY_RESOLUTION"); expect(await prisma.providerInvocation.findUniqueOrThrow({ where: { id: data.invocation.id } })).toMatchObject({ status: "RECONCILIATION_REQUIRED" }); });
  it("permits exactly one fresh retry only after a durable definitive or risk-acknowledged resolution", async () => { const data = await fixture(); const q = await open(data); await expect(resolvePodcastAudioPaidOutcomeQuarantine({ workspaceId: data.workspace.id, quarantineId: q.id, actorId: data.user.id, resolution: "ABANDON_AND_ALLOW_RETRY", reason: "operator accepts duplicate-cost risk", riskAcknowledged: false })).rejects.toThrow("AUDIO_PAID_OUTCOME_RISK_ACKNOWLEDGEMENT_REQUIRED"); const resolved = await resolvePodcastAudioPaidOutcomeQuarantine({ workspaceId: data.workspace.id, quarantineId: q.id, actorId: data.user.id, resolution: "ABANDON_AND_ALLOW_RETRY", reason: "operator accepts duplicate-cost risk", riskAcknowledged: true }); expect(resolved.riskAcknowledged).toBe(true); const before = await counts(data.workspace.id); const retries = await Promise.all(Array.from({ length: 10 }, () => requestPodcastAudioGeneration(data.context, data.input))); expect(new Set(retries.map(value => value.run.id)).size).toBe(1); const after = await counts(data.workspace.id); expect(after.map((value, index) => value - before[index]!)).toEqual([1, 1, 1, 0, 0]); expect(await prisma.providerInvocation.findUniqueOrThrow({ where: { id: data.invocation.id } })).toMatchObject({ status: "RECONCILIATION_REQUIRED" }); });
  it("permits exactly one fresh retry after definitive remote failure", async () => { const data = await fixture(), q = await open(data); await resolvePodcastAudioPaidOutcomeQuarantine({ workspaceId: data.workspace.id, quarantineId: q.id, actorId: data.user.id, resolution: "DEFINITIVE_REMOTE_FAILURE", reason: "confirmed" }); const before = await counts(data.workspace.id), retries = await Promise.all(Array.from({ length: 10 }, () => requestPodcastAudioGeneration(data.context, data.input))), after = await counts(data.workspace.id); expect(new Set(retries.map(value => value.run.id)).size).toBe(1); expect(after.map((value, index) => value - before[index]!)).toEqual([1, 1, 1, 0, 0]); });
  it.each(["DEFINITIVE_REMOTE_FAILURE", "ABANDON_AND_ALLOW_RETRY"] as const)("serializes %s resolution against concurrent normal retries", async resolution => { const data = await fixture(), q = await open(data), before = await counts(data.workspace.id); const [resolved, ...retries] = await Promise.all([resolvePodcastAudioPaidOutcomeQuarantine({ workspaceId: data.workspace.id, quarantineId: q.id, actorId: data.user.id, resolution, reason: "race resolution", riskAcknowledged: resolution === "ABANDON_AND_ALLOW_RETRY" }), ...Array.from({ length: 10 }, () => requestPodcastAudioGeneration(data.context, data.input))]); expect(resolved).toMatchObject({ status: "RESOLVED", resolution }); const after = await counts(data.workspace.id), delta = after.map((value, index) => value - before[index]!); expect(delta[0]).toBeLessThanOrEqual(1); expect(delta[1]).toBeLessThanOrEqual(1); expect(delta[2]).toBeLessThanOrEqual(1); expect(delta[3]).toBe(0); expect(retries.every(value => value.run.id === data.requested.run.id || value.run.workspaceId === data.workspace.id)).toBe(true); });
  it("preserves resolved Q1 while a later independent ambiguity opens Q2 for the same semantic identity", async () => { const data = await fixture(), q1 = await open(data); await resolvePodcastAudioPaidOutcomeQuarantine({ workspaceId: data.workspace.id, quarantineId: q1.id, actorId: data.user.id, resolution: "DEFINITIVE_REMOTE_FAILURE", reason: "first remote failure" }); const retry = await requestPodcastAudioGeneration(data.context, data.input); const snapshot = await prisma.providerExecutionSnapshot.create({ data: { workspaceId: data.workspace.id, routeSlot: "PODCAST_TTS", providerKey: "custom", protocol: "CUSTOM_SPEECH", modelId: "test", capability: {}, configuration: {}, configurationHash: randomUUID(), adapterVersion: "1", correlationId: retry.run.id } }); const invocation = await prisma.providerInvocation.create({ data: { workspaceId: data.workspace.id, snapshotId: snapshot.id, providerKey: "custom", protocol: "CUSTOM_SPEECH", modelId: "test", routeSlot: "PODCAST_TTS", idempotencyKey: `podcast-tts:${retry.run.id}:later`, requestFingerprint: randomUUID(), correlationId: retry.run.id, status: "RECONCILIATION_REQUIRED" } }); const attempt = await prisma.providerInvocationAttempt.create({ data: { workspaceId: data.workspace.id, invocationId: invocation.id, attemptNumber: 1, status: "REMOTE_OUTCOME_UNKNOWN", completedAt: new Date() } }); const q2 = await openPodcastAudioPaidOutcomeQuarantine({ workspaceId: data.workspace.id, audioGenerationRunId: retry.run.id, providerInvocationId: invocation.id, providerInvocationAttemptId: attempt.id }); expect(q2.id).not.toBe(q1.id); expect(await prisma.podcastAudioPaidOutcomeQuarantine.findUniqueOrThrow({ where: { id: q1.id } })).toMatchObject({ status: "RESOLVED", resolution: "DEFINITIVE_REMOTE_FAILURE", resolutionReason: "first remote failure" }); expect(await prisma.podcastAudioPaidOutcomeQuarantine.count({ where: { workspaceId: data.workspace.id, semanticIdentityHash: data.semantic, status: "OPEN" } })).toBe(1); });
});
