import { createHash, randomUUID } from "node:crypto";
import { afterEach, describe, expect, it } from "vitest";
import { prisma } from "@ai-cognitive/db";
import { ProviderExecutionRepository, ProviderGatewayRepository, ProviderRegistry, WorkspaceMembershipExecutionAuthorizer, createProductionProviderGateway, testCipher } from "@ai-cognitive/provider-gateway";
import { readEnvironment } from "@ai-cognitive/shared/server";
import { S3CompatibleStorageProvider } from "@ai-cognitive/storage";
import { createEpisode, createEpisodeAudioConfig, createPodcastProject, createVoiceProfile, processPodcastAudioGenerationRun, requestPodcastAudioGeneration } from "../src/index.js";
import { GatewayPodcastSpeechSynthesisProvider } from "../src/gateway-speech-provider.js";

process.env.NODE_ENV = "test";
const environment = readEnvironment();
const storage = new S3CompatibleStorageProvider({ endpoint: environment.S3_ENDPOINT, publicEndpoint: environment.S3_PUBLIC_ENDPOINT, region: environment.S3_REGION, bucket: environment.S3_BUCKET, accessKey: environment.S3_ACCESS_KEY, secretKey: environment.S3_SECRET_KEY, forcePathStyle: environment.S3_FORCE_PATH_STYLE });
const owned: Array<{ workspaceId: string; userId: string }> = [];
const sha = (bytes: Uint8Array) => createHash("sha256").update(bytes).digest("hex");
function wav() { const samples = 8_000, bytes = new Uint8Array(44 + samples * 2), view = new DataView(bytes.buffer); bytes.set(new TextEncoder().encode("RIFF")); view.setUint32(4, bytes.length - 8, true); bytes.set(new TextEncoder().encode("WAVEfmt "), 8); view.setUint32(16, 16, true); view.setUint16(20, 1, true); view.setUint16(22, 1, true); view.setUint32(24, 8_000, true); view.setUint32(28, 16_000, true); view.setUint16(32, 2, true); view.setUint16(34, 16, true); bytes.set(new TextEncoder().encode("data"), 36); view.setUint32(40, samples * 2, true); for (let i = 0; i < samples; i++) view.setInt16(44 + i * 2, Math.sin(i / 20) * 2_000, true); return bytes; }

async function fixture() {
  const suffix = randomUUID(), user = await prisma.user.create({ data: { email: `${suffix}@speech.test` } }), workspace = await prisma.workspace.create({ data: { name: suffix } }); owned.push({ workspaceId: workspace.id, userId: user.id }); await prisma.workspaceMember.create({ data: { workspaceId: workspace.id, userId: user.id, role: "OWNER" } }); const context = { workspaceId: workspace.id, userId: user.id };
  const source = await prisma.source.create({ data: { workspaceId: workspace.id, kind: "FILE", displayName: suffix } }), blob = await prisma.sourceBlob.create({ data: { workspaceId: workspace.id, sha256: suffix, sizeBytes: 1, mediaType: "text/plain", storageKey: `phase8c/${suffix}` } }), document = await prisma.sourceDocument.create({ data: { workspaceId: workspace.id, sourceId: source.id, sourceBlobId: blob.id, version: 1, sha256: suffix, sizeBytes: 1, mediaType: "text/plain", storageKey: blob.storageKey } });
  const project = await createPodcastProject(context, { name: suffix, sourceDocumentIds: [document.id] }), episode = await createEpisode(context, { podcastProjectId: project.id, title: suffix, targetDurationMinutes: 1 }), hosts = await prisma.podcastHost.findMany({ where: { podcastProjectId: project.id }, orderBy: { ordinal: "asc" } }), utterance = { id: `u-${suffix}`, segmentId: `s-${suffix}`, speakerHostId: hosts[0]!.id, text: "Gateway receipts must survive a crash.", utteranceType: "STATEMENT" };
  const script = await prisma.podcastScriptRevision.create({ data: { workspaceId: workspace.id, episodeId: episode.id, revisionNumber: 1, source: "GENERATED", status: "FINAL", estimatedDurationSeconds: 1, scriptSnapshot: { episode: { language: "en" }, utterances: [utterance] } } }); await prisma.currentPodcastScript.create({ data: { workspaceId: workspace.id, episodeId: episode.id, revisionId: script.id } }); const voices = await Promise.all(hosts.map((host, index) => createVoiceProfile(context, { podcastProjectId: project.id, displayName: host.displayName, language: "en", provider: "openai", providerVoiceId: index ? "nova" : "alloy", voiceVersion: "1", model: "gpt-4o-mini-tts", modelVersion: "v1" }))); const config = await createEpisodeAudioConfig(context, { episodeId: episode.id, outputFormat: "wav", sampleRate: 8_000, channels: 1 }); const requested = await requestPodcastAudioGeneration(context, { episodeId: episode.id, audioConfigId: config.id, provider: "openai", model: "gpt-4o-mini-tts", modelVersion: "v1", pipelineVersion: "phase8c", speechPreparationVersion: "v1", assemblyVersion: "v1", normalizationVersion: "v1", hostVoiceProfileIds: Object.fromEntries(hosts.map((host, index) => [host.id, voices[index]!.id])) });
  const cipher = testCipher(), store = new ProviderGatewayRepository(prisma, cipher), connection = await store.createConnection(context, { providerKey: "openai", protocol: "CUSTOM_SPEECH", displayName: suffix }); await store.rotateCredential(context, connection.id, "test-secret"); await store.setRoute(context, { routeSlot: "PODCAST_TTS", connectionId: connection.id, modelId: "gpt-4o-mini-tts", configuration: { modelVersion: "v1", sampleRate: 8_000, channels: 1 } }); let remoteCalls = 0; const registry = new ProviderRegistry(); registry.register({ providerKey: "openai", displayName: "OpenAI", protocol: "CUSTOM_SPEECH", adapterVersion: "test", models: [{ modelId: "gpt-4o-mini-tts", families: ["SPEECH"], confidence: "VERIFIED", speechFormats: ["wav"], languages: ["en"] }, { modelId: "gpt-4o-mini-tts-incompatible", families: ["SPEECH"], confidence: "VERIFIED", speechFormats: ["wav"], languages: ["en"] }] }); const repository = new ProviderExecutionRepository(prisma, cipher); const gateway = createProductionProviderGateway(registry, { resolveWorkspaceRoute: value => store.resolveWorkspaceRoute(value) }, { resolve: async () => undefined }, () => ({ execute: async () => ({ response: { bytes: wav(), mediaType: "audio/wav", format: "wav", sampleRate: 8_000, channels: 1, durationMs: 1_000 }, usage: { speechInputCharacters: 1 }, remoteRequestId: `remote-${++remoteCalls}` }) }), { authorize: (principal, request) => new WorkspaceMembershipExecutionAuthorizer(prisma).authorizeExecution(principal, request.workspaceId), assertRouteUsable: async () => undefined, validateEndpoint: async () => undefined, assertBudget: () => undefined, repository, circuit: { admit: async () => undefined, recordSuccess: async () => undefined, recordRetryableFailure: async () => undefined }, rate: { admit: async () => undefined }, concurrency: { acquire: async key => ({ key, token: "test" }), release: async () => true }, maxAttempts: 1 });
  const provider = () => new GatewayPodcastSpeechSynthesisProvider({ workspaceId: workspace.id, userId: user.id, audioGenerationRunId: requested.run.id, provider: "openai", model: "gpt-4o-mini-tts", modelVersion: "v1", pipelineVersion: "phase8c", speechPreparationVersion: "v1", gateway, repository }); return { workspace, user, context, store, connection, episode, script, requested, provider, calls: () => remoteCalls };
}
afterEach(async () => { for (const value of owned.splice(0)) { const runs = await prisma.audioGenerationRun.findMany({ where: { workspaceId: value.workspaceId }, select: { id: true } }); await prisma.currentPodcastAudio.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.podcastAudioRevision.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.providerSpeechResult.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.providerUsageEvent.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.providerInvocationAttempt.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.providerInvocation.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.providerExecutionSnapshot.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.providerRouteBinding.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.providerCredentialVersion.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.providerConnection.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.audioGenerationRun.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.outboxEvent.deleteMany({ where: { aggregateId: { in: runs.map(run => run.id) } } }); await prisma.job.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.currentPodcastScript.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.podcastScriptRevision.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.podcastProject.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.sourceDocument.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.source.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.sourceBlob.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.workspace.delete({ where: { id: value.workspaceId } }); await prisma.user.delete({ where: { id: value.userId } }); } });

describe("Phase 8C Podcast Gateway speech receipt", () => {
  it("recovers a post-upload crash without another remote synthesis and rejects a corrupted consumed destination", async () => {
    const value = await fixture(); let crashed = false; await expect(processPodcastAudioGenerationRun(value.requested.run.id, { provider: value.provider(), storage, faultInjector: point => { if (point === "after-speech-upload-before-destination" && !crashed) { crashed = true; throw new Error("CRASH_AFTER_SPEECH_UPLOAD"); } } })).rejects.toThrow("CRASH_AFTER_SPEECH_UPLOAD"); expect(value.calls()).toBe(1); await processPodcastAudioGenerationRun(value.requested.run.id, { provider: value.provider(), storage }); expect(value.calls()).toBe(1); const chunk = await prisma.utteranceSpeechChunk.findFirstOrThrow({ where: { audioGenerationRunId: value.requested.run.id } }); expect(chunk.status).toBe("SUCCEEDED"); const receipt = await prisma.providerSpeechResult.findFirstOrThrow({ where: { workspaceId: value.workspace.id } }); expect([receipt.consumedAt !== null, receipt.ciphertext, receipt.sha256]).toEqual([true, null, chunk.sha256]); await storage.putObject({ key: chunk.storageKey!, body: new Uint8Array([1, 2, 3]), contentType: "audio/wav" }); await expect(processPodcastAudioGenerationRun(value.requested.run.id, { provider: value.provider(), storage })).rejects.toThrow("AUDIO_SPEECH_RECONCILIATION_REQUIRED"); expect(sha(new Uint8Array([1, 2, 3]))).not.toBe(chunk.sha256);
  });
  it("continues after a committed consume before stage advance without another remote synthesis", async () => {
    const value = await fixture(); let crashed = false; await expect(processPodcastAudioGenerationRun(value.requested.run.id, { provider: value.provider(), storage, faultInjector: point => { if (point === "after-speech-destination-consume" && !crashed) { crashed = true; throw new Error("CRASH_AFTER_SPEECH_CONSUME"); } } })).rejects.toThrow("CRASH_AFTER_SPEECH_CONSUME"); const consumed = await prisma.providerSpeechResult.findFirstOrThrow({ where: { workspaceId: value.workspace.id } }), chunks = await prisma.utteranceSpeechChunk.findMany({ where: { audioGenerationRunId: value.requested.run.id } }); expect([value.calls(), consumed.consumedAt !== null, consumed.ciphertext, chunks.filter(chunk => chunk.status === "SUCCEEDED").length]).toEqual([1, true, null, 1]); await processPodcastAudioGenerationRun(value.requested.run.id, { provider: value.provider(), storage }); expect([value.calls(), await prisma.podcastAudioRevision.count({ where: { audioGenerationRunId: value.requested.run.id } }), (await prisma.audioGenerationRun.findUniqueOrThrow({ where: { id: value.requested.run.id } })).status]).toEqual([1, 1, "SUCCEEDED"]);
  });
  it("reuses the encrypted receipt when the process crashes after remote success but before S3 materialization", async () => {
    const value = await fixture(), inner = value.provider(), crashing = { identity: inner.identity, capabilities: inner.capabilities, synthesize: async (input: Parameters<typeof inner.synthesize>[0]) => { await inner.synthesize(input); throw new Error("CRASH_AFTER_SPEECH_RECEIPT"); }, consumeSpeechResult: inner.consumeSpeechResult.bind(inner), verifyConsumedSpeechResult: inner.verifyConsumedSpeechResult.bind(inner) }; await expect(processPodcastAudioGenerationRun(value.requested.run.id, { provider: crashing, storage })).rejects.toThrow("CRASH_AFTER_SPEECH_RECEIPT"); const [receipt, chunks, invocations, attempts, usage] = await Promise.all([prisma.providerSpeechResult.findFirstOrThrow({ where: { workspaceId: value.workspace.id } }), prisma.utteranceSpeechChunk.findMany({ where: { audioGenerationRunId: value.requested.run.id } }), prisma.providerInvocation.count({ where: { workspaceId: value.workspace.id } }), prisma.providerInvocationAttempt.count({ where: { workspaceId: value.workspace.id, status: "SUCCEEDED" } }), prisma.providerUsageEvent.count({ where: { workspaceId: value.workspace.id } })]); expect([value.calls(), invocations, attempts, usage, receipt.ciphertext !== null, receipt.consumedAt, chunks.every(chunk => chunk.status !== "SUCCEEDED")]).toEqual([1, 1, 1, 1, true, null, true]); await processPodcastAudioGenerationRun(value.requested.run.id, { provider: value.provider(), storage }); expect([value.calls(), (await prisma.providerSpeechResult.findFirstOrThrow({ where: { workspaceId: value.workspace.id } })).ciphertext, await prisma.utteranceSpeechChunk.count({ where: { audioGenerationRunId: value.requested.run.id, status: "SUCCEEDED" } })]).toEqual([1, null, 1]);
  });
  it("rejects a deleted consumed destination on terminal redelivery without resynthesis", async () => {
    const value = await fixture(); await processPodcastAudioGenerationRun(value.requested.run.id, { provider: value.provider(), storage }); const chunk = await prisma.utteranceSpeechChunk.findFirstOrThrow({ where: { audioGenerationRunId: value.requested.run.id } }); await prisma.utteranceSpeechChunk.delete({ where: { id: chunk.id } }); await expect(processPodcastAudioGenerationRun(value.requested.run.id, { provider: value.provider(), storage })).rejects.toThrow("AUDIO_SPEECH_RECONCILIATION_REQUIRED"); expect(value.calls()).toBe(1);
  });
  it("fails closed before remote execution when a new operation resolves to an incompatible current route", async () => {
    const value = await fixture(); await value.store.setRoute(value.context, { routeSlot: "PODCAST_TTS", connectionId: value.connection.id, modelId: "gpt-4o-mini-tts-incompatible", configuration: { modelVersion: "v1", sampleRate: 8_000, channels: 1 } }); await expect(processPodcastAudioGenerationRun(value.requested.run.id, { provider: value.provider(), storage })).rejects.toThrow("AUDIO_GATEWAY_ROUTE_IDENTITY_MISMATCH"); expect(value.calls()).toBe(0);
  });
  it("is terminal-redelivery idempotent through the Gateway path", async () => {
    const value = await fixture(); await processPodcastAudioGenerationRun(value.requested.run.id, { provider: value.provider(), storage }); const first = { calls: value.calls(), revisions: await prisma.podcastAudioRevision.count({ where: { audioGenerationRunId: value.requested.run.id } }) }; await processPodcastAudioGenerationRun(value.requested.run.id, { provider: value.provider(), storage }); expect({ calls: value.calls(), revisions: await prisma.podcastAudioRevision.count({ where: { audioGenerationRunId: value.requested.run.id } }), status: (await prisma.audioGenerationRun.findUniqueOrThrow({ where: { id: value.requested.run.id } })).status }).toEqual({ ...first, status: "SUCCEEDED" });
  });
  it("rejects a meaningful voice-version change for an existing Gateway operation without resynthesis", async () => {
    const value = await fixture(), inner = value.provider(), crashing = { identity: inner.identity, capabilities: inner.capabilities, synthesize: async (input: Parameters<typeof inner.synthesize>[0]) => { await inner.synthesize(input); throw new Error("CRASH_AFTER_SPEECH_RECEIPT"); }, consumeSpeechResult: inner.consumeSpeechResult.bind(inner), verifyConsumedSpeechResult: inner.verifyConsumedSpeechResult.bind(inner) }; await expect(processPodcastAudioGenerationRun(value.requested.run.id, { provider: crashing, storage })).rejects.toThrow("CRASH_AFTER_SPEECH_RECEIPT"); const mapping = await prisma.audioGenerationHostVoice.findFirstOrThrow({ where: { audioGenerationRunId: value.requested.run.id }, orderBy: { host: { ordinal: "asc" } } }); await prisma.podcastVoiceProfile.update({ where: { id: mapping.voiceProfileId }, data: { voiceVersion: "changed" } }); await expect(processPodcastAudioGenerationRun(value.requested.run.id, { provider: value.provider(), storage })).rejects.toMatchObject({ code: "IDEMPOTENCY_CONFLICT" }); expect(value.calls()).toBe(1);
  });
  it("keeps Script A pinned when CurrentPodcastScript moves to B during receipt recovery", async () => {
    const value = await fixture(), inner = value.provider(), crashing = { identity: inner.identity, capabilities: inner.capabilities, synthesize: async (input: Parameters<typeof inner.synthesize>[0]) => { await inner.synthesize(input); throw new Error("CRASH_AFTER_SPEECH_RECEIPT"); }, consumeSpeechResult: inner.consumeSpeechResult.bind(inner), verifyConsumedSpeechResult: inner.verifyConsumedSpeechResult.bind(inner) }; await expect(processPodcastAudioGenerationRun(value.requested.run.id, { provider: crashing, storage })).rejects.toThrow("CRASH_AFTER_SPEECH_RECEIPT"); const b = await prisma.podcastScriptRevision.create({ data: { workspaceId: value.workspace.id, episodeId: value.episode.id, revisionNumber: 2, source: "USER_EDIT", status: "FINAL", estimatedDurationSeconds: 1, scriptSnapshot: { utterances: [{ id: "b", segmentId: "b", speakerHostId: "other", text: "B_ONLY_MARKER", utteranceType: "STATEMENT" }] } } }); await prisma.currentPodcastScript.update({ where: { episodeId: value.episode.id }, data: { revisionId: b.id } }); await processPodcastAudioGenerationRun(value.requested.run.id, { provider: value.provider(), storage }); const plans = await prisma.utteranceSpeechPlan.findMany({ where: { audioGenerationRunId: value.requested.run.id } }); expect([value.calls(), plans.every(plan => !plan.spokenText.includes("B_ONLY_MARKER")), (await prisma.podcastAudioRevision.findFirstOrThrow({ where: { audioGenerationRunId: value.requested.run.id } })).scriptRevisionId]).toEqual([1, true, value.script.id]);
  });
  it("preserves CurrentPodcastAudio when a distinct Gateway regeneration fails", async () => {
    const value = await fixture(); await processPodcastAudioGenerationRun(value.requested.run.id, { provider: value.provider(), storage }); const current = await prisma.currentPodcastAudio.findUniqueOrThrow({ where: { episodeId: value.episode.id } }), config = await createEpisodeAudioConfig(value.context, { episodeId: value.episode.id, outputFormat: "wav", sampleRate: 8_000, channels: 1, defaultPauseMs: 777 }), mappings = await prisma.audioGenerationHostVoice.findMany({ where: { audioGenerationRunId: value.requested.run.id } }), retry = await requestPodcastAudioGeneration(value.context, { episodeId: value.episode.id, audioConfigId: config.id, provider: "openai", model: "gpt-4o-mini-tts", modelVersion: "v1", pipelineVersion: "failed-regeneration", speechPreparationVersion: "v1", assemblyVersion: "v1", normalizationVersion: "v1", hostVoiceProfileIds: Object.fromEntries(mappings.map(item => [item.hostId, item.voiceProfileId])) }), stable = value.provider(), failing = { identity: stable.identity, capabilities: stable.capabilities, synthesize: async () => { throw new Error("GATEWAY_SYNTHESIS_FAILURE"); }, consumeSpeechResult: stable.consumeSpeechResult.bind(stable), verifyConsumedSpeechResult: stable.verifyConsumedSpeechResult.bind(stable) }; await expect(processPodcastAudioGenerationRun(retry.run.id, { provider: failing, storage })).rejects.toThrow("GATEWAY_SYNTHESIS_FAILURE"); expect((await prisma.currentPodcastAudio.findUniqueOrThrow({ where: { episodeId: value.episode.id } })).revisionId).toBe(current.revisionId);
  });
  it("rejects a stale owner after B reclaims the run while preserving one durable remote result", async () => {
    const value = await fixture(); let entered!: () => void, release!: () => void; const enteredPromise = new Promise<void>(resolve => entered = resolve), releasePromise = new Promise<void>(resolve => release = resolve); const stale = processPodcastAudioGenerationRun(value.requested.run.id, { provider: value.provider(), storage, faultInjector: async point => { if (point === "after-speech-upload-before-destination") { entered(); await releasePromise; } } }); await enteredPromise; await prisma.$executeRaw`UPDATE "AudioGenerationRun" SET "executionLeaseUntil"=NOW()-INTERVAL '1 second' WHERE "id"=${value.requested.run.id}`; await processPodcastAudioGenerationRun(value.requested.run.id, { provider: value.provider(), storage }); release(); await expect(stale).rejects.toThrow("AUDIO_GENERATION_OWNERSHIP_LOST"); const [run, receipt] = await Promise.all([prisma.audioGenerationRun.findUniqueOrThrow({ where: { id: value.requested.run.id } }), prisma.providerSpeechResult.findFirstOrThrow({ where: { workspaceId: value.workspace.id } })]); expect([value.calls(), run.status, receipt.consumedAt !== null, await prisma.utteranceSpeechChunk.count({ where: { audioGenerationRunId: value.requested.run.id, status: "SUCCEEDED" } })]).toEqual([1, "SUCCEEDED", true, 1]);
  });
});
