import { describe, expect, it } from "vitest";
import { buildPodcastSystemInstruction, evaluatePodcastScriptData, evaluateNaturalness, pauseFor, prepareSpokenText } from "../src/index.js";

const good = [{ speakerHostId: "a", text: "环境先改变注意力，这会重排选择的条件。", utteranceType: "STATEMENT", substantive: true, evidenceCount: 1, evidenceMemoryIds: ["m1"] }, { speakerHostId: "b", text: "等等，这会不会把选择说得太被动？", utteranceType: "CHALLENGE", substantive: false }, { speakerHostId: "a", text: "不是免责；它要求我们看见可以重新设计的条件。", utteranceType: "CLARIFICATION", substantive: true, evidenceCount: 1, evidenceMemoryIds: ["m2"] }, { speakerHostId: "b", text: "这就接回开头那个自律的误解了。", utteranceType: "CALLBACK", substantive: false }];
const bad = Array.from({ length: 10 }, (_, i) => ({ speakerHostId: i % 2 ? "b" : "a", text: i % 2 ? "你说得对，这非常重要。" : "首先我们来看这个关键点。", utteranceType: "STATEMENT", substantive: false }));
describe("Phase 15 quality", () => {
  it("separates grounded dialogue from AI ping-pong", () => { const a = evaluatePodcastScriptData(good, { style: { hostCount: 2 } }), b = evaluatePodcastScriptData(bad, { style: { hostCount: 2 } }); expect(a.groundingScore).toBe(100); expect(a.naturalnessScore).toBeGreaterThan(b.naturalnessScore + 20); expect(b.metrics.strictAlternationRate).toBeGreaterThan(.8); expect(b.warnings).toContain("GENERIC_AGREEMENT_DENSITY"); });
  it("is style-aware and preserves prompt and audio contracts", () => { expect(evaluateNaturalness([{ speakerHostId: "a", text: "首先，边界需要说清。", utteranceType: "STATEMENT" }], { hostCount: 1, formality: 9 }).hostDifferentiationScore).toBe(100); for (const stage of ["EPISODE_PLANNING", "NARRATIVE_DESIGN", "SEGMENT_OUTLINE", "SEGMENT_DRAFTING", "HUMANIZATION"] as const) expect(buildPodcastSystemInstruction(stage, { hosts: [] })).toMatch(/untrusted|Never fabricate/i); expect(buildPodcastSystemInstruction("SEGMENT_DRAFTING", { hosts: [] })).toMatch(/asymmetry|grounding/i); expect(buildPodcastSystemInstruction("HUMANIZATION")).toMatch(/Do not change substantive claims/); expect(prepareSpokenText("[说明](https://x.test) <break/> AI").spokenText).toContain("A I"); const c = { defaultPauseMs: 420, shortReactionPauseMs: 120, interruptionPauseMs: 80 }; expect(pauseFor("REACTION", c).after).toBeLessThan(pauseFor("QUESTION", c).after); });
});
