import { describe, expect, it } from "vitest";
import { FfmpegAudioProcessor } from "../src/audio-processor.js";
import { MAX_SPEECH_CHUNK_CHARS, pauseFor, prepareSpokenText, splitSpeechChunks } from "../src/audio.js";

function wav(): Uint8Array { const samples = 4_000, bytes = new Uint8Array(44 + samples * 2), view = new DataView(bytes.buffer); bytes.set(new TextEncoder().encode("RIFF")); view.setUint32(4, bytes.length - 8, true); bytes.set(new TextEncoder().encode("WAVEfmt "), 8); view.setUint32(16, 16, true); view.setUint16(20, 1, true); view.setUint16(22, 1, true); view.setUint32(24, 8_000, true); view.setUint32(28, 16_000, true); view.setUint16(32, 2, true); view.setUint16(34, 16, true); bytes.set(new TextEncoder().encode("data"), 36); view.setUint32(40, samples * 2, true); for (let i = 0; i < samples; i++) view.setInt16(44 + i * 2, i < 300 || i > samples - 300 ? 0 : 2_000, true); return bytes; }

describe("Phase 4 deterministic speech and media boundaries", () => {
  it("bounds chunks without splitting Unicode code points or changing text order", () => { const text = `${"中文 AI GPT-5 😀 API。".repeat(100)}结束`; const chunks = splitSpeechChunks(text); expect(chunks.length).toBeGreaterThan(1); expect(chunks.join("")).toBe(text); expect(chunks.every(chunk => Array.from(chunk).length <= MAX_SPEECH_CHUNK_CHARS)).toBe(true); expect(prepareSpokenText("<break/> AI GPT-5").spokenText).toContain("A I"); });
  it("keeps reaction and interruption pauses shorter than normal handoffs", () => { const config = { defaultPauseMs: 420, shortReactionPauseMs: 120, interruptionPauseMs: 80 }; expect(pauseFor("REACTION", config).after).toBeLessThan(pauseFor("STATEMENT", config).after); expect(pauseFor("CHALLENGE", config).before).toBeLessThan(pauseFor("STATEMENT", config).before); });
  it("uses the real FFmpeg process to resample, mix channels, trim, and normalize", async () => { const output = await new FfmpegAudioProcessor().canonicalize(wav(), { sampleRate: 16_000, channels: 2, targetLufs: -16, truePeakLimitDb: -1, normalizeLoudness: true, trimLeadingSilence: true, trimTrailingSilence: true }); const view = new DataView(output.bytes.buffer, output.bytes.byteOffset, output.bytes.byteLength); expect(new TextDecoder().decode(output.bytes.slice(0, 4))).toBe("RIFF"); expect(view.getUint16(22, true)).toBe(2); expect(view.getUint32(24, true)).toBe(16_000); expect(output.bytes.length).toBeGreaterThan(44); });
});
