/* eslint-disable @typescript-eslint/no-explicit-any */
import { afterEach, describe, expect, it } from "vitest";
import { prisma } from "@ai-cognitive/db";
import { ProviderGatewayRepository, parseKeyring } from "@ai-cognitive/provider-gateway";
import { buildBookContextForIntelligence, materializeChunkSet, processBookAnalysisRun, requestBookAnalysis, type AnalysisProvider, type AnalysisRequest } from "@ai-cognitive/book-intelligence";
import { processPodcastGenerationRun } from "../src/index.js";
import { createPodcastProductionGatewayRuntime } from "../../../apps/worker/src/provider-gateway-runtime.js";
import { fixture } from "./phase3-durability.integration.test.js";

const keyring = JSON.stringify({ activeVersion: "v1", keys: { v1: Buffer.alloc(32, 13).toString("base64") } });
const manifest = JSON.stringify({ providers: [{ providerKey: "deterministic-test", displayName: "A", protocol: "TEST", adapterVersion: "test", models: [{ modelId: "deterministic-vector-v1", families: ["EMBEDDING"], confidence: "VERIFIED", embeddingDimensions: 4, embeddingPurposes: ["QUERY"] }] }, { providerKey: "fixture-b", displayName: "B", protocol: "TEST", adapterVersion: "test", models: [{ modelId: "fixture-b-model", families: ["EMBEDDING"], confidence: "VERIFIED", embeddingDimensions: 4, embeddingPurposes: ["QUERY"] }] }] });
const controls = { circuit: { admit: async () => undefined, recordSuccess: async () => undefined, recordRetryableFailure: async () => undefined }, rate: { admit: async () => undefined }, concurrency: { acquire: async (key: string) => ({ key, token: "test" }), release: async () => true }, validateEndpoint: async () => undefined };
type Data = Awaited<ReturnType<typeof fixture>>;
class Analysis implements AnalysisProvider { async generateStructured(request: AnalysisRequest) { return request.stage === "CHUNK" ? { summary: `chunk ${request.content}`, memory: [{ type: "CLAIM" as const, content: request.content }] } : { summary: `book ${request.content}`, memory: [{ type: "SUMMARY" as const, content: "bounded secondary source" }] }; } }
async function production(data: Data, invalid?: "dimensions" | "count" | "nonfinite") {
  const store = new ProviderGatewayRepository(prisma, parseKeyring(keyring)!); const connectionA = await prisma.providerConnection.findFirstOrThrow({ where: { workspaceId: data.workspace.id, providerKey: "deterministic-test" } }); await store.rotateCredential({ workspaceId: data.workspace.id, userId: data.user.id }, connectionA.id, "a-secret");
  const calls = { a: 0, b: 0 };
  const runtime = createPodcastProductionGatewayRuntime({ ...process.env, PROVIDER_GATEWAY_KEYRING: keyring, PROVIDER_GATEWAY_MODEL_MANIFEST: manifest }, { ...controls, adapterResolver: () => ({ execute: async ({ snapshot, request }: any) => { if (snapshot.providerKey === "fixture-b") calls.b++; else calls.a++; const vectors = invalid === "count" ? [] : invalid === "nonfinite" ? [[NaN, 0, 0, 0]] : await data.retrievalEmbeddings.embed({ texts: [...request.embedding.texts] }); return { response: { vectors, dimensions: invalid === "dimensions" ? 3 : 4 }, usage: { embeddingInputTokens: request.embedding.texts.length } }; } }) });
  return { store, runtime, calls };
}
async function receiptCounts(workspaceId: string) { return Promise.all([prisma.providerInvocation.count({ where: { workspaceId } }), prisma.providerInvocationAttempt.count({ where: { workspaceId, status: "SUCCEEDED" } }), prisma.providerUsageEvent.count({ where: { workspaceId } }), prisma.providerEmbeddingResult.count({ where: { workspaceId } })]); }
async function addPinnedSource(data: Data) {
  const suffix = crypto.randomUUID(), source = await prisma.source.create({ data: { workspaceId: data.workspace.id, kind: "FILE", displayName: `second-${suffix}.md` } }), blob = await prisma.sourceBlob.create({ data: { workspaceId: data.workspace.id, sha256: `second-${suffix}`, sizeBytes: 1, mediaType: "text/markdown", storageKey: `phase8c/${suffix}` } }), document = await prisma.sourceDocument.create({ data: { workspaceId: data.workspace.id, sourceId: source.id, sourceBlobId: blob.id, version: 1, sha256: `second-${suffix}`, sizeBytes: 1, mediaType: "text/markdown", storageKey: blob.storageKey } }), job = await prisma.job.create({ data: { workspaceId: data.workspace.id, type: "source.ingest", payload: {}, idempotencyKey: `second-ingest:${suffix}` } }), ingestion = await prisma.ingestionRun.create({ data: { workspaceId: data.workspace.id, sourceDocumentId: document.id, jobId: job.id, parserVersion: "test", normalizationVersion: "test" } }), extraction = await prisma.documentExtraction.create({ data: { workspaceId: data.workspace.id, sourceDocumentId: document.id, ingestionRunId: ingestion.id, status: "SUCCEEDED", parserName: "test", parserVersion: "test", normalizationVersion: "test" } });
  await prisma.sourceBlock.createMany({ data: ["A second independently analyzed source.", "It preserves vector-space acceptance.", "Its bounded evidence remains separate."].map((text, ordinal) => ({ extractionId: extraction.id, ordinal, kind: "PARAGRAPH", text, contentHash: `${suffix}-${ordinal}` })) }); await prisma.currentDocumentExtraction.create({ data: { workspaceId: data.workspace.id, sourceDocumentId: document.id, extractionId: extraction.id } }); await materializeChunkSet({ workspaceId: data.workspace.id, sourceDocumentId: document.id, configuration: { targetSize: 45, hardMax: 70 } });
  const requested = await requestBookAnalysis({ workspaceId: data.workspace.id, sourceDocumentId: document.id, pipelineVersion: `phase8c-${suffix}`, promptVersion: "phase8c", provider: "analysis-test", model: "analysis-test", modelVersion: "1" }); await processBookAnalysisRun(requested.run.id, { analysisProvider: new Analysis(), embeddingProvider: data.retrievalEmbeddings, embeddingGateway: data.bookEmbeddingGateway.embeddingGateway });
  const run = await prisma.bookAnalysisRun.findUniqueOrThrow({ where: { id: requested.run.id } }); await prisma.podcastGenerationSource.create({ data: { podcastGenerationRunId: data.requested.run.id, workspaceId: data.workspace.id, episodeId: data.episode.id, sourceDocumentId: document.id, extractionId: run.extractionId, chunkSetId: run.chunkSetId, analysisRunId: run.id } }); return run;
}
async function resetForRetry(runId: string) { await prisma.podcastGenerationRun.update({ where: { id: runId }, data: { status: "QUEUED", executionClaimToken: null, executionClaimedAt: null, executionLeaseUntil: null, errorCode: null } }); }

describe("Phase 8C Checkpoint 4B Podcast retrieval Gateway", () => {
  afterEach(async () => undefined);
  it("persists, replays, pins A→B, and rejects new incompatible or semantically changed queries", async () => {
    const data = await fixture(), value = await production(data), run = data.requested.run;
    const providerA = await value.runtime.createEmbeddingProviderForRun({ workspaceId: data.workspace.id, podcastGenerationRunId: run.id });
    const first = await providerA.embed({ texts: ["Q1"], model: providerA.identity.model, correlationId: "trace-1", operationKey: "PLANNING" });
    expect(value.calls).toEqual({ a: 1, b: 0 }); expect(await receiptCounts(data.workspace.id)).toEqual([2, 2, 2, 2]);
    const query = await prisma.providerInvocation.findFirstOrThrow({ where: { workspaceId: data.workspace.id, idempotencyKey: `podcast-retrieval-query:${run.id}:PLANNING` }, include: { embeddingResult: true } }); expect(query.embeddingResult).toMatchObject({ consumedAt: null, purgedAt: null, ciphertext: expect.any(String), iv: expect.any(String), authTag: expect.any(String), keyVersion: expect.any(String) });
    const connectionB = await value.store.createConnection({ workspaceId: data.workspace.id, userId: data.user.id }, { providerKey: "fixture-b", protocol: "TEST", displayName: "b" }); await value.store.rotateCredential({ workspaceId: data.workspace.id, userId: data.user.id }, connectionB.id, "b-secret"); await value.store.setRoute({ workspaceId: data.workspace.id, userId: data.user.id }, { routeSlot: "EMBEDDING", connectionId: connectionB.id, modelId: "fixture-b-model" });
    const replay = await (await value.runtime.createEmbeddingProviderForRun({ workspaceId: data.workspace.id, podcastGenerationRunId: run.id })).embed({ texts: ["Q1"], model: providerA.identity.model, correlationId: "trace-2", operationKey: "PLANNING" }); expect(replay).toEqual(first); expect(value.calls).toEqual({ a: 1, b: 0 }); expect(await receiptCounts(data.workspace.id)).toEqual([2, 2, 2, 2]);
    const providerB = await value.runtime.createEmbeddingProviderForRun({ workspaceId: data.workspace.id, podcastGenerationRunId: run.id }); await expect(providerB.embed({ texts: ["Q2"], model: providerB.identity.model, correlationId: "trace-3", operationKey: "SEGMENT_CONTEXT:one" })).rejects.toThrow("PODCAST_RETRIEVAL_EMBEDDING_ROUTE_IDENTITY_GAP"); await expect(providerB.embed({ texts: ["Q2"], model: providerB.identity.model, correlationId: "trace-4", operationKey: "PLANNING" })).rejects.toMatchObject({ code: "IDEMPOTENCY_CONFLICT" }); expect(value.calls).toEqual({ a: 1, b: 0 });
    await prisma.podcastGenerationRun.update({ where: { id: run.id }, data: { pipelineVersion: "changed-semantic-version" } }); const changed = await value.runtime.createEmbeddingProviderForRun({ workspaceId: data.workspace.id, podcastGenerationRunId: run.id }); await expect(changed.embed({ texts: ["Q1"], model: changed.identity.model, correlationId: "trace-5", operationKey: "PLANNING" })).rejects.toMatchObject({ code: "IDEMPOTENCY_CONFLICT" }); expect(value.calls).toEqual({ a: 1, b: 0 });
    await value.runtime.close();
  }, 60_000);

  it.each([
    ["actor-null", async (data: Data) => prisma.job.update({ where: { id: data.requested.run.jobId }, data: { userId: null } }), "PODCAST_DURABLE_PRINCIPAL_MISSING"],
    ["non-member", async (data: Data) => prisma.workspaceMember.delete({ where: { workspaceId_userId: { workspaceId: data.workspace.id, userId: data.user.id } } }), "PODCAST_DURABLE_PRINCIPAL_MISSING"],
    ["workspace-mismatch", async (data: Data) => prisma.job.update({ where: { id: data.requested.run.jobId }, data: { workspaceId: null } }), "PODCAST_DURABLE_PRINCIPAL_WORKSPACE_MISMATCH"],
  ] as const)("fails closed for production durable principal %s before an embedding request", async (_name, mutate, error) => {
    const data = await fixture(), value = await production(data); await mutate(data);
    await expect(value.runtime.createEmbeddingProviderForRun({ workspaceId: data.workspace.id, podcastGenerationRunId: data.requested.run.id })).rejects.toThrow(error); expect(value.calls).toEqual({ a: 0, b: 0 }); await value.runtime.close();
  });

  it("fails closed when the pinned source has no consumed Book embedding receipt", async () => {
    const data = await fixture(), value = await production(data), source = await prisma.podcastGenerationSource.findFirstOrThrow({ where: { podcastGenerationRunId: data.requested.run.id } }); const invocation = await prisma.providerInvocation.findUniqueOrThrow({ where: { workspaceId_idempotencyKey: { workspaceId: data.workspace.id, idempotencyKey: `book-analysis-embeddings:${source.analysisRunId}` } } }); await prisma.providerEmbeddingResult.delete({ where: { invocationId: invocation.id } });
    await expect(value.runtime.createEmbeddingProviderForRun({ workspaceId: data.workspace.id, podcastGenerationRunId: data.requested.run.id })).rejects.toThrow("PODCAST_RETRIEVAL_EMBEDDING_IDENTITY_MISSING"); expect(value.calls).toEqual({ a: 0, b: 0 }); await value.runtime.close();
  });

  it.each(["dimensions", "count", "nonfinite"] as const)("rejects an invalid Gateway query response: %s", async invalid => {
    const data = await fixture(), value = await production(data, invalid), provider = await value.runtime.createEmbeddingProviderForRun({ workspaceId: data.workspace.id, podcastGenerationRunId: data.requested.run.id }); await expect(provider.embed({ texts: ["invalid"], model: provider.identity.model, correlationId: invalid, operationKey: "PLANNING" })).rejects.toBeDefined(); expect(value.calls.a).toBe(1); await value.runtime.close();
  });

  it("keeps Book retrieval ranking, selection, budget, and lineage identical to the direct provider", async () => {
    const data = await fixture(), value = await production(data), source = await prisma.podcastGenerationSource.findFirstOrThrow({ where: { podcastGenerationRunId: data.requested.run.id } }), gateway = await value.runtime.createEmbeddingProviderForRun({ workspaceId: data.workspace.id, podcastGenerationRunId: data.requested.run.id }); const common = { workspaceId: data.workspace.id, sourceDocumentId: source.sourceDocumentId, extractionId: source.extractionId, chunkSetId: source.chunkSetId, analysisRunId: source.analysisRunId, task: "bounded retrieval parity", tokenBudget: 800 };
    const direct = await buildBookContextForIntelligence({ ...common, embeddingProvider: data.retrievalEmbeddings }); const routed = await buildBookContextForIntelligence({ ...common, embeddingProvider: gateway, operationKey: "PLANNING" });
    expect(routed.items.map(item => item.memoryItemId)).toEqual(direct.items.map(item => item.memoryItemId)); expect(routed.items.map(item => item.score)).toEqual(direct.items.map(item => item.score)); expect(routed.estimatedTokens).toBe(direct.estimatedTokens); expect(routed.provenance).toEqual(direct.provenance); await value.runtime.close();
  });

  it("reuses the durable Gateway query receipt after a real Podcast crash before paid planning text", async () => {
    const data = await fixture(), value = await production(data), run = data.requested.run;
    await prisma.podcastGenerationRun.update({ where: { id: run.id }, data: { provider: "fixture", model: "fixture-model", modelVersion: null, modelVersionKey: "" } });
    const text = await value.store.createConnection({ workspaceId: data.workspace.id, userId: data.user.id }, { providerKey: "fixture", protocol: "TEST", displayName: "fixture" }); await value.store.rotateCredential({ workspaceId: data.workspace.id, userId: data.user.id }, text.id, "fixture-secret"); await value.store.setRoute({ workspaceId: data.workspace.id, userId: data.user.id }, { routeSlot: "PODCAST_SCRIPT", connectionId: text.id, modelId: "fixture-model" });
    let textCalls = 0, planningQueries = 0; const runtime = createPodcastProductionGatewayRuntime({ ...process.env, PROVIDER_GATEWAY_KEYRING: keyring, PROVIDER_GATEWAY_MODEL_MANIFEST: JSON.stringify({ providers: [...JSON.parse(manifest).providers, { providerKey: "fixture", displayName: "Fixture", protocol: "TEST", adapterVersion: "test", models: [{ modelId: "fixture-model", families: ["TEXT_GENERATION"], confidence: "VERIFIED", structuredOutput: "STRICT_JSON_SCHEMA" }] }] }) }, { ...controls, adapterResolver: () => ({ execute: async ({ request }: any) => { if (request.embedding) { if (request.idempotencyKey.endsWith(":PLANNING")) planningQueries++; return { response: { vectors: await data.retrievalEmbeddings.embed({ texts: [...request.embedding.texts] }), dimensions: 4 }, usage: { embeddingInputTokens: request.embedding.texts.length } }; } textCalls++; const input = JSON.parse(request.text.messages[0].content), stage = input.metadata.stage, memory = input.context?.find((item: any) => item.sourceBlockEvidenceSpans?.length)?.memoryItemId ?? input.context?.[0]?.memoryItemId ?? input.availableMemoryIds?.[0], hosts = input.hosts; const structured = stage === "EPISODE_PLANNING" ? { centralQuestion: "q", listenerStartingPoint: "s", listenerTakeaway: "t", coreThesis: "c", tensions: ["x"], surprisingIdeas: ["x"], misconceptions: ["x"], keyConcepts: ["x"], candidateStories: [], candidateExamples: ["x"], openQuestions: ["x"] } : stage === "NARRATIVE_DESIGN" ? { arcType: "arc", intellectualProgression: ["a", "b", "c"], openingMove: "a", closingMove: "c" } : stage === "SEGMENT_OUTLINE" ? { segments: [{ ordinal: 1, purpose: "p", internalLabel: "l", targetDurationSeconds: 30, narrativeFunction: "n", keyQuestions: ["q"], requiredMemoryIds: [memory], optionalMemoryIds: [] }] } : stage === "SEGMENT_DRAFTING" ? { utterances: [{ ordinal: 1, speakerHostId: hosts[0].id, text: "Evidence persists.", utteranceType: "STATEMENT", substantive: true, isDirectQuote: false, evidence: [{ memoryItemId: memory }] }, { ordinal: 2, speakerHostId: hosts[1].id, text: "Why?", utteranceType: "QUESTION", substantive: false, isDirectQuote: false, evidence: [] }] } : { utterances: input.dialogue.utterances.map((item: any) => ({ ordinal: item.ordinal, text: item.text })) }; return { response: { type: "STRUCTURED", structured }, usage: { inputTokens: 1, outputTokens: 1 } }; } }) });
    await expect(processPodcastGenerationRun(run.id, { providerForRun: runtime.createProviderForRun, embeddingProviderForRun: runtime.createEmbeddingProviderForRun, faultInjector: point => { if (point === "afterPlanningRetrieval") throw new Error("CRASH_AFTER_QUERY"); } })).rejects.toThrow("CRASH_AFTER_QUERY");
    const query = await prisma.providerInvocation.findFirstOrThrow({ where: { workspaceId: data.workspace.id, idempotencyKey: `podcast-retrieval-query:${run.id}:PLANNING` }, include: { embeddingResult: true } }); expect([planningQueries, textCalls, await prisma.providerInvocationAttempt.count({ where: { invocationId: query.id, status: "SUCCEEDED" } }), await prisma.providerUsageEvent.count({ where: { invocationId: query.id } })]).toEqual([1, 0, 1, 1]); expect(query.embeddingResult).toMatchObject({ consumedAt: null, purgedAt: null, ciphertext: expect.any(String), iv: expect.any(String), authTag: expect.any(String), keyVersion: expect.any(String) });
    await resetForRetry(run.id); await processPodcastGenerationRun(run.id, { providerForRun: runtime.createProviderForRun, embeddingProviderForRun: runtime.createEmbeddingProviderForRun }); const replay = await prisma.providerInvocation.findUniqueOrThrow({ where: { id: query.id }, include: { embeddingResult: true } }); expect([replay.id === query.id, replay.embeddingResult?.id === query.embeddingResult?.id, planningQueries, textCalls > 0, await prisma.providerInvocationAttempt.count({ where: { invocationId: query.id, status: "SUCCEEDED" } }), await prisma.providerUsageEvent.count({ where: { invocationId: query.id } })]).toEqual([true, true, 1, true, 1, 1]); await runtime.close(); await value.runtime.close();
  }, 60_000);

  it("accepts every pinned source only when their authoritative identities share one vector space", async () => {
    const data = await fixture(), second = await addPinnedSource(data), value = await production(data), provider = await value.runtime.createEmbeddingProviderForRun({ workspaceId: data.workspace.id, podcastGenerationRunId: data.requested.run.id }); expect(await prisma.podcastGenerationSource.count({ where: { podcastGenerationRunId: data.requested.run.id } })).toBe(2); expect(provider.identity).toMatchObject({ provider: "deterministic-test", model: "deterministic-vector-v1", embeddingVersion: "gateway", dimensions: 4 }); expect(value.calls).toEqual({ a: 0, b: 0 }); const invocation = await prisma.providerInvocation.findUniqueOrThrow({ where: { workspaceId_idempotencyKey: { workspaceId: data.workspace.id, idempotencyKey: `book-analysis-embeddings:${second.id}` } }, include: { snapshot: true } }); await prisma.providerEmbeddingResult.update({ where: { invocationId: invocation.id }, data: { dimensions: 3 } }); await prisma.providerExecutionSnapshot.update({ where: { id: invocation.snapshotId }, data: { capability: { ...(invocation.snapshot.capability as Record<string, unknown>), embeddingDimensions: 3 } } }); await expect(value.runtime.createEmbeddingProviderForRun({ workspaceId: data.workspace.id, podcastGenerationRunId: data.requested.run.id })).rejects.toThrow("PODCAST_RETRIEVAL_SOURCE_EMBEDDING_INCOMPATIBLE"); expect(value.calls).toEqual({ a: 0, b: 0 }); await value.runtime.close();
  });
});
