import { createHash, randomUUID } from "node:crypto";
import { afterEach, describe, expect, it } from "vitest";
import { prisma } from "@ai-cognitive/db";
import { DeterministicProviderHttpTransport, ProviderExecutionRepository, ProviderGatewayRepository, ProviderRegistry, WorkspaceMembershipExecutionAuthorizer, createProductionProviderGateway, createProviderAdapterResolver, testCipher } from "@ai-cognitive/provider-gateway";

const owned: Array<{ workspaceId: string; userId: string }> = [];
const stages = ["EPISODE_PLANNING", "NARRATIVE_DESIGN", "SEGMENT_OUTLINE", "SEGMENT_DRAFTING", "HUMANIZATION"] as const;

async function fixture() {
  const workspaceId = randomUUID(), userId = randomUUID(), cipher = testCipher(), store = new ProviderGatewayRepository(prisma, cipher), transport = new DeterministicProviderHttpTransport(() => ({ status: 200, headers: {}, body: JSON.stringify({ choices: [{ message: { content: JSON.stringify({ ok: true }) }, finish_reason: "stop" }], usage: { prompt_tokens: 1, completion_tokens: 1 } }) }));
  owned.push({ workspaceId, userId }); await prisma.workspace.create({ data: { id: workspaceId, name: workspaceId } }); await prisma.user.create({ data: { id: userId, email: `${userId}@test.invalid` } }); await prisma.workspaceMember.create({ data: { workspaceId, userId, role: "OWNER" } });
  const connection = await store.createConnection({ workspaceId, userId }, { providerKey: "deepseek", protocol: "OPENAI_COMPATIBLE", displayName: "fixture" }); await store.rotateCredential({ workspaceId, userId }, connection.id, "fixture-secret"); await store.setRoute({ workspaceId, userId }, { routeSlot: "PODCAST_SCRIPT", connectionId: connection.id, modelId: "deepseek-chat" });
  const registry = new ProviderRegistry(); registry.register({ providerKey: "deepseek", displayName: "fixture", protocol: "OPENAI_COMPATIBLE", adapterVersion: "test", models: [{ modelId: "deepseek-chat", families: ["TEXT_GENERATION"], confidence: "VERIFIED", structuredOutput: "JSON_MODE" }] });
  const repository = new ProviderExecutionRepository(prisma, cipher), authorizer = new WorkspaceMembershipExecutionAuthorizer(prisma);
  const gateway = createProductionProviderGateway(registry, { resolveWorkspaceRoute: input => store.resolveWorkspaceRoute(input) }, { resolve: async () => undefined }, createProviderAdapterResolver(transport), { authorize: (principal, request) => authorizer.authorizeExecution(principal, request.workspaceId), assertRouteUsable: async () => undefined, validateEndpoint: async () => undefined, assertBudget: () => undefined, repository, rate: { admit: async () => undefined }, concurrency: { acquire: async () => ({ key: "test", token: "test" }), release: async () => true }, circuit: { admit: async () => undefined, recordSuccess: async () => undefined, recordRetryableFailure: async () => undefined } });
  return { workspaceId, userId, repository, gateway, transport };
}
afterEach(async () => { for (const value of owned.splice(0)) { await prisma.providerTextResult.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.providerUsageEvent.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.providerInvocationAttempt.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.providerInvocation.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.providerExecutionSnapshot.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.providerRouteBinding.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.providerCredentialVersion.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.providerConnection.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.workspaceMember.deleteMany({ where: { workspaceId: value.workspaceId } }); await prisma.workspace.delete({ where: { id: value.workspaceId } }); await prisma.user.delete({ where: { id: value.userId } }); } });

describe("Phase 8C Checkpoint 4A real ProviderTextResult durability", () => {
  it.each(stages)("keeps %s encrypted through a materializer rollback and replays without repaying", async stage => {
    const value = await fixture(), key = `podcast-text:run:${stage}`, request = { workspaceId: value.workspaceId, routeSlot: "PODCAST_SCRIPT" as const, correlationId: stage, idempotencyKey: key, inputHash: createHash("sha256").update(stage).digest("hex"), capability: { family: "TEXT_GENERATION" as const, structuredOutput: "JSON_MODE" as const }, text: { messages: [{ role: "user" as const, content: stage }], structuredOutput: { mode: "JSON_MODE" as const } } };
    const first = await value.gateway.execute(request, { userId: value.userId }); if (first.status !== "SUCCEEDED" || !first.invocationId || !first.snapshot) throw new Error("fixture");
    const consumer = { workspaceId: value.workspaceId, invocationId: first.invocationId, snapshotId: first.snapshot.id, consumerKind: `PODCAST_${stage}`, consumerKey: "run", consumerFingerprint: "a".repeat(64) };
    expect(await prisma.providerTextResult.findUniqueOrThrow({ where: { invocationId: first.invocationId } })).toMatchObject({ consumedAt: null, purgedAt: null, ciphertext: expect.any(String), iv: expect.any(String), authTag: expect.any(String), keyVersion: expect.any(String) });
    await expect(value.repository.consumeTextResult(consumer, async ({ tx }) => { await tx.workspace.update({ where: { id: value.workspaceId }, data: { name: "must-rollback" } }); throw new Error("MATERIALIZER_CRASH"); })).rejects.toThrow("MATERIALIZER_CRASH");
    expect(await prisma.providerTextResult.findUniqueOrThrow({ where: { invocationId: first.invocationId } })).toMatchObject({ consumedAt: null, purgedAt: null, ciphertext: expect.any(String) }); expect(value.transport.calls).toHaveLength(1);
    const replay = await value.gateway.execute(request, { userId: value.userId }); expect(replay).toMatchObject({ status: "ALREADY_PROCESSED", invocationId: first.invocationId });
    await value.repository.consumeTextResult(consumer, async ({ tx }) => { await tx.workspace.update({ where: { id: value.workspaceId }, data: { name: `materialized-${stage}` } }); });
    expect(value.transport.calls).toHaveLength(1); expect(await prisma.workspace.findUniqueOrThrow({ where: { id: value.workspaceId } })).toMatchObject({ name: `materialized-${stage}` }); expect(await prisma.providerTextResult.findUniqueOrThrow({ where: { invocationId: first.invocationId } })).toMatchObject({ consumedAt: expect.any(Date), purgedAt: expect.any(Date), ciphertext: null, iv: null, authTag: null, keyVersion: null });
    await expect(Promise.all([prisma.providerInvocation.count({ where: { workspaceId: value.workspaceId } }), prisma.providerInvocationAttempt.count({ where: { workspaceId: value.workspaceId, status: "SUCCEEDED" } }), prisma.providerUsageEvent.count({ where: { workspaceId: value.workspaceId } }), prisma.providerTextResult.count({ where: { workspaceId: value.workspaceId } })])).resolves.toEqual([1, 1, 1, 1]);
  });
});
