/* eslint-disable @typescript-eslint/no-explicit-any */
import { createHash } from "node:crypto";
import { execFile } from "node:child_process";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import { afterAll, afterEach, describe, expect, it } from "vitest";
import { prisma } from "@ai-cognitive/db";
import { DeterministicFakeEmbeddingProvider, materializeChunkSet, processBookAnalysisRun, requestBookAnalysis, type AnalysisProvider } from "@ai-cognitive/book-intelligence";
import { S3CompatibleStorageProvider } from "@ai-cognitive/storage";
import { configureShortVideoStyle, createShortVideoProject, processShortVideoGenerationRun, requestShortVideoGeneration, type ShortVideoProvider, type ShortVideoTtsProvider, type VideoRenderer } from "../src/index.js";

const required = (name: string) => {
  const value = process.env[name];
  if (!value) throw new Error(`MISSING_TEST_ENV:${name}`);
  return value;
};
const storage = new S3CompatibleStorageProvider({ endpoint: required("S3_ENDPOINT"), publicEndpoint: required("S3_PUBLIC_ENDPOINT"), region: required("S3_REGION"), bucket: required("S3_BUCKET"), accessKey: required("S3_ACCESS_KEY"), secretKey: required("S3_SECRET_KEY"), forcePathStyle: process.env.S3_FORCE_PATH_STYLE !== "false" });
const sha = (value: Uint8Array) => createHash("sha256").update(value).digest("hex");
const execute = promisify(execFile);
const workspaces: string[] = [], users: string[] = [];

function wav() { const samples = 20_000, bytes = new Uint8Array(44 + samples * 2), view = new DataView(bytes.buffer); bytes.set(new TextEncoder().encode("RIFF")); view.setUint32(4, bytes.length - 8, true); bytes.set(new TextEncoder().encode("WAVEfmt "), 8); view.setUint32(16, 16, true); view.setUint16(20, 1, true); view.setUint16(22, 1, true); view.setUint32(24, 8000, true); view.setUint32(28, 16000, true); view.setUint16(32, 2, true); view.setUint16(34, 16, true); bytes.set(new TextEncoder().encode("data"), 36); view.setUint32(40, samples * 2, true); for (let i = 0; i < samples; i++) view.setInt16(44 + i * 2, Math.sin(i / 11) * 3000, true); return bytes; }
class Analysis implements AnalysisProvider { constructor(private readonly marker: string) {} async generateStructured(request: any): Promise<any> { if (request.stage !== "CHUNK") return { summary: this.marker, memory: request.stage === "BOOK" ? [{ type: "SUMMARY", content: `${this.marker} grounded memory` }] : undefined }; const block = await prisma.sourceBlock.findFirstOrThrow({ where: { id: { in: request.sourceBlockIds } } }); return { summary: request.content.slice(0, 100), memory: [{ type: "QUOTE", content: request.content.slice(0, 100), evidence: [{ sourceBlockId: block.id, startOffset: 0, endOffset: Math.min(20, block.text.length), quoteText: block.text.slice(0, 20) }] }, { type: "CLAIM", content: `${this.marker} grounded claim` }] }; } }
class Video implements ShortVideoProvider { readonly identity = { provider: "phase5-durability", model: "fixture", modelVersion: "1" }; calls: any[] = []; entered?: () => void; release?: Promise<void>; fail = false; async plan(input: any): Promise<any> { this.calls.push(input); this.entered?.(); await this.release; if (this.fail) throw new Error("PLANNING_PROVIDER_FAILED"); return { centralQuestion: "How does evidence change judgement?", viewerAssumption: "answers arrive quickly", coreInsight: "evidence first", cognitiveShift: "verify before deciding", hook: "Change the question", supportingIdeas: ["evidence"], evidenceStrategy: "grounded", ending: "ask for evidence", targetDurationSeconds: 15, tone: "grounded" }; } async scenes(input: any): Promise<any> { this.calls.push(input); const evidence = input.context[0].evidence[0], types = ["HOOK", "QUESTION", "EVIDENCE", "CONCEPT", "REFRAME", "ENDING"]; return { scenes: types.map((sceneType, i) => ({ ordinal: i + 1, sceneType, targetDurationMs: 2500, narrationText: `Scene ${i + 1} needs grounded evidence.`, visualIntent: "editorial", primaryText: `Evidence ${i + 1}`, secondaryText: "grounded", keywords: ["evidence"], layoutTemplate: ["QUESTION_CARD", "CONTRAST", "EVIDENCE_CARD", "CONCEPT_CARD", "CLAIM_CARD", "ENDING_CARD"][i], motionPreset: "REVEAL", transitionIntent: "FADE", evidence: [evidence] })) }; } }
class Tts implements ShortVideoTtsProvider { readonly identity = { provider: "phase5-wav", model: "fixture", voiceIdentity: "test" }; calls = 0; async synthesize() { this.calls++; return { bytes: wav(), mediaType: "audio/wav", durationMs: 2500 }; } }
const lightweightRenderer: VideoRenderer = { async render(input) { const directory = await mkdtemp(join(tmpdir(), "phase5-durable-render-")), path = join(directory, "render.mp4"); await execute("ffmpeg", ["-y", "-f", "lavfi", "-i", `color=c=#0f172a:s=${input.width}x${input.height}:r=${input.fps}:d=${input.durationMs / 1000}`, "-f", "lavfi", "-i", `sine=frequency=440:sample_rate=8000:duration=${input.durationMs / 1000}`, "-shortest", "-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac", path], { windowsHide: true }); return { path, width: input.width, height: input.height, fps: input.fps, durationMs: input.durationMs, cleanup: () => rm(directory, { recursive: true, force: true }) }; } };

async function fixture() { const suffix = crypto.randomUUID(), user = await prisma.user.create({ data: { email: `${suffix}@phase5-durability.test` } }), workspace = await prisma.workspace.create({ data: { name: suffix } }); users.push(user.id); workspaces.push(workspace.id); await prisma.workspaceMember.create({ data: { workspaceId: workspace.id, userId: user.id, role: "OWNER" } }); const source = await prisma.source.create({ data: { workspaceId: workspace.id, kind: "FILE", displayName: "book.md" } }), blob = await prisma.sourceBlob.create({ data: { workspaceId: workspace.id, sha256: suffix, sizeBytes: 1, mediaType: "text/markdown", storageKey: `phase5/${suffix}` } }), document = await prisma.sourceDocument.create({ data: { workspaceId: workspace.id, sourceId: source.id, sourceBlobId: blob.id, version: 1, sha256: suffix, sizeBytes: 1, mediaType: "text/markdown", storageKey: blob.storageKey } }), job = await prisma.job.create({ data: { workspaceId: workspace.id, type: "source.ingest", payload: {} } }), ingestion = await prisma.ingestionRun.create({ data: { workspaceId: workspace.id, sourceDocumentId: document.id, jobId: job.id, parserVersion: "test", normalizationVersion: "test" } }), extraction = await prisma.documentExtraction.create({ data: { workspaceId: workspace.id, sourceDocumentId: document.id, ingestionRunId: ingestion.id, status: "SUCCEEDED", parserName: "test", parserVersion: "test", normalizationVersion: "test" } }); for (const [ordinal, text] of ["# Evidence", "A grounded direct quote explains why evidence matters.", "Context remains bounded and independent."].entries()) await prisma.sourceBlock.create({ data: { extractionId: extraction.id, ordinal, kind: ordinal === 0 ? "HEADING" : "PARAGRAPH", text, contentHash: `${suffix}-${ordinal}` } }); await prisma.currentDocumentExtraction.create({ data: { workspaceId: workspace.id, sourceDocumentId: document.id, extractionId: extraction.id } }); await materializeChunkSet({ workspaceId: workspace.id, sourceDocumentId: document.id, configuration: { targetSize: 80, hardMax: 120 } }); const embeddings = new DeterministicFakeEmbeddingProvider(), analysis = await requestBookAnalysis({ workspaceId: workspace.id, sourceDocumentId: document.id, pipelineVersion: "phase5-a", promptVersion: "a", provider: "analysis", model: "fixture", modelVersion: "1" }); await processBookAnalysisRun(analysis.run.id, { analysisProvider: new Analysis("A_ONLY_MARKER"), embeddingProvider: embeddings }); const context = { workspaceId: workspace.id, userId: user.id }, project = await createShortVideoProject(context, { name: "Evidence", sourceDocumentIds: [document.id] }), style = await configureShortVideoStyle(context, project.id, { targetDurationSeconds: 15 }); return { context, workspace, document, embeddings, project, style }; }
async function request(data: Awaited<ReturnType<typeof fixture>>, promptVersion: string = crypto.randomUUID()) { return requestShortVideoGeneration(data.context, { shortVideoProjectId: data.project.id, styleProfileId: data.style.id, ...new Video().identity, pipelineVersion: "phase5", promptVersion, retrievalVersion: "v1", scenePlannerVersion: "v1", captionVersion: "v1", audioVersion: "v1", renderVersion: "v1" }); }
async function runGeneration(runId: string, provider = new Video(), embeddings = new DeterministicFakeEmbeddingProvider(), faultInjector?: any, renderer?: VideoRenderer) { return processShortVideoGenerationRun(runId, { provider, embeddingProvider: embeddings, tts: new Tts(), storage, renderer, renderConfiguration: { width: 360, height: 640, fps: 15 }, faultInjector }); }
async function expire(runId: string) { await prisma.$executeRaw`UPDATE "ShortVideoGenerationRun" SET "executionLeaseUntil" = NOW() - INTERVAL '1 second' WHERE "id" = ${runId}`; }
afterEach(async () => { workspaces.splice(0); users.splice(0); }); afterAll(() => prisma.$disconnect());

describe("durable Phase 5 short-video generation", () => {
  it("resumes persisted planning work after a deterministic partial crash", async () => { const data = await fixture(), requested = await request(data, "resume"), provider = new Video(); let crashed = false; await expect(runGeneration(requested.run.id, provider, data.embeddings, (point: string) => { if (point === "afterPlanPersist" && !crashed) { crashed = true; throw new Error("PLAN_CRASH"); } })).rejects.toThrow("PLAN_CRASH"); expect(await prisma.shortVideoPlan.count({ where: { shortVideoGenerationRunId: requested.run.id } })).toBe(1); await runGeneration(requested.run.id, provider, data.embeddings); expect((await prisma.shortVideoGenerationRun.findUniqueOrThrow({ where: { id: requested.run.id } })).status).toBe("SUCCEEDED"); });
  it("rejects stale successful persistence after worker B reclaims the expired lease", async () => { const data = await fixture(), requested = await request(data, "stale-success"), a = new Video(); let entered!: () => void, release!: () => void; const enteredP = new Promise<void>(resolve => entered = resolve), releaseP = new Promise<void>(resolve => release = resolve); a.entered = entered; a.release = releaseP; const stale = runGeneration(requested.run.id, a, data.embeddings); await enteredP; await expire(requested.run.id); await runGeneration(requested.run.id, new Video(), data.embeddings, undefined, lightweightRenderer); release(); await expect(stale).rejects.toThrow("SHORT_VIDEO_OWNERSHIP_LOST"); expect((await prisma.shortVideoGenerationRun.findUniqueOrThrow({ where: { id: requested.run.id } })).status).toBe("SUCCEEDED"); });
  it("does not let a stale provider failure overwrite worker B success", async () => { const data = await fixture(), requested = await request(data, "stale-failure"), a = new Video(); let entered!: () => void, release!: () => void; const enteredP = new Promise<void>(resolve => entered = resolve), releaseP = new Promise<void>(resolve => release = resolve); a.entered = entered; a.release = releaseP; a.fail = true; const stale = runGeneration(requested.run.id, a, data.embeddings); await enteredP; await expire(requested.run.id); await runGeneration(requested.run.id, new Video(), data.embeddings); release(); await expect(stale).rejects.toThrow("PLANNING_PROVIDER_FAILED"); expect((await prisma.shortVideoGenerationRun.findUniqueOrThrow({ where: { id: requested.run.id } })).status).toBe("SUCCEEDED"); });
  it("makes terminal redelivery a strict no-op", async () => { const data = await fixture(), requested = await request(data, "terminal"); await runGeneration(requested.run.id, new Video(), data.embeddings, undefined, lightweightRenderer); const before = { attempts: (await prisma.job.findUniqueOrThrow({ where: { id: requested.job.id } })).attemptCount, scenes: await prisma.shortVideoScene.count({ where: { shortVideoGenerationRunId: requested.run.id } }), revision: await prisma.shortVideoRevision.count({ where: { generationRunId: requested.run.id } }) }; const provider = new Video(); await runGeneration(requested.run.id, provider, data.embeddings, undefined, lightweightRenderer); expect({ attempts: (await prisma.job.findUniqueOrThrow({ where: { id: requested.job.id } })).attemptCount, scenes: await prisma.shortVideoScene.count({ where: { shortVideoGenerationRunId: requested.run.id } }), revision: await prisma.shortVideoRevision.count({ where: { generationRunId: requested.run.id } }) }).toEqual(before); expect(provider.calls).toHaveLength(0); });
  it("keeps the request pinned to Book Intelligence A after current moves to B", async () => { const data = await fixture(), requested = await request(data, "pin-a"); const b = await requestBookAnalysis({ workspaceId: data.workspace.id, sourceDocumentId: data.document.id, pipelineVersion: "phase5-b", promptVersion: "b", provider: "analysis", model: "fixture", modelVersion: "1" }); await processBookAnalysisRun(b.run.id, { analysisProvider: new Analysis("B_ONLY_MARKER"), embeddingProvider: data.embeddings }); const provider = new Video(); await runGeneration(requested.run.id, provider, data.embeddings); const pinned = await prisma.shortVideoGenerationSource.findFirstOrThrow({ where: { shortVideoGenerationRunId: requested.run.id } }); const contexts = provider.calls.flatMap(call => call.context ?? []); expect(contexts.length).toBeGreaterThan(0); expect(contexts.every((item: any) => item.source.analysisRunId === pinned.analysisRunId && !item.content.includes("B_ONLY_MARKER"))).toBe(true); });
  it("preserves CurrentShortVideo when a later regeneration fails", async () => { const data = await fixture(), first = await request(data, "first"); await runGeneration(first.run.id, new Video(), data.embeddings); const current = await prisma.currentShortVideo.findUniqueOrThrow({ where: { shortVideoProjectId: data.project.id } }); const later = await request(data, "failed-regeneration"), failing = new Video(); failing.fail = true; await expect(runGeneration(later.run.id, failing, data.embeddings)).rejects.toThrow("PLANNING_PROVIDER_FAILED"); expect((await prisma.currentShortVideo.findUniqueOrThrow({ where: { shortVideoProjectId: data.project.id } })).revisionId).toBe(current.revisionId); });
  it("rejects corrupted stored narration bytes by SHA before rendering", async () => { const data = await fixture(), requested = await request(data, "corruption"); let persisted = false; await expect(runGeneration(requested.run.id, new Video(), data.embeddings, (point: string) => { if (point === "afterNarrationArtifactPersist" && !persisted) { persisted = true; throw new Error("NARRATION_CRASH"); } })).rejects.toThrow("NARRATION_CRASH"); const artifact = await prisma.shortVideoAudioArtifact.findFirstOrThrow({ where: { shortVideoGenerationRunId: requested.run.id } }); await storage.putObject({ key: artifact.storageKey, body: new Uint8Array([1, 2, 3]), contentType: "audio/wav" }); await expect(runGeneration(requested.run.id, new Video(), data.embeddings)).rejects.toThrow("SHORT_VIDEO_STORAGE_HASH_MISMATCH"); expect(await prisma.currentShortVideo.count({ where: { shortVideoProjectId: data.project.id } })).toBe(0); });
});
