import { prisma } from "@ai-cognitive/db";
import { randomUUID } from "node:crypto";
import { VersionedAesGcmCipher, type CredentialCipher } from "./credentials/cipher.js";
import { redactSecrets } from "./credentials/redaction.js";
import { ProviderGatewayError } from "./errors.js";
import type { ExecutionSnapshot, GatewayRequest, ResolvedRoute } from "./types.js";

type Db = typeof prisma;
type OwnerContext = { workspaceId: string; userId: string };
async function requireOwner(db: Db, context: OwnerContext): Promise<void> { const membership = await db.workspaceMember.findUnique({ where: { workspaceId_userId: context } }); if (membership?.role !== "OWNER") throw new ProviderGatewayError("AUTHORIZATION_FAILED"); }
function hint(secret: string): string { return secret.length >= 4 ? `…${secret.slice(-4)}` : "configured"; }
function boundedMetadata(value: Record<string, unknown>): Record<string, unknown> { const clean = redactSecrets(value) as Record<string, unknown>; if (JSON.stringify(clean).length > 8_192) throw new ProviderGatewayError("INTERNAL_PROVIDER_ERROR", "Provider metadata exceeds its safety bound"); return clean; }

export class ProviderGatewayRepository {
  constructor(private readonly db: Db = prisma, private readonly cipher?: CredentialCipher) {}
  async createConnection(context: OwnerContext, input: { providerKey: string; protocol: string; displayName: string; endpoint?: string; region?: string; configuration?: Record<string, unknown> }) { await requireOwner(this.db, context); const connection = await this.db.providerConnection.create({ data: { ...input, configuration: boundedMetadata(input.configuration ?? {}) as never, workspaceId: context.workspaceId } }); await this.audit(context, "CONNECTION_CREATED", "ProviderConnection", connection.id, { providerKey: input.providerKey }); return connection; }
  async updateConnection(context: OwnerContext, connectionId: string, input: { displayName?: string; endpoint?: string | null; region?: string | null; configuration?: Record<string, unknown> }) { await requireOwner(this.db, context); const connection = await this.db.providerConnection.update({ where: { id_workspaceId: { id: connectionId, workspaceId: context.workspaceId } }, data: { displayName: input.displayName, endpoint: input.endpoint, region: input.region, configuration: input.configuration ? boundedMetadata(input.configuration) as never : undefined } }); await this.audit(context, "CONNECTION_UPDATED", "ProviderConnection", connectionId, { displayName: input.displayName, endpointChanged: input.endpoint !== undefined, regionChanged: input.region !== undefined, configurationChanged: input.configuration !== undefined }); return connection; }
  async setConnectionEnabled(context: OwnerContext, connectionId: string, enabled: boolean) { await requireOwner(this.db, context); const current = await this.db.providerConnection.findUniqueOrThrow({ where: { id_workspaceId: { id: connectionId, workspaceId: context.workspaceId } } }); if (current.status === "REVOKED") throw new ProviderGatewayError("CONNECTION_DISABLED", "Revoked provider connections are terminal"); const connection = await this.db.providerConnection.update({ where: { id_workspaceId: { id: connectionId, workspaceId: context.workspaceId } }, data: { status: enabled ? "ACTIVE" : "DISABLED" } }); await this.audit(context, enabled ? "CONNECTION_ENABLED" : "CONNECTION_DISABLED", "ProviderConnection", connectionId, {}); return connection; }
  async rotateCredential(context: OwnerContext, connectionId: string, secret: string) { if (!this.cipher) throw new ProviderGatewayError("INTERNAL_PROVIDER_ERROR", "Credential vault is not configured"); await requireOwner(this.db, context); const versionId = randomUUID(); return this.db.$transaction(async tx => { const connection = await tx.providerConnection.findUnique({ where: { id_workspaceId: { id: connectionId, workspaceId: context.workspaceId } } }); if (!connection) throw new ProviderGatewayError("AUTHORIZATION_FAILED"); if (connection.status === "REVOKED") throw new ProviderGatewayError("CONNECTION_DISABLED", "Revoked provider connections cannot rotate credentials"); const latest = await tx.providerCredentialVersion.aggregate({ where: { connectionId, workspaceId: context.workspaceId }, _max: { credentialVersion: true } }); const encrypted = this.cipher!.encrypt(secret, { workspaceId: context.workspaceId, connectionId, credentialVersionId: versionId, providerKey: connection.providerKey }); await tx.providerCredentialVersion.updateMany({ where: { connectionId, workspaceId: context.workspaceId, status: "ACTIVE" }, data: { status: "RETIRED" } }); const credential = await tx.providerCredentialVersion.create({ data: { id: versionId, workspaceId: context.workspaceId, connectionId, credentialVersion: (latest._max.credentialVersion ?? 0) + 1, ...encrypted, displayHint: hint(secret), status: "ACTIVE" } }); await tx.providerAuditEvent.create({ data: { workspaceId: context.workspaceId, actorUserId: context.userId, action: latest._max.credentialVersion === null ? "CREDENTIAL_CREATED" : "CREDENTIAL_ROTATED", targetType: "ProviderCredentialVersion", targetId: credential.id, metadata: {} } }); return credential; }); }
  async revokeCredential(context: OwnerContext, credentialVersionId: string) { await requireOwner(this.db, context); const credential = await this.db.providerCredentialVersion.update({ where: { id_workspaceId: { id: credentialVersionId, workspaceId: context.workspaceId } }, data: { status: "REVOKED" } }); await this.audit(context, "CREDENTIAL_REVOKED", "ProviderCredentialVersion", credentialVersionId, {}); return credential; }
  async setRoute(context: OwnerContext, input: { routeSlot: string; connectionId: string; modelId: string; configuration?: Record<string, unknown> }) { await requireOwner(this.db, context); const connection = await this.db.providerConnection.findUniqueOrThrow({ where: { id_workspaceId: { id: input.connectionId, workspaceId: context.workspaceId } } }); if (connection.status === "REVOKED") throw new ProviderGatewayError("CONNECTION_DISABLED", "Revoked provider connections cannot be routed"); const route = await this.db.providerRouteBinding.upsert({ where: { workspaceId_routeSlot: { workspaceId: context.workspaceId, routeSlot: input.routeSlot } }, create: { ...input, configuration: boundedMetadata(input.configuration ?? {}) as never, workspaceId: context.workspaceId }, update: { connectionId: input.connectionId, modelId: input.modelId, configuration: boundedMetadata(input.configuration ?? {}) as never } }); await this.audit(context, "ROUTING_UPDATED", "ProviderRouteBinding", route.id, { routeSlot: input.routeSlot, modelId: input.modelId }); return route; }
  async resolveWorkspaceRoute(request: GatewayRequest): Promise<ResolvedRoute | undefined> { const route = await this.db.providerRouteBinding.findUnique({ where: { workspaceId_routeSlot: { workspaceId: request.workspaceId, routeSlot: request.routeSlot } }, include: { connection: true } }); if (!route) return undefined; if (route.connection.status !== "ACTIVE") throw new ProviderGatewayError("CONNECTION_DISABLED"); const credential = await this.db.providerCredentialVersion.findFirst({ where: { connectionId: route.connectionId, workspaceId: request.workspaceId, status: "ACTIVE" }, orderBy: { credentialVersion: "desc" } }); if (!credential) throw new ProviderGatewayError("AUTHENTICATION_FAILED", "No active workspace credential"); return { source: "WORKSPACE", providerKey: route.connection.providerKey, protocol: route.connection.protocol as ResolvedRoute["protocol"], modelId: route.modelId, adapterVersion: "phase8a", connectionId: route.connectionId, credentialVersionId: credential.id, endpoint: route.connection.endpoint ?? undefined, region: route.connection.region ?? undefined, capability: { modelId: route.modelId, families: [], confidence: "DECLARED" }, configuration: route.configuration as Record<string, unknown> }; }
  async persistSnapshot(snapshot: ExecutionSnapshot) { return this.db.providerExecutionSnapshot.create({ data: { id: snapshot.id, workspaceId: snapshot.workspaceId, routeSlot: snapshot.routeSlot, providerKey: snapshot.providerKey, protocol: snapshot.protocol, modelId: snapshot.modelId, connectionId: snapshot.connectionId, credentialVersionId: snapshot.credentialVersionId, endpoint: snapshot.endpoint, region: snapshot.region, capability: snapshot.capability as never, configuration: snapshot.configuration as never, configurationHash: snapshot.configurationHash, adapterVersion: snapshot.adapterVersion, promptVersion: snapshot.promptVersion, schemaVersion: snapshot.schemaVersion, pipelineVersion: snapshot.pipelineVersion, correlationId: snapshot.correlationId, createdAt: snapshot.createdAt } }); }
  async assertSnapshotCredentialUsable(workspaceId: string, snapshotId: string): Promise<void> { const snapshot = await this.db.providerExecutionSnapshot.findUnique({ where: { id_workspaceId: { id: snapshotId, workspaceId } }, include: { credentialVersion: true, connection: true } }); if (!snapshot) throw new ProviderGatewayError("AUTHORIZATION_FAILED"); if (snapshot.connection && snapshot.connection.status !== "ACTIVE") throw new ProviderGatewayError("CONNECTION_DISABLED"); if (snapshot.credentialVersion?.status === "REVOKED") throw new ProviderGatewayError("CREDENTIAL_REVOKED"); }
  /** Validates a resolved workspace route before its execution snapshot is persisted. */
  async assertResolvedRouteUsable(workspaceId: string, connectionId: string | undefined, credentialVersionId: string | undefined): Promise<void> { if (!connectionId || !credentialVersionId) throw new ProviderGatewayError("AUTHORIZATION_FAILED"); const credential = await this.db.providerCredentialVersion.findUnique({ where: { id_workspaceId: { id: credentialVersionId, workspaceId } }, include: { connection: true } }); if (!credential?.connection || credential.connectionId !== connectionId) throw new ProviderGatewayError("AUTHORIZATION_FAILED"); if (credential.connection.status !== "ACTIVE") throw new ProviderGatewayError("CONNECTION_DISABLED"); if (credential.status === "REVOKED") throw new ProviderGatewayError("CREDENTIAL_REVOKED"); }
  async appendUsage(input: { workspaceId: string; invocationId: string; attemptId: string; attemptNumber: number; providerKey: string; connectionId?: string; modelId: string; capability: string; routeSlot: string; status: "SUCCEEDED" | "FAILED"; inputTokens?: number; outputTokens?: number; embeddingInputTokens?: number; speechInputCharacters?: number; audioDurationMs?: number; latencyMs?: number; remoteRequestId?: string; metadata?: Record<string, unknown> }) { return this.db.providerUsageEvent.create({ data: { ...input, metadata: input.metadata ? boundedMetadata(input.metadata) as never : undefined } }); }
  private async audit(context: OwnerContext, action: "CONNECTION_CREATED" | "CONNECTION_UPDATED" | "CONNECTION_DISABLED" | "CONNECTION_ENABLED" | "CREDENTIAL_REVOKED" | "ROUTING_UPDATED", targetType: string, targetId: string, metadata: Record<string, unknown>) { await this.db.providerAuditEvent.create({ data: { workspaceId: context.workspaceId, actorUserId: context.userId, action, targetType, targetId, metadata: boundedMetadata(metadata) as never } }); }
}

export function testCipher(): VersionedAesGcmCipher { return new VersionedAesGcmCipher("test-v1", new Map([["test-v1", Buffer.alloc(32, 7)]])); }
